### ISSUE TITLE
Only works with `chunkIds: 'named'` and `chunkFilename: '[name].chunk.bundle'`

### ISSUE THREAD

**Issue by oblador** [callstack/repack#107]
## Description

For optimization purposes one might want to use a different value for `chunkIds` or `chunkFilename`, but repack makes too many assumptions on the setup instead of using the config values when building the `__CHUNKS__` variable and when loading the chunks on the native side. 

## Reproducible Demo

Change to `chunkIds: 'size'` or `chunkFilename: '[id].chunk.bundle'`.

**Comment by zamotany** [comment]
The problem with chunk ids is more complex than what's put into `__CHUNKS__` - that easy to fix. The bigger problem is that with `chunkIds` other than `named`, you end up with number. Those number will be passed to `resolveRemoteChunk` function so figuring out where each chunk is hosted my be really problematic. The situation is complicated even more by the fact that if `chunkIds` is other than `named`, chunk is only assigned numeric `id` without a `name` (which is `null`), so we cannot even provide any kind of mapping from `names` to `id`s. To do that we would need to reimplement Webpack's naming logic, which means more surface to maintain. Moreover there are chunks with `id`s specified manually (via `webpackChunkName` magic comment), which takes priority over `chunkIds` options.
