### ISSUE TITLE
How to download chunk from server on demand

### ISSUE THREAD

**Issue by daiquangduy** [callstack/repack#129]
## Ask your Question

I have 2 questions:

1. When I use ChunkManager.loadChunk('miniapp'), 
I received log: [DevServer@ios] Route GET:/undefined not found.
Do I have a missing config somewhere?

2. I understand that I can code a Remote component -> bundle remote chunk has name is remote.chunk.bundle -> upload this chunk to my server -> and in my other project, I can display Remote component without any code related to this Remote component by downloading remote.chunk.bundle via ChunkManager.
Is my understanding correct?

I had code:

`index.js`
```javascript
import { AppRegistry } from 'react-native';
import { ChunkManager } from '@callstack/repack/client';
import AsyncStorage from '@react-native-async-storage/async-storage';
import App from './src';
import { name as appName } from './app.json';

ChunkManager.configure({
    storage: AsyncStorage,
    resolveRemoteChunk: async (chunkId) => {
        return {
            url: `https://dev-api.mydomain.com/students/${chunkId}`,
        };
    },
});

AppRegistry.registerComponent(appName, () => App);
```

`src/index.js`
```javascript
import React from 'react';
import { Text } from 'react-native';

const Remote = React.lazy(
    () => import(/* webpackChunkName: "remote" */ './Remote.js')
);

const App = () => {
    return (
        <React.Suspense fallback={<Text>Loading...</Text>}>
            <Remote />
        </React.Suspense>
    );
}

export default App;
``` 

But I get the error: Can't not find module './Remote.js'.

Please help me. Thank you !!!

**Comment by TMaszko** [comment]
In the development mode you can use flag `forceRemoteChunkResolution` and it will use provided url as a source URL instead of the current dev server :)

**Comment by ashutoshd11** [comment]
@TMaszko @zamotany   did `forceRemoteChunkResolution`  set to true will fetch all chunks or it will consider to fetch only changed chunks.

**Comment by RafikiTiki** [comment]
As @zamotany suggested – Module Federation is probably the right option for your use case, luckily repack v3 has official support for MF built in.
