### ISSUE TITLE
Support custom webpack watch options/polling

### ISSUE THREAD

**Issue by milesj** [callstack/repack#137]
## Describe the feature

Support configurable watch options, which would be passed in places like here: https://github.com/callstack/repack/blob/main/packages/repack/src/server/compilerWorker.ts#L10

## Motivation

We use Bazel for our monorepo setup, which utilizes symlinks heavily. Webpack file watching does not respond to file changes through symlinks, so we need to use polling for HMR to work correctly. Right now we are patching the package, like so:

```diff
-compiler.watch({}, error => {
+compiler.watch({ poll: 500 }, error => {
```

Would be great if this was supported natively.

**Comment by zamotany** [comment]
Have you tried passing `watchOptions` to Webpack config? https://webpack.js.org/configuration/watch/#watchoptions
