### ISSUE TITLE
Support Tree shaking

### ISSUE THREAD

**Issue by roshan-lmi** [callstack/repack#142]
How does tree shaking support look like with repack ? 
We have scenarios where we are using cross platform sdk for web, mobile. It contains certain code/dependencies that's only used in web. So, I wanted to know if it's possible to tree shake these dependencies in case of mobile as we don't use it. 

Would these config like usedExports and sideEffects work right away? 
https://webpack.js.org/guides/tree-shaking/

**Comment by zamotany** [comment]
> How does tree shaking support look like with repack ?

Re.Pack doesn't do tree shaking, Webpack does and it works exactly the same way as in plain Webpack. Re.Pack doesn't change that behaviour.

> Would these config like usedExports and sideEffects work right away?

They should.

**Comment by zamotany** [comment]
Ah, one thing to keep in mind: `metro-react-native-babel-preset` transpiles ESM to CJS and Webpack uses ESM primarily for tree shaking, so in order to fully benefit from treeshaking, you have to pass `disableImportExportTransform` to `metro-react-native-babel-preset` but only for your source files.

In the default Webpack config there are 2 `babel-loader` which you will have to modify:

```js
      {
        test: /\.[jt]sx?$/,
        include: [
          /node_modules(.*[/\\])+react/,
          /node_modules(.*[/\\])+@react-native/,
          /node_modules(.*[/\\])+@react-navigation/,
          /node_modules(.*[/\\])+@react-native-community/,
          /node_modules(.*[/\\])+@expo/,
          /node_modules(.*[/\\])+pretty-format/,
          /node_modules(.*[/\\])+metro/,
          /node_modules(.*[/\\])+abort-controller/,
          /node_modules(.*[/\\])+@callstack\/repack/,
        ],
        use: 'babel-loader',
        // This should transform ESM to CJS
        options: {
          configFile: false,
          babelrc: false,
          presets: ['module:metro-react-native-babel-preset']
        }
      },
      /**
       * Here you can adjust loader that will process your files.
       *
       * You can also enable persistent caching with `cacheDirectory` - please refer to:
       * https://github.com/babel/babel-loader#options
       */
      {
        test: /\.[jt]sx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          // This should NOT transform ESM to CJS
          options: {
            configFile: false,
            babelrc: false,
            presets: [
              ['module:metro-react-native-babel-preset', { disableImportExportTransform: true }]
            ],
            /** Add React Refresh transform only when HMR is enabled. */
            plugins: devServer.hmr ? ['module:react-refresh/babel'] : undefined,
          },
        },
      },
```

**Comment by joe06102** [comment]
> Ah, one thing to keep in mind: `metro-react-native-babel-preset` transpiles ESM to CJS and Webpack uses ESM primarily for tree shaking, so in order to fully benefit from treeshaking, you have to pass `disableImportExportTransform` to `metro-react-native-babel-preset` but only for your source files.
> 
> In the default Webpack config there are 2 `babel-loader` which you will have to modify:
> 
> ```js
>       {
>         test: /\.[jt]sx?$/,
>         include: [
>           /node_modules(.*[/\\])+react/,
>           /node_modules(.*[/\\])+@react-native/,
>           /node_modules(.*[/\\])+@react-navigation/,
>           /node_modules(.*[/\\])+@react-native-community/,
>           /node_modules(.*[/\\])+@expo/,
>           /node_modules(.*[/\\])+pretty-format/,
>           /node_modules(.*[/\\])+metro/,
>           /node_modules(.*[/\\])+abort-controller/,
>           /node_modules(.*[/\\])+@callstack\/repack/,
>         ],
>         use: 'babel-loader',
>         // This should transform ESM to CJS
>         options: {
>           configFile: false,
>           babelrc: false,
>           presets: ['module:metro-react-native-babel-preset']
>         }
>       },
>       /**
>        * Here you can adjust loader that will process your files.
>        *
>        * You can also enable persistent caching with `cacheDirectory` - please refer to:
>        * https://github.com/babel/babel-loader#options
>        */
>       {
>         test: /\.[jt]sx?$/,
>         exclude: /node_modules/,
>         use: {
>           loader: 'babel-loader',
>           // This should NOT transform ESM to CJS
>           options: {
>             configFile: false,
>             babelrc: false,
>             presets: [
>               ['module:metro-react-native-babel-preset', { disableImportExportTransform: true }]
>             ],
>             /** Add React Refresh transform only when HMR is enabled. */
>             plugins: devServer.hmr ? ['module:react-refresh/babel'] : undefined,
>           },
>         },
>       },
> ```

You really save my day!
