### ISSUE TITLE
Getting weird issues when switching to repack from metro

### ISSUE THREAD

**Issue by roshan-lmi** [callstack/repack#143]
After switching to repack, I am getting issues related to component rendering which looks like this: 

``` 
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CallFlipCard`. - Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CallFlipCard`.
```

I know this happens when import/export is wrong but no idea why is this happening with webpack config but working fine with metro.
 Bundling is okayish though (with some errors). (https://github.com/callstack/repack/issues/138)

**Comment by roshan-lmi** [comment]
Somehow, in one of the files. re-exporting a component in a index.ts had syntax error in case of webpack. 
The import looked like 
`export * from './ActionMenu'` and it was returning undefined. When I use, `ActionMenu.ts` then it works. Strange that this is only happening in this file but these type of import/export is everywhere in the code base.

**Comment by zamotany** [comment]
Generally, you should be using Re.Pack's utility for that: https://github.com/callstack/repack/blob/main/templates/webpack.config.js#L75-L82

**Comment by roshan-lmi** [comment]
Thanks. I will check.
