### ISSUE TITLE
Potential bug in asset scale sorting

### ISSUE THREAD

**Issue by bjornallvin** [callstack/repack#157]
This location in the asset loader could lead to trouble if the asset has a decimal point in the resolution suffix. Like 'image@2.5x'. On sorting we now parse those number to ints. It should probably be parseFloat to be sure right?

https://github.com/callstack/repack/blob/f30ded4b25e17320877b8cd2975af9f7a5de971a/packages/repack/src/webpack/loaders/assetsLoader.ts#L109-L113

**Comment by zamotany** [comment]
This was fixed in #156

**Comment by bjornallvin** [comment]
> This was fixed in #156

I know, I issued that bug :-)  This is another location in the code though.

**Comment by TMaszko** [comment]
Yeah good catch again :) I'll fix it quickly :) Thanks !
