### ISSUE TITLE
Cannot load chunk from express server

### ISSUE THREAD

**Issue by voanhtuan318** [callstack/repack#165]
Hi, I would like to test run your example project from the link https://github.com/callstack/repack/tree/main/packages/TesterApp. When I replace the configuration forceRemoteChunkResolution: true and try to build an express server with the following code and directory structure:
const express = require('express');
const app = express();
const PORT = 5000;

app.get('/', (req, res) => {
     res.send('Hello World!');
});
app.use(express.static('public'));

app.listen(PORT, () => console.log(`Server listening on port: ${PORT}`));
When I test the Preload Chunk function of the example I don't see a problem reported but then I execute the general load function an issue is displayed as shown. Can you help me to solve it.

<img width="964" alt="Screen Shot 2022-03-04 at 17 27 37" src="https://user-images.githubusercontent.com/44761312/156746926-013dc445-d504-492e-8e4f-6355495c45c9.png">

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-03-04 at 17 31 59](https://user-images.githubusercontent.com/44761312/156747267-53e9ed73-5e85-43f9-82de-54e6e6cdbac0.png)

**Comment by zamotany** [comment]
The unexpected token `<` suggests that the URL `ChunkManager` is using to download the bundle returns a HTML instead of a JS bundle and so evaluating it throws the error.

1. What's the result if you try to open `http://localhost:5000/remote.chunk.bundle` in the browser?
2. You can also check saved "bundle" in simulator storage to see what's the content of it (they are saved in `chunks` in App's directory)

**Comment by voanhtuan318** [comment]
1. I try open http://localhost:5000/remote.chunk.bundle in the browser, This bundle file is automatically downloaded as shown in the attached image
<img width="282" alt="Screen Shot 2022-03-04 at 19 43 47" src="https://user-images.githubusercontent.com/44761312/156765930-4169e164-acc2-4032-9b33-7347507d6aaf.png">

**Comment by voanhtuan318** [comment]
2. I check saved "bundle" in simulator storage to see what's the content of it (they are saved in chunks in App's directory) show in  the attached image
<img width="771" alt="Screen Shot 2022-03-04 at 19 56 50" src="https://user-images.githubusercontent.com/44761312/156767527-bcdd1b2b-821d-4f88-ae81-be21634d8123.png">

**Comment by voanhtuan318** [comment]
remote.chunk.bundle have content:
(self.webpackChunkTesterApp=self.webpackChunkTesterApp||[]).push([["remote"],{95659:function(t,e,n){var r=n(95318);Object.defineProperty(e,"__esModule",{value:!0}),e.default=function(){return(0,o.default)((function(){}),0),i.default.createElement(u.Text,null,"Remote: this text comes from remote chunk111")};var i=r(n(35466)),o=r(n(93096)),u=n(79765)},93096:function(t,e,n){var r="Expected a function",i=/^\s+|\s+$/g,o=/^[-+]0x[0-9a-f]+$/i,u=/^0b[01]+$/i,f=/^0o[0-7]+$/i,a=parseInt,c="object"==typeof n.g&&n.g&&n.g.Object===Object&&n.g,l="object"==typeof self&&self&&self.Object===Object&&self,s=c||l||Function("return this")(),p=Object.prototype.toString,v=Math.max,d=Math.min,m=function(){return s.Date.now()};function b(t,e,n){var i,o,u,f,a,c,l=0,s=!1,p=!1,b=!0;if("function"!=typeof t)throw new TypeError(r);function h(e){var n=i,r=o;return i=o=void 0,l=e,f=t.apply(r,n)}function j(t){return l=t,a=setTimeout(x,e),s?h(t):f}function T(t){var n=t-c;return void 0===c||n>=e||n<0||p&&t-l>=u}function x(){var t=m();if(T(t))return O(t);a=setTimeout(x,function(t){var n=e-(t-c);return p?d(n,u-(t-l)):n}(t))}function O(t){return a=void 0,b&&i?h(t):(i=o=void 0,f)}function w(){var t=m(),n=T(t);if(i=arguments,o=this,c=t,n){if(void 0===a)return j(c);if(p)return a=setTimeout(x,e),h(c)}return void 0===a&&(a=setTimeout(x,e)),f}return e=g(e)||0,y(n)&&(s=!!n.leading,u=(p="maxWait"in n)?v(g(n.maxWait)||0,e):u,b="trailing"in n?!!n.trailing:b),w.cancel=function(){void 0!==a&&clearTimeout(a),l=0,i=c=o=a=void 0},w.flush=function(){return void 0===a?f:O(m())},w}function y(t){var e=typeof t;return!!t&&("object"==e||"function"==e)}function g(t){if("number"==typeof t)return t;if(function(t){return"symbol"==typeof t||function(t){return!!t&&"object"==typeof t}(t)&&"[object Symbol]"==p.call(t)}(t))return NaN;if(y(t)){var e="function"==typeof t.valueOf?t.valueOf():t;t=y(e)?e+"":e}if("string"!=typeof t)return 0===t?t:+t;t=t.replace(i,"");var n=u.test(t);return n||f.test(t)?a(t.slice(2),n?2:8):o.test(t)?NaN:+t}t.exports=function(t,e,n){var i=!0,o=!0;if("function"!=typeof t)throw new TypeError(r);return y(n)&&(i="leading"in n?!!n.leading:i,o="trailing"in n?!!n.trailing:o),b(t,e,{leading:i,maxWait:e,trailing:o})}}}]);//# sourceMappingURL=remote.chunk.bundle.map?platform=ios

**Comment by voanhtuan318** [comment]
@zamotany please help me resolve this problem, thanks.

**Comment by RafikiTiki** [comment]
Hi @voanhtuan318 could you create a reproduction repo with both the app and the express server?

**Comment by jbroma** [comment]
Closing as stale, please open a new issue if the issue still persists
