### ISSUE TITLE
Missing type definitions for `@callstack/repack/client`

### ISSUE THREAD

**Issue by tom-sherman** [callstack/repack#169]
```
import { ChunkManager } from '@callstack/repack/client';
```

This import produces a typescript error of `Could not find a declaration file for module '@callstack/repack/client'.`. The type definition for `client.js` are missing.

Fixable by adding a `client.d.ts` file with the following content:

```ts
export * from './dist/client/api';
```

**Comment by zamotany** [comment]
Fixed in #183
