### ISSUE TITLE
There are some error log when I start devServer

### ISSUE THREAD

**Issue by NiuGuohui** [callstack/repack#170]
I think they are dependency issues.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/37471959/168234836-9707e9db-8e32-4f3b-b9a6-c6a52fdbfa0b.png">

**Comment by zamotany** [comment]
Those deprecation errors don't affect the behaviour of Re.Pack and can be safely ignored. They will be gone in new upcoming version 3 of Re.Pack.
