### ISSUE TITLE
ChunkManager.resolveChunk error on android dynamic import in production

### ISSUE THREAD

**Issue by jd1378** [callstack/repack#173]
## Description

dynamic imports not working as expected in production builds where the chunks are bundled locally.

## Reproducible Demo

https://github.com/jd1378/repack_dynamic_import_bug

**Comment by zamotany** [comment]
There were multiple issues with local chunks in version 2. In upcoming version 3, local chunks are handled differently, so most of the problems should go away. I'm closing this issue, since it's unlikely there will be a fix in version 2. Once 3 is officially released, everyone should upgrade to it.
