### ISSUE TITLE
Kotlin version issue on react-native run-android

### ISSUE THREAD

**Issue by singhalpranav22** [callstack/repack#184]
## Environment
Basic boilerplate project made as show in the docs : https://re-pack.netlify.app/docs/getting-started

## Description
react-native run-android build failing due to this error:
<img width="998" alt="Screenshot 2022-06-26 at 2 29 11 AM" src="https://user-images.githubusercontent.com/51447798/175790373-92c2e462-aa08-40e4-9f45-8519f5f7e5fb.png">

Errors : The class is loaded from /Users/pranav.singhal/.gradle/caches/transforms-3/b4bd8b2d8b84f89e1b1eb3315da16eb4/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/pranav.singhal/Documents/code-splitting/trials/trial3/node_modules/@callstack/repack/android/src/main/java/com/callstack/repack/RemoteChunkLoader.kt: (106, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

Also, tried to change the kotlin version in @callstack/repack/android/build.gradle
## Reproducible Demo
Just create a new project by react-native init <project-name>
And add all the configurations as follows : https://re-pack.netlify.app/docs/getting-started
Take help of my repo as well : https://github.com/singhalpranav22/react-native-project

**Comment by DaveWelling** [comment]
Yeah, I'm getting this too.  It looks like react-native 0.69.0 [bumped the kotlin version](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#:~:text=Bump%20Kotlin%20version%20to%201.6.10%20(d0f0234656%20by%20%40AKB48)).
which is breaking a bunch of your kotlin modules (e.g. ChunkManagerModule.kt).

**Comment by singhalpranav22** [comment]
@DaveWelling , Yes you are right!

**Comment by zamotany** [comment]
You don't need to patch or modify anything in `node_modules`. Open your `android/build.gradle` and add `kotlinVersion = "1.6.0"` to `buildscript.ext` like so:
```groovy
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        kotlinVersion = "1.6.0"
    
    // ...
    }

    // ...
}
```

**Comment by saifbak** [comment]
I have figured out the solution. try this  [https://github.com/facebook/react-native/issues/35210](url)

**Comment by zaid-themedcompany** [comment]
In my case the following fixed the issue:

       buildscript {

          ext {
              ...
               kotlinVersion = "1.8.0"
           }
