### ISSUE TITLE
[Enhancement] devDependencies "fastify" warning

### ISSUE THREAD

**Issue by Guang1234567** [callstack/repack#197]
Hello dev:

I just test `repack` in a typescript reactnative templateApp, but found some warning when `react-native webpack-start --reset-cache` as below code and snapshot, thanks.

https://github.com/callstack/repack/blob/6f42c687511e13c7f4ba644f08fcaf9f40069efd/packages/repack/package.json#L69-L70

![snapshot](https://user-images.githubusercontent.com/8240718/177676089-e1458eaa-c39c-4e51-ba05-66c164b9cd0c.png)

**Comment by zamotany** [comment]
Thanks for opening the issue.

In upcoming version `3.x` of Re.Pack, `fastify-static` is replaced by `@fastify/static` and `fastify-reply-from` is no longer used, so there won't be any deprecation warnings.
