### ISSUE TITLE
redundant chunks

### ISSUE THREAD

**Issue by hds220** [callstack/repack#206]
## Environment

 "webpack": "^5.73.0"
"@callstack/repack": "^2.5.2",

## Description

redundant chunks
![image](https://user-images.githubusercontent.com/6418201/179710554-0a310ec6-2432-4dff-b9a6-6b540aa5d855.png)

## Reproducible Demo
import React,{Suspense} from 'react';
import {Text} from 'react-native';
import {createStackNavigator} from 'react-navigation-stack';

const ConsentApp = React.lazy(
  () => import(/* webpackChunkName: "ConsentApp" */'../../../epp-patient-mini-app/src/Consent/ConsentStackNavigator.js')
);

const ConsentStackNavigator = () => {
  return (
    <Suspense fallback={<Text>Loading...</Text>}>
      <ConsentApp />
    </Suspense>
  );
};

const AuthStackNavigator = createStackNavigator(
  {
    Main: {
      screen: MainScreen,
    },
    InAppBrowser: {
      screen: InAppBrowser,
    },
.......

**Comment by hds220** [comment]
@zamotany This problem occurs when there are two chunks， I've tried many times, but I can't find the reason. could you help me？

**Comment by zamotany** [comment]
This is default behaviour in Webpack. To change this I suggest to look into `optimization.splitChunk` options:  https://webpack.js.org/plugins/split-chunks-plugin/ more specifically at cache groups: https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroups
