### ISSUE TITLE
Updated installation/migration docs

### ISSUE THREAD

**Issue by joeyfigaro** [callstack/repack#21]
## Describe the feature

Complete steps to go from using Metro to using react-native-webpack-toolkit. Should walk through installation, configuration, and starting up a development server.

## Motivation

Current installation instructions do not result in a working development environment. Attempting to run `yarn react-native webpack-start` with the template webpack config complains about missing flags for host, port, projectRoot, watchFolders, assetPlugins, etc.

## Related Issues

N/A

**Comment by joeyfigaro** [comment]
Attempting to use `react-native.config.js` to specify these options does not seem to work with or without specifying `--config <location-of-config>`

**Comment by zamotany** [comment]
What React Native version are you using? Can you run & past the results of `npm ls @react-native-community/cli`??

**Comment by joeyfigaro** [comment]
@zamotany apologies for missing this–I'm on rn `0.64.1` and looks like `5.0.1-alpha.2` for the cli.

**Comment by zamotany** [comment]
@joeyfigaro Looks fine, not sure why the issue is happening. Can you use `@callstack/nativepack@1.4.0` and use new getting started steps??

**Comment by chakravarthy-mm** [comment]
When I try webpack-start I get 
**Unrecognized command "webpack-start"**

**Comment by chakravarthy-mm** [comment]
I just created wrong file name `reactnative.config.js` instead of `react-natve.config.js`

Sorry
