### ISSUE TITLE
Production remote bundles fails to load without any error message 

### ISSUE THREAD

**Issue by a839128** [callstack/repack#210]
## Environment

We are using ChunkManager APIs of module-federation to load remote bundles. We tried in both iOS and android platforms but faced same issue on both. 

## Description

We are using following command to create production bundles (container and chunk bundles). Then we load these bundles, as remote bundles, but they fails to load and we are stuck at loading state. 

`STANDALONE=1 react-native webpack-bundle --platform ios --dev false --entry-file index.js --bundle-output bundle/index.bundle`

Where as if we run the same code, but with development bundles created using following command they are loaded properly. Note the difference in both commands is - `--dev true/ false`

`STANDALONE=1 react-native webpack-bundle --platform ios --dev true --entry-file index.js --bundle-output bundle/index.bundle`

## Reproducible Demo

We are using following example to load remote bundles, using ChunkManager APIs of repack module-federation. 
https://github.com/zamotany/module-federation-repack

Any help will be highly appreciated.

Thank you!

**Comment by zamotany** [comment]
Any errors in terminal, logcat or Console.app? Also are you trying to run host app or individual apps?

**Comment by a839128** [comment]
There is nothing in the logs. Please find below the logs from terminal (running host server webpack/repack) and logcat. Please note we have removed the actual s3 link and android package Id from the logs.

We are running host app on local machine, and widget apps bundles are created using the command mentioned in the above post and hosted in AWS S3 bucket. We also tried hosing the widget apps bundles in localhost, but same results.    

Terminal log - 

```
[02:53:26.481Z][DevServerProxy] response received 
[02:53:33.939Z][Console] i18next::translator: missingKey en-US host route.NAVIGATION_HOME_KEY route.NAVIGATION_HOME_KEY 
[02:53:33.944Z][Console] i18next::translator: missingKey en-US host route.NAVIGATION_FARMS_AND_FIELDS_KEY route.NAVIGATION_FARMS_AND_FIELDS_KEY 
[02:53:34.668Z][Console] main | widget2 | <aws s3 link>/widget2.container.bundle 
[02:53:37.169Z][Console] main | widget1 | <aws s3 link>/widget1.container.bundle 
```

Logcat log - 
```
ReactNativeJS: 'i18next::translator: missingKey', 'en-US', 'host', 'route.NAVIGATION_HOME_KEY', 'route.NAVIGATION_HOME_KEY'
ReactNativeJS: 'i18next::translator: missingKey', 'en-US', 'host', 'route.NAVIGATION_FARMS_AND_FIELDS_KEY', 'route.NAVIGATION_FARMS_AND_FIELDS_KEY'
ReactNativeJS: main | widget2 | <aws s3 link prefix>widget2.container.bundle
.mxp.host.stag: Background young concurrent copying GC freed 82288(3612KB) AllocSpace objects, 1(16KB) LOS objects, 0% free, 18MB/18MB, paused 7.081ms total 91.494ms
.mxp.host.stag: Background concurrent copying GC freed 9336(2495KB) AllocSpace objects, 4(9024KB) LOS objects, 33% free, 11MB/17MB, paused 594us total 116.229ms
ReactNativeJS: main | widget1 | <aws s3 link prefix>widget1.container.bundle
```

**Comment by zamotany** [comment]
Can you post configuration for `webpack.container.ModuleFederationPlugin`s and a config for `ChunkManager.configure`?

**Comment by ReneLa** [comment]
Am also stuck on this, host app load containers properly in development mode but is stuck loading while fetching the container from a remote server. (for testing the remote container is hosted on Cloudinary). is there any configuration am missing???

**Comment by namnh240795** [comment]
![Screen Shot 2022-11-30 at 14 45 20](https://user-images.githubusercontent.com/20696416/204736912-49cdb4a5-97ec-411e-9986-f70eb1b61f41.png)
i also try getRemoteUrl but has the same issue that the chunk could not be resolved.

**Comment by dhayaljaswantgit** [comment]
Hello, have you found a solution for this issue yet? I'm currently experiencing the same problem.

**Comment by dhayaljaswantgit** [comment]
> ## Environment
> We are using ChunkManager APIs of module-federation to load remote bundles. We tried in both iOS and android platforms but faced same issue on both.
> 
> ## Description
> We are using following command to create production bundles (container and chunk bundles). Then we load these bundles, as remote bundles, but they fails to load and we are stuck at loading state.
> 
> `STANDALONE=1 react-native webpack-bundle --platform ios --dev false --entry-file index.js --bundle-output bundle/index.bundle`
> 
> Where as if we run the same code, but with development bundles created using following command they are loaded properly. Note the difference in both commands is - `--dev true/ false`
> 
> `STANDALONE=1 react-native webpack-bundle --platform ios --dev true --entry-file index.js --bundle-output bundle/index.bundle`
> 
> ## Reproducible Demo
> We are using following example to load remote bundles, using ChunkManager APIs of repack module-federation. https://github.com/zamotany/module-federation-repack
> 
> Any help will be highly appreciated.
> 
> Thank you!

Hello, have you found a solution for this issue yet? I'm currently experiencing the same problem.

https://github.com/callstack/repack/issues/505
