### ISSUE TITLE
When is module federations planned to be supported/ launched officially? 

### ISSUE THREAD

**Issue by a839128** [callstack/repack#213]
Can we please know, when is module federations planned to be supported/ launched officially? 

We can see some new APIs like `import { Federated } from '@callstack/repack/client';` being introduced in the latest example code `https://github.com/callstack/repack-examples/tree/main/module-federation` related to module federation. These new APIs looks very interesting. 

We understand that this is still under development in version 3. 

Is there a planned/ estimated timeline for module federation official launch?

**Comment by thymikee** [comment]
The feature is available in alpha channel. We're still in the testing phase and there's no launch date set yet. We'll keep you updated :)

**Comment by leotm** [comment]
awesome ^ and good spot on the new APIs

think can close this since being tracked with more details in
- https://github.com/callstack/repack/issues/60

**Comment by a839128** [comment]
Noted. Thank you!
