### ISSUE TITLE
fetch bundle from my url error

### ISSUE THREAD

**Issue by hoangdvhou** [callstack/repack#226]
## Environment

- Production

## Description

- I deploy mini app to my server, export to url "http://mobile-app-02.oneat.org/app1.container.bundle?platform=ios" . I can load bundle when access to url by browser but ChuckManager.loadChuck error

## Reproducible Demo

<img width="707" alt="Screen Shot 2022-08-31 at 08 39 12" src="https://user-images.githubusercontent.com/42249706/187624393-ab4d5b97-eb07-45f1-84b7-bf421beaa1ec.png">

**Comment by RafikiTiki** [comment]
@hoangdvhou Would you be able to create reproduction repository with your config?

**Comment by jbroma** [comment]
Closing as:
- no reproduction repository was provided
- issue became stale
