### ISSUE TITLE
New React Framework called "Repack"

### ISSUE THREAD

**Issue by brillout** [callstack/repack#228]
Hi,

I'm building a new React framework called "Repack".

The name would clash with your project. So I wanted to reach out about this. The way I see it is that Re.Pack being a webpack bundler for React Native apps and Repack being a React framework, they are different product tackling an entire different use case (although both are about React). All-in-all I think the name conflict would be okay. What do you guys think?

Kind regards,

Rom

**Comment by thymikee** [comment]
Hey! Thanks for reaching out. The brand name of this product is "Re.Pack", although out of simplicity we refer to it as "repack" in spoken word, and also as a repository name. I've contacted our marketing team to advise here.

**Comment by thymikee** [comment]
So I consulted our marketing team and we would kindly ask you change the name. We're operating in both React and React Native spaces and it would be weird for the respective communities to have both tools sharing the same name. By "weird" I mean confusion when searching or refering to it in conversation. Think "angular" and "angular js" – still confusing after years of dropping Angular.js.

**Comment by brillout** [comment]
I agree in principle, but I wonder if this will actually happen.

>  As Callstack we operate in both React and React Native spaces and it would be weird for the respective communities to have both tools sharing the same name.

Do you have a concrete example when such confusion would occur between "Re.Pack" and "Repack" leading to a tangible problem?

I'm willing to rename the project if I can "feel" the problem. Right now I feel where you come from but I still fail to see the concrete problem. Maybe because I don't know enough about Callstack. I'm more than happy to be shown wrong.

Thanks for the conversation, I'm confident we can reach a consensus.

**Comment by revskill10** [comment]
Prepack could be a good alternative.

**Comment by thymikee** [comment]
> Prepack could be a good alternative.

I'm not so sure about that: https://prepack.io 😅

**Comment by jbinda** [comment]
btw, the first result in google when searching "repack" is this: https://www.repack.com/ 😅
