### ISSUE TITLE
How to mock ChunkManager for jest tests

### ISSUE THREAD

**Issue by bea73693** [callstack/repack#229]
## Environment

`"@callstack/repack": "^2.5.2"`
`"jest": "^26.6.3",`

## Description
I have a simple jest test using react-test-renderer:

```
it('renders correctly', () => {
  renderer.create(<App />)
})
```

Where ChunkManager.configure() is called in App.tsx. After adding @callstack to transform ignore patterns `yarn test` is showing: 

`ReferenceError: __repack__ is not defined.`

I have tried many different solutions to mock this, for example:
```
global.__repack__ = jest.fn()
jest.mock('@callstack/repack/client', () => ({
  ChunkManager: {configure: jest.fn()}
}))
```

Which times out with the following error:
<img width="762" alt="Screen Shot 2022-09-08 at 3 40 55 PM" src="https://user-images.githubusercontent.com/56211155/189221777-2085c6fc-a512-4b83-baf6-a0781b78b30d.png">

I am using jest.useFakeTimers(). So what is the proper way mock this to accomplish a simple render test? Im new to this, apologies in advance.

**Comment by bea73693** [comment]
No longer seeing this issue after upgrading jest to 
`"jest": "^29.0.2"`

**Comment by DivyatejaChe** [comment]
Hey @bea73693 , I seem to run into a similar issue as well, and updating jest to the latest didn't help
`ERROR  ReferenceError: Can't find variable: __repack__`
`ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[2], "./Root").Root')`
