### ISSUE TITLE
failed build init app rn 0.70

### ISSUE THREAD

**Issue by ajiehatajie** [callstack/repack#235]
/app/appa/node_modules/@callstack/repack/android/src/main/java/com/callstack/repack/RemoteChunkLoader.kt: (124, 18): Unresolved reference: deleteRecursively

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':callstack_repack:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by jbinda** [comment]
Can you tri this: https://github.com/callstack/repack/issues/184#issuecomment-1172448429 and confirm if that works?

**Comment by jbroma** [comment]
Closing as issue became stale and this version is no longer supported anyways.
