### ISSUE TITLE
 Error: Unhandled error. ([ScriptManager] Failed to load script:):

### ISSUE THREAD

**Issue by ReneLa** [callstack/repack#242]
## Ask your Question
I'm getting this error when the host app tries to load an app bundle running on port 9000. Can any one advise

**Comment by thymikee** [comment]
Hey! Mind providing some more info about your setup? Sample repro project, Re.Pack version?

**Comment by jbinda** [comment]
Hi @ReneLa - it's very generic Error pops up in multiple situation (we're working to provide more verbose reason). However it might be related to e.g: https://github.com/callstack/repack/issues/250#issuecomment-1292606264 or simply to not installing pods.

Please try and both proposed solution and let us know if that works in your case

**Comment by ReneLa** [comment]
@jbinda the issue was specifically on android. The above solution helped... Thanks a lot

**Comment by jai924** [comment]
I am facing the same issue with IOS, any suggestions
