### ISSUE TITLE
v3 release points to non-existing page in docs

### ISSUE THREAD

**Issue by meypod** [callstack/repack#245]
I try to open this link (https://re-pack.netlify.app/docs/migration-guides/repack-v2-to-v3/) and it's not there yet it seems ?

**Comment by GitNiko** [comment]
If you find wepack.config of v3, you can check this https://github.com/callstack/repack/tree/v3/templates or https://github.com/callstack/repack-examples

**Comment by meypod** [comment]
I can see that, I just wanted to point out maybe they forgot to deploy the website again

**Comment by jbinda** [comment]
@meypod - indeed we had issue with versioned version of the docs that's why docs wasn't available for some time. If you can please confirm if all links working now.

**Comment by meypod** [comment]
it seems to be fine now

**Comment by jbinda** [comment]
cool - thanks !
