### ISSUE TITLE
Unhandled error. ([ScriptManager] Failed to load script:)

### ISSUE THREAD

**Issue by rock-hu** [callstack/repack#250]
## Environment

"react": "18.1.0",
"react-native": "0.70.1",
"@callstack/repack": "3.0.0",
host> react-native info
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
    Memory: 309.26 MB / 15.56 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
      System Images: android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16 - /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
  npmGlobalPackages:
    *react-native*: Not Found
## Description
ios platform running well on remote-chunk mode, while android always come to below issue:
✖ [07:33:52.930Z][Console] Error: Unhandled error. ([ScriptManager] Failed to load script:)
This error is located at:
    in Lazy (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in favorites(RootComponent), js engine: hermes 

**_host/index.android.js_**
_import {AppRegistry, Platform} from 'react-native';
import {ScriptManager, Script, Federated} from '@callstack/repack/client';
import App from './src/App';
import {name as appName} from './app.json';
const resolveURL = Federated.createURLResolver({
  containers: {
      app1: 'http://localhost:8080/app1/least/android/development/[name][ext]',
      app2: 'http://localhost:8080/app2/least/android/development/[name][ext]',
  },
});
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  let url;
  if (caller === 'main') {
    url = Script.getDevServerURL(scriptId);
  } else {
    url = resolveURL(scriptId, caller);
  }
  if (!url) {
    return undefined;
  }
  return {
    url,
    cache: false, // For development
    query: {
      platform: Platform.OS,
    },
  };
});
AppRegistry.registerComponent(appName, () => App);_

_**favorites/src/App.js**_
_import {Federated} from '@callstack/repack/client';
import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Platform,
} from 'react-native';
import {enableScreens} from 'react-native-screens';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

const App1 = React.lazy(() => Federated.importModule('app1', './App'));
const App2 = React.lazy(() => Federated.importModule('app2', './App'));

const TabNavigator = createBottomTabNavigator();
enableScreens(true);
class App extends React.Component {
  render() {
    return (
      <NavigationContainer>
        <TabNavigator.Navigator>
          <TabNavigator.Screen name="movies" component={App1} />
          <TabNavigator.Screen name="musics" component={App1} />
        </TabNavigator.Navigator>
      </NavigationContainer>
    );
  }
}
export default App;_
**_app1|app2/webpack.config.mjs_**
      _new Repack.plugins.ModuleFederationPlugin({
        name: 'movies',
        exposes: {
          './App': './App.js',
        },
      }),_
## Reproducible Demo
similar to https://github.com/callstack/repack-examples/tree/main/module-federation, using least rn version 
npx react-native init movies --version 0.70.1

**Comment by jbinda** [comment]
If iOS work well please do as follow:

If you run the app on Android Emulator please try to check if you can open `localhost:80801 in your Emulator browser. If not do `adb reverse tcp:8080 tcp:8080` or try alternatives from here(https://stackoverflow.com/questions/5528850/how-do-you-connect-localhost-in-the-android-emulator)

**Comment by RafikiTiki** [comment]
@rock-hu Any luck with what was suggested in the comment above?

**Comment by ViniciusUrias** [comment]
Same problem here, adb reverse didnt solve, it happens when I run my host app and try to change to some child app.
Any solutions?

**Comment by RafikiTiki** [comment]
Hey @ViniciusUrias would you be able to provide a reproduction repo and steps that lead to the error? These errors may happen for various reasons and without the ability to reproduce them locally it's very hard to find a solution.

**Comment by shivjon** [comment]
> adb reverse tcp:8080 tcp:8080

I added my child application serve port instead of 8080 to 9000.
Its work for me

**Comment by RafikiTiki** [comment]
@ViniciusUrias please create a new issue with your specific problem, and if possible – attach a reproduction repo and exact steps.

**Comment by suhassasuke** [comment]
> If iOS work well please do as follow:
> 
> If you run the app on Android Emulator please try to check if you can open `localhost:8080` in your Emulator browser. If not do `adb reverse tcp:8080 tcp:8080` or try alternatives from here(https://stackoverflow.com/questions/5528850/how-do-you-connect-localhost-in-the-android-emulator)
 
when you are using re-pack. try to start all the servers for repack [Host and miniappone and miniapptwo].

so that when you run your host app. repack will try to get your mini app through the host app server.

127.0.0.0:8081 -> host                             `adb reverse tcp:8081 tcp:8081`
127.0.0.0:8083 -> miniappone                `adb reverse tcp:8083 tcp:8083`
127.0.0.0:8084 -> miniapptwo                `adb reverse tcp:8084 tcp:8084`

adb reverse is for adb and your system connection.

**Comment by mahendramahi** [comment]
This is adb connectivity problem
So use adb reverse command when it come and reload app with all port's number which is using for your host and mini modules.
Like:-
adb reverse tcp:3000 tcp:3000 && adb reverse tcp:8081 tcp:8081 && adb reverse tcp:9000 tcp:9000 && adb reverse tcp:9001 tcp:9001 && adb reverse tcp:9002 tcp:9002 && adb reverse tcp:9003 tcp:9003
