### ISSUE TITLE
Download chunk in background 

### ISSUE THREAD

**Issue by ashutoshd11** [callstack/repack#254]
## Ask your Question

Is there a config by which we can serve the local chunk first and then check the new version of chunks and download it in the background and serve the new chunk in the next app launch

**Comment by jbinda** [comment]
You can try to play with `ScriptManager.shared.prefetchScript`. Please check `TesterApp->remoteChunks->RemoteContainer`

When applying some custom logic to handle loading script next time user opens the app after prefetching it in the background previously, you can achieve described behaviour.

**Comment by RafikiTiki** [comment]
@ashutoshd11 Any luck with what was suggested in the comment above?

**Comment by mlakmal** [comment]
@jbroma sorry to tag you like this on old issue. but i am trying to achieve same thats mentioned in this ticket. we have remote that will be served from cdn. on initial load we are already using local chunk to show the content to avoid waiting on remote download. while we show local chunk we also do prefetch of the remote chunk in background.

i was expecting next restart of the app native script manager will be able to pull remote chunk from prefetched local file system path. but looks like this support is not built-in (i could not figure this is supported from native source-code for re.pack...) or may be iam missing something. can you please confirm is this support built0in at native script manager level or this needs to be something we have to custom build on our side...
