### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [callstack/repack#259]
## Describe the feature

Support new React Native architecture.

## Motivation

So that we can take advantage of React 18 features.

## Related Issues

See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by thymikee** [comment]
@troZee will try to estimate the effort for this and we'll pick that for some R&D work, most likely early next year. Will keep you posted

**Comment by oristian** [comment]
This would be huge for us.  Thanks for the great work.

**Comment by skins-app** [comment]
Bout to submit our app, and was hoping to use re.pack, as we're an existing RNW app that uses webpack already. Waiting on this, let me know if there's anything I can do.

**Comment by faceyspacey** [comment]
Love your work, can't wait for this!

**Comment by ajanuar** [comment]
Any update?

**Comment by tom-sherman** [comment]
@thymikee can we reopen this?

**Comment by jbroma** [comment]
@tom-sherman thanks for noticing, I'll be cleaning up more issues tomorrow which might have been accidentally closed

**Comment by jbroma** [comment]
Support for New Architecture added in https://github.com/callstack/repack/pull/495. Will be released in `4.0.0` soon! Thanks again @troZee for his work on this 🎉
