### ISSUE TITLE
Cannot load local chunks: cannot read property loadScript of undefined

### ISSUE THREAD

**Issue by StanislavSava** [callstack/repack#260]
## Environment
React Native 0.69.5

## Description

Since upgrading to 3.0, the ScriptManager seems to fail to load scripts with the error of "cannot read property loadScript of undefined"

<img width="480" alt="Screenshot 2022-10-04 at 12 40 58" src="https://user-images.githubusercontent.com/14952015/193787838-ff492a73-14c5-4ff9-80b1-9a75f37f5e93.png">

## Reproducible Demo

Here's my scriptManager

```
ScriptManager.shared.setStorage(AsyncStorage);
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  // In dev mode, resolve script location to dev server.
  if (__DEV__) {
    return {
      url: Script.getDevServerURL(scriptId),
      cache: false
    };
  }
  // In production, get chunks matching the regex from filesystem.
  if (/^.+\.remote$/.test(scriptId)) {
    return {
      url: Script.getRemoteURL(`https://my-domain.dev/${scriptId}`)
    };
  } else {
    return {
      url: Script.getFileSystemURL(scriptId)
    };
  }
});
```

And I'm using React.Lazy to import the file

```
const Screen = React.lazy(
  () =>
    import(/* webpackChunkName: "async_body" */ './Screen')
);
```

And this is the extraChunks in webpack config

```
extraChunks: [
          {
            include: /.*/,
            type: 'local'
          },
          {
            // IMPORTANT!
            exclude: /^.+\.remote$/,
            type: 'remote',
            outputPath: path.join('build/output', platform, 'remote') // Default path
          }
        ]
```

**Comment by jbinda** [comment]
Please check and confirm if `ScriptManager` is initialised before lazy import your local chunk.

Please also check if path to local chunk file is correct and if the file is actually there.

**Comment by rakshith** [comment]
> @StanislavSava any luck trying to follow the steps from the comment above?

I tried the above solution to load from local 'getFileSystemURL' but it is unable find the jsbundles there even if in android assets folder all the jsBundles is present
