### ISSUE TITLE
Error in "./App.tsx": Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by sleaper** [callstack/repack#262]
## Question
I successfully set up my React native app v0.69 with Repack v3 and pnpm. I executed all the necessary steps that are here: https://re-pack.netlify.app/docs/getting-started. I can install the app with `npx react-native webpack-bundle` command. Also I have node v16.14.2 and I use this default webpack config template: https://github.com/callstack/repack/blob/main/templates/webpack.config.mjs

But when I start webpack with this command `npx react-native webpack-start` I get this error message:
![image](https://user-images.githubusercontent.com/19505081/194590195-1418d45f-388e-457d-98f7-e499a7d130eb.png)

If you need more information feel free to ask.

**Comment by jbinda** [comment]
hi @sleaper ! Thanks for posting your question.

I assume after initial setup that you've mentioned you still have Metro. Can you try to run the app using metro and see if that will work ?

If yes, you can also try use node 16.15.0.

**Comment by RafikiTiki** [comment]
@sleaper any luck with node 16.15.0?

**Comment by sleaper** [comment]
Could not make it work even with node v.16.15.0. For now I will have to use pnpm without symlinks.
