### ISSUE TITLE
Research how to make `Federated.importModule` type safe

### ISSUE THREAD

**Issue by thymikee** [callstack/repack#270]
## Describe the feature

Add some kind of type safety to the `Federated.importModule` method when importing federated modules.

It could look like this, but I hope there's a more ergonomic way of doing this.

```ts
import {Federated} from '@callstack/repack/client';
import type {GeneratedAvailableModules} from '@/generated-dir';

const Booking = React.lazy(() => Federated.importModule<Exports, GeneratedAvailableModules>('booking', './App')); 
```

The `GeneratedAvailableModules` type could be generated by e.g. a webpack plugin running a script that takes module info from the webpack config and concatenates it into a type file. 

## Motivation

Current signature of the `importModule` method is as follows:

https://github.com/callstack/repack/blob/7348b5628158e11c617e4499095fd108a3740a03/packages/repack/src/modules/ScriptManager/federated.ts#L252-L256

Allowing for declaring exports and assuming the `containerName` and `module` can be anything. Making it possible to unintentionally import a module that's not available.

I haven't done any research regarding how this is solved in web micro frontends, so maybe there's something ready to use out there already.

**Comment by grabbou** [comment]
This would be cool, unless already resolved with MF2. 

CC: @jbroma

**Comment by jbroma** [comment]
@grabbou yep, already solved with MF2, will be available in Re.Pack V5
