### ISSUE TITLE
Obtaining uniqueName always uses package.json name when using Module Federation plugin

### ISSUE THREAD

**Issue by Drakeoon** [callstack/repack#279]
## Environment

The above issue is not impacted by the environment. I'll post the setup requirements below:

- Set up with 2 or more Module Federated apps like below:

### App 1
```ts
// webpack.config.js
  plugins: [
    new Repack.plugins.ModuleFederationPlugin({
        name: 'remoteFeatureOne',
        exposes: {
          './RemoteFeature': './src/remoteFeature.ts',
        },
        shared: { ... }
    })
  ]
```

### App 2
```ts
// webpack.config.js
  plugins: [
    new Repack.plugins.ModuleFederationPlugin({
        name: 'remoteFeatureTwo',
        exposes: {
          './RemoteFeature': './src/remoteFeature.ts',
        },
        shared: { ... }
    })
  ]
```

## Description

When you use 2 or more Module Federated apps that have the same `name` in `package.json` and they have the same module paths, you can experience a strange behavior of wrong bundles being used. The bundle that was first loaded ends up being the one that Re.Pack uses every time, even though they should be unique.

After digging for a while, I found that the issue lies in the `uniqueName` property, that Webpack generates underneath based on `output.library.name` or falls back to `name` from `package.json`.

Webpack docs: https://webpack.js.org/configuration/output/#outputuniquename

A solution to this would be for Webpack to get `output.library.name` config from Module Federated plugin, since the `name` provided in the config should always be unique and would solve the above behavior.

## Reproducible Demo

1. Set up an app with Re.Pack to be the host
2. Set up two different apps that use Module Federation plugin (clients)
3. Configure unique names for these two apps, use the same `name` in `package.json`
4. Configure host app to consume the two client apps
5. Add ability to navigate to the client apps
6. Navigate to the first one, then navigate to the second one
7. The second one will always use the first one's bundle

**Comment by Drakeoon** [comment]
I've already got a possible solution, will push a PR soon

**Comment by deeze307** [comment]
> I've already got a possible solution, will push a PR soon

Sounds good. I hope that your PR can be accepted.
