### ISSUE TITLE
Remote Assets

### ISSUE THREAD

**Issue by jbroma** [callstack/repack#290]
## Motivation
When using Repack with Module Federation the only way to access the assets is to inline them via Repack's `assetLoader`. This solution results in assets being bigger in size by themselves and embedded into the bundle itself resulting in bigger size of it as well.

## Description
Proposed solution is to handle the assets the same way they're handled on the web - by keeping them separate and downloading them in the app only if needed. To achieve that, we would need to emit a directory containing all of the assets that would need to be uploaded to the remote host (e.g. CDN). Another step would be to change the result of RePack's `require` when using remote assets. The goal here is to make it compatible with `ReactNative`'s `Image` component. Similarly to how inlining assets works, the result of the `require` would look something like this:
```ts
const source = {
    uri: url.href,
    width: size?.width,
    height: size?.height,
  };
```
This solution involves encoding asset's dimension during compilation which eliminates the problem where the remote asset won't be displayed by `Image` component without styling the component (similar to inlined assets).

The `URL` inside of source object would be the result of prepending `PUBLIC_PATH` provided via `assetsLoader` configuration to the relative path of the resource. There is an important limitation in here that `PUBLIC_PATH` needs to be known at compile-time, similar to how it's done in Webpack

Here's how the configuration object for `assetsLoader` could like with options for remote assets:
```ts
export interface Options {
  platform: string;
  scalableAssetExtensions: string[];
  devServerEnabled?: boolean;
  inline?: boolean;
  publicPath?: string;
  remote?: {
    enabled: boolean;        // useful for switching between development and production env
    publicPath: string;      // hostname of the target remote location
    outDir?: string;         // name of the resulting directory containing remote assets
    publicOutDir?: string;   // name of the directory appended to the publicPath in case it's different than the outDir
    scalableAssets: 'min' | 'max' | 'default' | 'all'  // what scale to choose for the remote asset
  };
}
```
By proper configuration of the RePack's `assetsLoaders`, the developer could work on the local assets as before, and only use the remote functionality for the production build (after uploading the assets to the remote host).

When dealing with remote assets there's also aspect of asset's scalability. Simple solution to that would be to only choose 1 scale of the asset to emit as remote, and let the user configure the behaviour that governs it, e.g. whether we want to take the smallest one, the biggest or the default one with `@1x` scale. It would be a good idea to leave it as a default solution while also providing an option to disable that behaviour in case someone wants to emit every asset at every scale and handle the scalability themselves (e.g. via query params?). 

## Summary
What needs to be done involves the following:
1. Add asset transformer that will replace the result of RePack's `require` with `Source` object containg the URL
2. Add mechanism to select only one scale from scalable assets
3. Handle outputting the asset's directory
4. Add relevant configuration to `assetsLoader` options

## Relevant PRs
[feat(assetLoader): support remote assets](https://github.com/callstack/repack/pull/217) - this PR aims to deliver similar functionality

**Comment by hosseinmd** [comment]
i changed assets config in webpack to this code 
```
              test: Repack.getAssetExtensionsRegExp(
                 Repack.ASSET_EXTENSIONS.filter((ext) => ext !== "svg")
              ),
              loader: 'file-loader',
              options:{
                postTransformPublicPath:(p)=>(`{uri:${p}}`)
              },
```

this code worked in development, not tested in production.

**Comment by crash7** [comment]
Hey @jbroma, just so this issue today. Do you think we can work together to make this solution a reality? (based on the linked PR I made a while back)

**Comment by rakshith** [comment]
> i changed assets config in webpack to this code
> 
> ```
>               test: Repack.getAssetExtensionsRegExp(
>                  Repack.ASSET_EXTENSIONS.filter((ext) => ext !== "svg")
>               ),
>               loader: 'file-loader',
>               options:{
>                 postTransformPublicPath:(p)=>(`{uri:${p}}`)
>               },
> ```
> 
> this code worked in development, not tested in production.

how we can deploy the ios/android build to production without running the dev server, please provide me one document

**Comment by hosseinmd** [comment]
for production i have changed it

```
 test: Repack.getAssetExtensionsRegExp(
            Repack.ASSET_EXTENSIONS.filter((ext) => ext !== "svg")
          ),

          loader: "file-loader",
          options: {
            publicPath: (url, resourcePath, context) => {
              const dimensions = sizeOf(resourcePath);

              let publicPath = `__webpack_public_path__ + ${JSON.stringify(
                url
              )} `;

              return `{uri:${publicPath},width:${dimensions.width},height:${dimensions.height}}`;
            },
            postTransformPublicPath: (p) => {
              return JSON.parse(p);
            },
          },
```

**Comment by jbroma** [comment]
Hey @crash7 , sorry for not replying earlier. I've done some research on the subject and changed the proposed solution slightly. I've investigated your approach with the `AssetsRegistry` but that didn't yield any satisfactory results. I've managed to get the scales working too, which might be of interest to you. Here's the PR: #331
