### ISSUE TITLE
Kotlin Gradle plugin version error

### ISSUE THREAD

**Issue by malkomich** [callstack/repack#291]
When I tried to run a new project (`react-native run-android`) I got the following:

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':callstack_repack' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10
```

It looks like I needed to add `kotlinVersion = "1.5.20"` in the android `build.gradle`.
That is not mentioned in the _Getting started_ page, so I assume is not an expected behaviour.

I was able to deduce the solution from [this line of code](https://github.com/callstack/repack/blob/0c973366fbbe80da02d5a873aeecbbc4cdbdb54e/packages/repack/android/build.gradle#L3). I discovered that it is taking the version 1.4.10 [here](https://github.com/callstack/repack/blob/0c973366fbbe80da02d5a873aeecbbc4cdbdb54e/packages/repack/android/gradle.properties#L1).

A default compatible version should be set for the plugin, or more information/steps is needed in the Getting started guide.

**Comment by RafikiTiki** [comment]
@malkomich I've merged a fix for this issue, I plan to publish new Repack release tomorrow, cheers!

**Comment by malkomich** [comment]
Nice! Thank you @RafikiTiki 😃
