### ISSUE TITLE
Got a white screen when upgrading react-native to 0.71.1

### ISSUE THREAD

**Issue by decisionnguyen** [callstack/repack#297]
## Environment

node  v18.0.0

```
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "^6.4.1",
    "@react-navigation/native": "^6.0.14",
    "@react-navigation/native-stack": "^6.9.2",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2"
```

## Description

It works fine on 0.70.6 but when I upgrade to 0.71.1 it doesn't work :'( 
Please help me

![image](https://user-images.githubusercontent.com/22584353/215240069-71263a68-5d27-45aa-a96c-718b3cf3dd3d.png)

**Comment by TMisiukiewicz** [comment]
hey @decisionnguyen, [this](https://github.com/callstack/repack/issues/251#issuecomment-1269765918) answer helped me with similar problem

**Comment by piccinnigius** [comment]
same here, the tagged issue doesn't work :/

**Comment by piccinnigius** [comment]
Hey @decisionnguyen, maybe my solution for #299 can helps you too

**Comment by d9j** [comment]
I am certain without upstream vendor support  eg facebook support this project need to have own fork of react native..

**Comment by AkankshaJagdish** [comment]
Having the same issue. Only downgrading React-Native works. Please help me.

**Comment by RafikiTiki** [comment]
Hello @decisionnguyen & @AkankshaJagdish, please try the latest version of repack (3.1.1) – the issue with DevTools should be fixed there. 

PR with a fix: https://github.com/callstack/repack/pull/302

Closing this issue. if you have problems, please open a new one.
