### ISSUE TITLE
What are the main drawbacks of Re.Pack for Super Apps (each team will handle their own piece of the Super App)?

### ISSUE THREAD

**Issue by jfbaro** [callstack/repack#303]

**Comment by thymikee** [comment]
We're working on preparing some quality resources regarding super apps around April. Stay tuned!

**Comment by jfbaro** [comment]
Can we (commercially) have a partnership where you folks use our use case as an example on how this can be done? I have sent one email to Krzysztof Pawlak (following up on an OLD discussion that I started with Marcelina in 2021).

**Comment by thymikee** [comment]
I pinged Krzysztof internally, so he can schedule us something. Let's talk :)

**Comment by jfbaro** [comment]
Thanks, looking forward to it!
