### ISSUE TITLE
How much do I need to refactor my existing React Native application to work with Re.Pack?

### ISSUE THREAD

**Issue by jfbaro** [callstack/repack#305]
Hi there,

Re.pack looks spectacular. Thanks to all the community!!

We have an existing React Native application that covers a single Business Unit (Investment Product). This uses React Native.

Now we want to move the architecture to Re.Pack for these reasons:

- Have many teams working on their products, that then is composed into a single super app to the customer.
- Each team has should be as autonomous as possible. 
- The end APP size (iOS and Android) should not be super large (like, lots of bloat added if not strictly necessary). Reuse of common libraries between the "Modules" (AKA "Products/BU")
- Allow us to incrementaly turn the current React Native app (single Product) into a container/shell prepared to have other teams working in new PRODUCTS, that at the end of the day will compose the NEW SUPER APP.
- Allow OTA update (like Code Push or Expo Updates), so for minor changes the teams don't need to wait for the weekly full deploy on the app stores.
- NICE TO HAVE: Teams could use Expo SDK 47 OR React Native... depending on what they feel more comfortable with
- The shell should have a dedicated team, the maintains the Shell/Container Architecture.in a way the minimize the conflict between modeules.
- Shared libraries that should be used by all Modules/Products... Like Analytics, Log, Authentication, Design System Components, Crashlytics, Off Line Database, etc.

Any help would be appreciated.

Thanks

**Comment by jfbaro** [comment]
Any tip?

**Comment by tranductanz** [comment]
Not much, but re.pack have some kind of rules example some library cannot use with re.pack, you must find and change another same lib, config some native place to compatible with repack. And you need to create where to store CDN to get remote Chunk to load modules. After a while to config with re.pack, our project doing very well.
