### ISSUE TITLE
Simple starter example of `Re.Pack` working with `Expo`

### ISSUE THREAD

**Issue by iambharath87** [callstack/repack#312]
## Ask your Question

I was trying to set up a simple expo app that could use `Re.Pack` for bundling. But i'm getting stuck on step 4 while following these [instructions](https://re-pack.netlify.app/docs/getting-started). Any help is appreciated.

Here is what i see on xcode while trying to perform step 4 of the instructions:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/6663930/222241725-230451aa-3132-4b3f-b66c-e061613287c5.png">

Here is my [repo](https://github.com/iambharath87/expo-repack-starter) for reproducing the error i get when i start the app on ios simulator:

![image](https://user-images.githubusercontent.com/6663930/222241190-0211e0e0-0ffd-4629-91ea-197852830be4.png)

**Comment by RafikiTiki** [comment]
[As stated in the Repack docs](https://re-pack.netlify.app/docs/getting-started#note-on-expo): currently `expo` is not officially supported and enabling this compatibility will require experimenting.

Any help here would be appreciated, so if you want to spend some time investigating this topic please feel free to do so 🚀
