### ISSUE TITLE
Unable to road url from custom server path

### ISSUE THREAD

**Issue by rakshith** [callstack/repack#314]
## Cannot able to load from custom server path, for example, 

Reproducible gitpath, https://github.com/rakshith/rn-micro-frontend-boilerplate.git

http://localhost:8083/build/outputs/ios/remotes/<scriptId>

1. Execute the command, yarn bundle:ios, it creates the path /build/outputs/ios/remotes
gives the below error,

<img width="975" alt="Screenshot 2023-03-12 at 8 47 03 PM" src="https://user-images.githubusercontent.com/926932/224554192-30bf0731-b61d-438e-8d6c-201389b3fb2c.png">

**Comment by RafikiTiki** [comment]
It looks like a problem with the project's configuration – try opening an issue in the original repo you forked or ask the author of that boilerplate for help.
