### ISSUE TITLE
Property "ScriptManger" and "Script" doesn't exist

### ISSUE THREAD

**Issue by Kumar8228** [callstack/repack#315]
Hi all. 
I am trying to create a Repack project but i am constantly getting the below error. 

In the console :
Reference error : Property "ScriptManager" doesn't exist 

![IMG_20230313_183025](https://user-images.githubusercontent.com/127760875/224727740-1501a59d-c94b-4ae6-b39a-0a5f5041c4b3.jpg)

OS: Windows 
Commands: run android & webpack-start

package versions:
react native : 0.70.6
callstack/repack: 3.1.1

If anyone know the solution, kindly share. It would be helpful.

**Comment by RafikiTiki** [comment]
Please add a reproduction repository, otherwise there's not much that I can do to help.

**Comment by piccinnigius** [comment]
@Kumar8228  to fix this ScriptManager not found error, try to add  `/node_modules(.*[/\\])+@callstack/,` in babel loader section of webpack config

**Comment by RafikiTiki** [comment]
@piccinnigius That is already a part of the recommended webpack template here: https://github.com/callstack/repack/blob/main/templates/webpack.config.mjs#L161


@Kumar8228 Any progress on the reproduction repo? Without it I don't have enough context to help you.

**Comment by vishnusaiunplatforms** [comment]
I am also getting the same issue, is there a solution to this?

**Comment by sis3141** [comment]
In my case, I was struggling with resolving class imports ( ex importing axios)
so i added babel-plugin-transform-class-properties and solved that issue

But even with the plugin, I got same issue for Scriptmanager
If you didn't have issue for other library's class resolve, just fixing regex for babel rule will help you
It might be path seperator for window is not included in your regex for repack module

in your webpack config, change `/node_modules(.*[/\\])+@callstack\/repack/`
to ` /node_modules(.*[/\\])+@callstack(.*[/\\])+repack/`
