### ISSUE TITLE
Bundle Analyzer

### ISSUE THREAD

**Issue by adityaputra11** [callstack/repack#319]
## Ask your Question

Can you please confirm if Re.Pack provides a built-in bundle analyzer or any other visualization tools to compare its generated bundles with those created using Metro bundler?

**Comment by RafikiTiki** [comment]
There's no built-in bundle analyzer, but since repack is using webpack under the hood, you can access all of the webpack plugins. 

The one that I've been using to analyze bundles is Statoscope: https://github.com/statoscope/statoscope

**Comment by arleyGuoLei** [comment]
mark
