### ISSUE TITLE
How to share react navigation with federated module?

### ISSUE THREAD

**Issue by sschottler** [callstack/repack#325]
It would be helpful to see an example in repack-examples where a federated module uses `@react-navigation` libraries. We are hoping to export a ["nested" navigator](https://reactnavigation.org/docs/nesting-navigators/) from federated modules representing sub features of the host app. So the federated module feature would be responsible for its own internal routing and host app would be agnostic of those screen names and internal navigation structure. I have gotten this working locally, but for some reason it only works when debugging is turned off. If I turn it on, the federated module exported navigator never renders in the host app suspense boundary even when ios bundling message for federated module dev server hits 100%. I don't see any helpful warning or error messages. Shared config for host and federated module is below. Am I doing this correctly? Any idea why it only works when debugging is turned off in simulator dev menu? 

https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

### host webpack shared config: 

```js
'react-native-safe-area-context': {
  eager: true,
  singleton: true,
  requiredVersion: '4.2.4',
},
'@react-navigation/native': {
  eager: true,
  singleton: true,
  requiredVersion: '6.1.4',
},
'@react-navigation/native-stack': {
  eager: true,
  singleton: true,
},
'react-native-screens': {
  eager: true,
  singleton: true,
},
```

### federated module webpack config:

```js
"@react-navigation/native": {
  eager: false,
  singleton: true,
  requiredVersion: "6.1.4",
},
"@react-navigation/native-stack": {
  eager: false,
  singleton: true,
},
"react-native-safe-area-context": {
  eager: false,
  singleton: true,
},
"react-native-screens": {
  eager: false,
  singleton: true,
},
```

**Comment by RafikiTiki** [comment]
Could you share a minimal reproduction repository with a list of steps to follow to see the behavior you described?

**Comment by sschottler** [comment]
Yeah, I'll attempt to fork the repack-examples module-federation app and set it up there when I have time and see if I can replicate it there or if it's something specific to the host app I am using.

**Comment by jbroma** [comment]
@sschottler did you manage to resolve your issues?

**Comment by RafikiTiki** [comment]
@sschottler I believe our Super App Showcase repo – https://github.com/callstack/super-app-showcase has a similar structure (mini-apps owning their navigation logic). Please check if it'll help you with your issue.
