### ISSUE TITLE
Fast refresh not working in  ModuleFederation repack 3.0.1

### ISSUE THREAD

**Issue by emel95** [callstack/repack#334]
hi guys
I have been stuck with fastRefresh for a few days and it doesn't work in  repack with reactnative . 
webpack Version:

  "@callstack/repack": "^3.0.1",
 "webpack": "^5.75.0",
  "react": "18.2.0",
 "react-native": "0.71.2",

I searched a lot and did what you said on the net, I did these things ,
   "resolutions": {
        "@pmmmwh/react-refresh-webpack-plugin": "0.5.7",
        "react-refresh": "0.14.0"
    },
and in webpack.config.js:
 output: {
      clean: false,
}
 
but It still doesn't work for me
Thank you for helping me.

**Comment by sschottler** [comment]
I ran into this from copying the default webpack config template and it ended up being a super simple fix - need to set `hmr` to true here:

https://github.com/callstack/repack-examples/blob/6f45b5cd81dfd06d86fda752ea04cc53021b89b7/module-federation/host/webpack.config.mjs#L51

**Comment by emel95** [comment]
Thanks, it works ok in repack, but it doesn't work for ModuleFederation

**Comment by sschottler** [comment]
Yeah, I ran into that as well. I think that is expected. The host app won't automatically refresh when a federated module container changes. This comment is from the creator of module federation:

https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/394#issuecomment-914928351

You could try the plugin he mentions:

https://www.npmjs.com/package/@module-federation/fmr

**Comment by emel95** [comment]
My problem was not solved with this plugin because it is for the web. I want a plugin for fast refresh that works for ModuleFederation in the app

**Comment by RafikiTiki** [comment]
Hi @emel95, Fast Refresh won't work for in the Host App for Federated Modules as was stated in the comment linked by @sschottler. Currently, we don't have any reaserch planned in this regard, but feel free to experiment with it yourself and please come back if you find anything.

**Comment by hosseinmd** [comment]
It is because multi entries not working in federation mode
