### ISSUE TITLE
React Native Debugger/Devtools not working 

### ISSUE THREAD

**Issue by vschan-digiX** [callstack/repack#336]
## Environment
`@callstack/repack": "^3.1.1`
`react-native": "0.71.6`
node: v18.11.0
yarn: 1.22.19

## Description
Debugger/Devtools not working with standalone 

<img width="733" alt="Screenshot 2023-04-11 at 10 09 46 AM" src="https://user-images.githubusercontent.com/97014737/231037206-bde21471-608b-4f42-8ec2-ce296a095f56.png">

or with flipper

<img width="1552" alt="Screenshot 2023-04-11 at 10 11 55 AM" src="https://user-images.githubusercontent.com/97014737/231037485-b5d15b15-515d-400a-b8f9-d3dac28b6356.png">

## Reproducible Demo

1. Init a new react native project :  `npx react-native init test_app`
2. Configure Repack according to https://re-pack.netlify.app/docs/getting-started#dependencies, using updated webpack config template under v3: https://github.com/callstack/repack/blob/v3/templates/webpack.config.mjs.
3. Run repack `react-native webpack-start`
4. Open simulator menu (cmd+d) and click 'Open Debugger' / 'Open React Devtools'

**Comment by steventnorris** [comment]
@vschan-digiX Did you ever solve this issue? I'm running into the same issue with flipper not having the hermes debugger listed as an available plugin.
