### ISSUE TITLE
how to share component between host and remote ? 

### ISSUE THREAD

**Issue by vschan-digiX** [callstack/repack#352]
Hi, I want to import components from the host app how am I supposed to do that?

**Comment by jbroma** [comment]
Hi @vschan-digiX 

If I understand you correctly, you want to **expose** a component in the host and then import it in another app. 

Please refer to [this](https://github.com/callstack/repack/issues/359) section of the docs which explains how to do that.

**Comment by jbroma** [comment]
Hi @vschan-digiX 

If I understand you correctly, you want to **expose** a component in the host and then import it in another app. 

Please refer to [this](https://re-pack.netlify.app/docs/module-federation#host-application-cant-use-remotes) section of the docs which explains how to do that.
