### ISSUE TITLE
React context in module module federation

### ISSUE THREAD

**Issue by jc578271** [callstack/repack#355]
## Ask your Question

I created a react context in my NPM package (this package is installed in both apps). And this Context.Provider is wrapped at host app. 

Is it imposible to use useContext without wrapping the provider in remote app?

**Comment by thymikee** [comment]
As in any React app, you need declare Context.Provider for the component tree you're calling `useContext`. It's perfectly fine to have `<Context.Provider>` in your host app so that remote apps could subscribe to it.
