### ISSUE TITLE
How to add axios to repack app?

### ISSUE THREAD

**Issue by bea73693** [callstack/repack#359]
## Ask your Question

Environment:
```
"react-native": "0.70.6",
"react": "18.1.0",
"@callstack/repack": "^3.2.0",
"axios": "^1.4.0",
"@tanstack/react-query": "^4.29.7",
```

What changes need to be done to add `axios` to a repack app?

`@tanstack/react-query` and `axios` were recently added to our react-native + web application. These packages were added without needing any changes to our web webpack config and work as expected. 

However a number of errors were showing on native platforms. We've made the following changes to the template webpack.config.js:

```diff
resolve: {
  ...Repack.getResolveOptions(platform),
+  fallback: {
+    url: require.resolve('url/'),
+    http: require.resolve('stream-http'),
+    https: require.resolve('https-browserify'),
+    stream: require.resolve('stream-browserify'),
+    assert: require.resolve('assert/'),
+    zlib: require.resolve('browserify-zlib')
+  }
},
```

```diff
rules: [
  {
    // added .cjs to test
    test: /\.(js|jsx|ts|tsx|cjs)$/, 
    include: [
      /node_modules(.*[/\\])+react/,
      /node_modules(.*[/\\])+@react-native/,
      /node_modules(.*[/\\])+@react-navigation/,
      /node_modules(.*[/\\])+@react-native-community/,
      /node_modules(.*[/\\])+@expo/,
      /node_modules(.*[/\\])+pretty-format/,
      /node_modules(.*[/\\])+metro/,
      /node_modules(.*[/\\])+abort-controller/,
      /node_modules(.*[/\\])+@callstack\/repack/,
+      /node_modules(.*[/\\])+@tanstack\/query-core/,
+      /node_modules(.*[/\\])+axios/
    ],
    use: 'babel-loader'
  },
```

These changes got past a number of errors but we've hit a wall when trying to call the axios create method:

```
import axios from 'axios'

const client = axios.create({ ... })
```
 "Cannot read property 'prototype' of undefined". Only shown on the device, nothing is logged to the console.

![Screen Shot 2023-05-19 at 9 34 23 AM](https://github.com/callstack/repack/assets/56211155/75f89627-ddba-4caf-be4c-09360f25d481)
 

Any help is appreciated.

**Comment by jbroma** [comment]
Hi @bea73693, there shouldn't be any problems from the Re.Pack side with adding a JS-only lib.

If the problem you've encountered still blocks you, please create a minimal reproduction repo so we can investigate this.

**Comment by jbroma** [comment]
Hi @bea73693

I've investigated the issue and I've found that that the easiest way to get the `axios` working with Re.Pack is to add alias in `resolve` options in `webpack.config.js`:

```js
resolve: {
  ...Repack.getResolveOptions(platform),
  alias: {
    axios: path.join(dirname, 'node_modules/axios/dist/axios.js'),
  },
  // ...
},
```

Steps 5. and 6. from your repro can be omitted when setup this way. As this problem doesn't occur when using metro, we will investigate this topic further to improve compatibility in the future. Please let me know whether this solution is sufficient for you.

**Comment by bea73693** [comment]
Hmm I have added this alias and removed steps 5 and 6, however with the app.tsx listed above, the create() method is undefined. 

<img width="383" alt="Screen Shot 2023-05-22 at 1 22 46 PM" src="https://github.com/callstack/repack/assets/56211155/d6d91a3f-7e41-450c-aeb1-b9085385629a">

Calling `axios.createInstance()` shows the same error.

**Comment by jbroma** [comment]
Please try again with `react-native webpack-start --resetCache`

**Comment by bea73693** [comment]
I appreciate your prompt responses. Unfortunately, with `react-native webpack-start --resetCache` still showing the same error: `TypeError: Cannot read property 'create' of undefined, js engine: hermes`. 

Also tried regenerating node_modules, still no luck.

**Comment by jbroma** [comment]
Hi @bea73693 

I've investigated the problem more throughly and found a solution that should help with any other packages that are ESM modules. I've compared how `metro` solves this and replicated it here for Re.Pack. 

In `webpack.config.js` add the following:

1. Add `conditionNames` key to `resolve` options
```ts
resolve: {
     // ...
      ...Repack.getResolveOptions(platform),
      conditionNames: ['default'],
     // ...
},
```
This will ensure that when resolving modules, we don't look for `require` in `exports` field in library `package.json`. This is the same way as metro does it, and we plan to include that option in `Repack.getResolveOptions(platform)` in the future. For now just add it as shown above.

2. Add **new** transform rules to `module.rules` that will help with ESM libs
```ts
{
  test: /\.[jt]sx?$/,
  include: [
    /node_modules(.*[/\\])+axios\//,
  ],
  use: {
    loader: "babel-loader",
    options: {
      presets: [
        [
          "module:metro-react-native-babel-preset",
          { disableImportExportTransform: true },
        ],
      ],
    },
  },
}
```
By disabling the `ImportExportTransform` we leave it to `webpack` to substitute those with `__webpack__require__` and ensure the module loads correctly. If we don't disable that, `webpack` will complain that since this is an ESM module, we shouldn't have any `require` calls in there.

Please try these steps in a clean setup and see if that helps you with the problem at hand.

**Comment by bea73693** [comment]
This fix is working, your help is greatly appreciated 😄.  Closing this issue

**Comment by chakravarthi-bb** [comment]
If anyone drops by here, use RedAxios from developit https://github.com/developit/redaxios

It has the same API of axios and works with react-native as it doesn't contain any code of node.js

**Comment by metuuu** [comment]
> Hmm I have added this alias and removed steps 5 and 6, however with the app.tsx listed above, the create() method is undefined.
> 
> <img alt="Screen Shot 2023-05-22 at 1 22 46 PM" width="383" src="https://user-images.githubusercontent.com/56211155/240001477-d6d91a3f-7e41-450c-aeb1-b9085385629a.png">
> Calling `axios.createInstance()` shows the same error.

I got axios working by using path `node_modules/axios/dist/esm/axios.js` instead of `node_modules/axios/dist/axios.js`

So only configuration I needed to get axios working was to configuring this to `webpack.config.js`:
```js
resolve: {
  ...Repack.getResolveOptions(platform),
  alias: {
    axios: path.join(dirname, 'node_modules/axios/dist/esm/axios.js'),
  },
  // ...
},
```

**Comment by HongQuang231** [comment]
@jbroma i follow your step but i use file .mjs and I still error look like this, can you help me???

![image](https://github.com/callstack/repack/assets/92237330/55441ab2-fc09-4fe8-bc7b-7f22bd1a8565)

![image](https://github.com/callstack/repack/assets/92237330/6678e71f-36d0-413a-bc68-b7b7eeaf0fb0)


![image](https://github.com/callstack/repack/assets/92237330/73b842ac-d07b-4d27-929f-0b377e518b50)

**Comment by zky847798418** [comment]
> @jbroma i follow your step but i use file .mjs and I still error look like this, can you help me???
> 
> ![image](https://private-user-images.githubusercontent.com/92237330/342048628-55441ab2-fc09-4fe8-bc7b-7f22bd1a8565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjk2NzQsIm5iZiI6MTcyMDQyOTM3NCwicGF0aCI6Ii85MjIzNzMzMC8zNDIwNDg2MjgtNTU0NDFhYjItZmMwOS00ZmU4LWJjN2ItN2YyMmJkMWE4NTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNjAyMDc3YTM3NDI2ZWFmZTdmMmMxZTU0NzE4YjUzNDJmZGRiNTMxYmY0NmJhNzZlNTNhODkxOGQ1MDk3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzY1MfOwcdVVpQkP989sGzNOaUVQwVZQWeWWyO01soo)
> 
> ![image](https://private-user-images.githubusercontent.com/92237330/342048639-6678e71f-36d0-413a-bc68-b7b7eeaf0fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjk2NzQsIm5iZiI6MTcyMDQyOTM3NCwicGF0aCI6Ii85MjIzNzMzMC8zNDIwNDg2MzktNjY3OGU3MWYtMzZkMC00MTNhLWJjNjgtYjdiN2VlYWYwZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OGRhOThkNjc1ZDkyNDU0ODNhZjdjNzY1N2JlMjlkZTIzMWFlODA3NDI2MDI4MDk2OGY0MmQ5ODU3MmEzM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CPyKcl_yYOJ-GRMk-etdv5-KVpz-in6ZelHXXHFZBfA)
> 
> ![image](https://private-user-images.githubusercontent.com/92237330/342048608-73b842ac-d07b-4d27-929f-0b377e518b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjk2NzQsIm5iZiI6MTcyMDQyOTM3NCwicGF0aCI6Ii85MjIzNzMzMC8zNDIwNDg2MDgtNzNiODQyYWMtZDA3Yi00ZDI3LTkyOWYtMGIzNzdlNTE4YjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4OWZjN2IwYzhjNjIxNjBlN2NiMTQxNjA4M2I3ODdiYzIyNDM0YWMzODIyMzVhNTFjMzA5NWE4ZjdlMmUzZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ShPwcIsGkkC6YKQqftfv541DF50YHhp9esr46he-YaY)

this is ok?

**Comment by zky847798418** [comment]
if create undefined，need use global.axios

**Comment by linhh-phv** [comment]
in my case, I have downgraded to version 0.27.2

**Comment by snehaJain8** [comment]
I am still facing this error. Any update on this ?

**Comment by eeuruetade** [comment]
> Si alguien se deja caer por aquí, use RedAxios de developit https://github.com/developit/redaxios
> 
> Tiene la misma API de axios y funciona con react-native ya que no contiene ningún código de node.js

I have problems with axios but this package works for me, I remain attentive to the solutions given for axios, thank you

**Comment by eeuruetade** [comment]
@jbroma  Apply the different solutions proposed, but with none of them it is possible to make axios work, I share a repo to replicate the case, I appreciate any help.

https://github.com/eeuruetade/TestAxiosRePack

<img width="332" alt="image" src="https://github.com/user-attachments/assets/3b84c1e4-ffd2-4df1-8799-ac0c9b5d831e">

<img width="319" alt="image" src="https://github.com/user-attachments/assets/5c7b5233-a2fb-4812-a245-033d9fc4cd68">
