### ISSUE TITLE
I want to use progress instead of showing the bundle percentagein a separate line

### ISSUE THREAD

**Issue by emel95** [callstack/repack#369]
I want to use progress instead of showing the bundle percentage in a separate line. The problem is that I can't find this number that I can use in progress.
<img width="745" alt="Screenshot 1402-03-08 at 11 01 02" src="https://github.com/callstack/repack/assets/81304095/f8df9911-42bd-4aa2-93f3-a9be5e4c1563">

**Comment by emel95** [comment]
Thank you for following @ RafikiTiki and @szymonrybczak 
I used cli-progress and I suggest you to use this

**Comment by RafikiTiki** [comment]
@szymonrybczak ⬆️

**Comment by szymonrybczak** [comment]
Hello @emel95, sure! Please create PR with your changes. It doesn't make sense to do the same job twice :)

**Comment by emel95** [comment]
@ szymonrybczak  
I've just submitted a pull request, and I'm eagerly waiting for it to be merged
