### ISSUE TITLE
Repack Federated loading forever when caching is enabled

### ISSUE THREAD

**Issue by decisionnguyen** [callstack/repack#374]
## Environment

```
"@callstack/repack": "^3.2.0",
"react": "18.2.0",
"react-native": "0.71.8",

```

## Description
Hi all,
I have problem it's always loading when I enabled caching mode.
And when debug I see all mini apps have the same chunk name: src_Routes_tsx.script.bundle

In the first time:
Open app -> open app 1 (fine) -> back to main-> open app 2 (fine)-> back to main ->  open app 3 (fine)
In the second time:
Open app ->  open app 3 -> work fine -> back to main-> open app 2 -> loading forever 
In the third:
Open app ->  open app 1 ->  loading forever 

I think it's only cache data of last Federated in the first time

![image](https://github.com/callstack/repack/assets/22584353/29454a0b-9863-43cd-8754-eba1d503f60a)
![Simulator Screenshot - iPhone 14 - 2023-06-03 at 14 44 27](https://github.com/callstack/repack/assets/22584353/1375dee3-1558-4324-ac1f-cad78257da12)

It's work fine if I remove this line 
`ScriptManager.shared.setStorage(AsyncStorage);`
Someone help me please

**Comment by RafikiTiki** [comment]
Hello @decisionnguyen could you please create a reproduction repository, with the same setup, and all of the mini apps just rendering a <Text /> component? It would be much quicker for me to debug this issue. Thanks!

**Comment by RafikiTiki** [comment]
Additional question: is it happening in the dev mode or in prod? I see that you have custom containers definition – if the issue is happening in the prod env, please let me know how is the server with the bundles set up, or even better – add it to the reproduction repository.

**Comment by RafikiTiki** [comment]
And two more questions:
1. Could you elaborate on why you pass `scriptId` and `callerId` as query params?
2. Why did you set the `absolute` flag to `true? It's only used for the local chunks (filesystem chunks): https://github.com/callstack/repack/blob/main/packages/repack/android/src/main/java/com/callstack/repack/FileSystemChunkLoader.kt#L11-L13

**Comment by decisionnguyen** [comment]
> Additional question: is it happening in the dev mode or in prod? I see that you have custom containers definition – if the issue is happening in the prod env, please let me know how is the server with the bundles set up, or even better – add it to the reproduction repository.

Thank you @RafikiTiki 
It's is in product mode
When I see in the cached folders: /Users/username/Library/Developer/CoreSimulator/Devices/AD83372B-33CF-4A9A-95A9-0FF365C1F698/data/Containers/Data/Application/3CAE7CFD-F6C0-4C02-9F65-AEB57E503AD4/Library/com.main.app/scripts
All apps with the same chunk when caching is enabled 
![image](https://github.com/callstack/repack/assets/22584353/2a1f482c-6ce4-47f6-85ec-ad5ffcee2445)
With each app in build folder it's the same chunk name 
![image](https://github.com/callstack/repack/assets/22584353/56a31864-864c-4ca8-b2e1-748075cef26e)

And I think it's error when you saved file it's just save file name 
`/Users/pudinh/Desktop/super-app/basefi/node_modules/@callstack/repack/android/src/main/java/com/callstack/repack/FileSystemChunkLoader.kt`

**Comment by decisionnguyen** [comment]
> And two more questions:
> 
> 1. Could you elaborate on why you pass `scriptId` and `callerId` as query params?
> 2. Why did you set the `absolute` flag to `true? It's only used for the local chunks (filesystem chunks): https://github.com/callstack/repack/blob/main/packages/repack/android/src/main/java/com/callstack/repack/FileSystemChunkLoader.kt#L11-L13

Ah I just add some props to test

**Comment by hafiz-azman-cd** [comment]
Hi @decisionnguyen did you manage to fix this? I'm currently facing the same issue too
