### ISSUE TITLE
HMR doesn't work on remote mini-apps

### ISSUE THREAD

**Issue by Kaveh-ap** [callstack/repack#376]
## Hot Module Replacement doesn't work on my project, I was wondering if you could help!

Hey everyone, thank you for all the hard work you've been putting in. 

I've been working with Repack for a while to grasp the topic well and use it on my bigger projects. Therefore, I  started developing a CLI and did some of the stuff before you provided a super app showcase of Repack. 

However, I've faced several issues along the way, and I was wondering if you could look at my repo and help me out : )

My repository: [TemplateSuperApp](https://github.com/Kaveh-ap/TemplateSuperApp)

Unfortunately, HMR doesn't work on my remote mini-apps. I have a remote and a local mini app and utilize the host(which I call it client) as a package to separate the native part of the app from mini apps.

**Comment by RafikiTiki** [comment]
What is the exact problem with HMR? Are you trying to make it work for the host app (client) or the remote mini apps embedded in the host app?

**Comment by Kaveh-ap** [comment]
Thanks for your response @RafikiTiki.
Well, I'd like to have this feature on remote mini-apps. It sometimes works with a delay of around 10s because of the changes I've made, but most of my attempts have ended up with failure. I was wondering if is it plausible to achieve the mentioned feature on remote mini-apps, and if it is feasible, what changes are required from my side to overcome this issue.
Thanks in advance.

**Comment by RafikiTiki** [comment]
Hey @Kaveh-ap – in the case of the remote mini-apps (Federate Modules) – it's currently impossible to have hmr working. It's a known limitation of the Module Federation itself. More context can be found here, in the comment posted by the author of the Module Federation in webpack himself: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/394#issuecomment-914928351.

What I suggest you do during the development: Work on the mini-apps in separation from the Host app (it will probably be the default workflow when you have many teams in the projects, all working on different features, anyway). When you are done developing a given feature, integrate it with the Host App.

**Comment by ra1nj** [comment]
Hey @RafikiTiki , according to this [comment](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/394#issuecomment-2381631552), it seems HRM is supported in module federation v2 , is it possible we can use it in repack ?

**Comment by jbroma** [comment]
@ra1nj yes, this is possible in Re.Pack 5 and MF2, we also have our showcase upgraded to latest RC version of repack where you can check it out:

https://github.com/callstack/super-app-showcase
