### ISSUE TITLE
Webpack support for exports field in package.json

### ISSUE THREAD

**Issue by chakrihacker** [callstack/repack#385]
I am adding axios and react-native-svg to my codebase and now repack is not able to compile the bundle

https://github.com/chakrihacker/repack-bug

**Comment by jbroma** [comment]
Hi @chakrihacker,

so apparently the order in `conditionNames` doesn't matter, we'll have to manually point to `axios` to resolve this issue.

In your `webpack.config.js` please modify `resolve` options and add the following:
```js
resolve: {
      /**
       * `getResolveOptions` returns additional resolution configuration for React Native.
       * If it's removed, you won't be able to use `<file>.<platform>.<ext>` (eg: `file.ios.js`)
       * convention and some 3rd-party libraries that specify `react-native` field
       * in their `package.json` might not work correctly.
       */
      ...Repack.getResolveOptions(platform),
      /**
       * Uncomment this to ensure all `react-native*` imports will resolve to the same React Native
       * dependency. You might need it when using workspaces/monorepos or unconventional project
       * structure. For simple/typical project you won't need it.
       */
      alias: {
        axios: new URL('./node_modules/axios/index.js', import.meta.url)
          .pathname,
      },
    },
```

**Comment by chakrihacker** [comment]
@jbroma This hack is fine, I am not sure if I move to mono repo in future this will work (I am planning to migrate my app to super app). can we fix this at repack library level?? I can deep dive into the library, if you can give some pointers??

**Comment by jbroma** [comment]
I'm not sure this is something we can fix easily as module resolution algorithm for `metro` and `Webpack` are different. Ideally we would want to maintain parity with metro when it comes to modules compatibility.

If you would like to contribute to this issue, you can check few things:
- metro recently released support for `conditionNames`, you can check how their final implementation looks like and how it differs from what Webpack uses (look up `webpack/enhanced-resolve`)
- it might be a long shot but you could check if it would be possible to replace `webpack/enhanced-resolve` with `metro-resolver`
