### ISSUE TITLE
Share logic between mini apps

### ISSUE THREAD

**Issue by lehuyaa** [callstack/repack#399]
## Ask your Question
I'm not sure if this has been resolved, if so please give me the link.
Currently I am having a problem while developing, in 1 mini app need to use some logic of other mini app and if I run in 1 mini app there won't be the code of other mini app that I need.
For example mini app profile will need to have auth functionality from mini app login and if I just run the mini app profile there will be no logic of mini app auth
And as I read it is not possible to use hot reload mini app in host app because this is a limitation. So has anyone had this problem while developing.

**Comment by RafikiTiki** [comment]
Your use case can be found among others in the Super App Showcase repository we created at Callstack: https://github.com/callstack/super-app-showcase.

While HMR is not working in Module Federation architecture, there's a way to efficiently develop one mini-app separately from all other pieces of the bigger (Super) app codebase. That's how it probably would look in a larger organization with many independent teams working on their parts of the app/features in separation. 

> Each of the mini-apps could be deployed and run as a standalone app.

If any changes are needed in the Auth miniapp – run it in a Standalone mode and develop the required changes – you'll have the full HMR and a nice dev experience. Only after the changes are implemented – use the update Auth miniapp code in another App.

**Comment by lehuyaa** [comment]
@RafikiTiki thank for your answer
