### ISSUE TITLE
Assets loader in federation not working

### ISSUE THREAD

**Issue by hosseinmd** [callstack/repack#403]
## Environment

This issue started from https://github.com/callstack/repack/issues/290
## Description

Assets loader doesn't work in federation mode

**Comment by jbroma** [comment]
@hosseinmd 

please provide a reproduction repository, otherwise I won't be able to help you. Assets loader works correctly in our TesterApp

**Comment by hosseinmd** [comment]
Ok, I will try to do that. But consider it, your TesterApp is not federation.
On the other hand, when I change it to inline assets, it is working.

**Comment by hosseinmd** [comment]
When I change it to inline assets, it is working in federation.

**Comment by jbroma** [comment]
@hosseinmd 

Normal assets won't work out of the box with federation - you have to either inline them as you did, or use [remote assets](https://re-pack.netlify.app/docs/configuration/guides/remote-assets)

**Comment by hosseinmd** [comment]
Yes, but there is a problem with publicPath, to support federation we need to get path dynamically in code not from config. I get it from `__webpack_public_path__` .

**Comment by jbroma** [comment]
In case of dynamic public path that indeed might be a problem. I think it might be possible to implement something like that in the future and initialise it before remotes load.

It might also be feasible to create a gateway server that the publicPath will point to and based on the asset need, it will forward the request to the CDN which has that resource.

**Comment by jbroma** [comment]
I'll close this issue for now as unfortunately we don't plan to implement that functionality anytime soon.

**Comment by hosseinmd** [comment]
To handle this, I made an asset-loader, like repack assets-loader, but it can handle dynamic URL and get it from `assetLoader` similar `scriptLoader`. Also, can handle scale and platform.
If you are interested, I can work on it to add it repack.

**Comment by jbroma** [comment]
> To handle this, I made an asset-loader, like repack assets-loader, but it can handle dynamic URL and get it from `assetResolver` similar `scriptResolver`. Also, can handle scale and platform. If you are interested, I can work on it for adding it to repack.

I would love to see what its all about, can you open a new issue with feature proposal where we can discuss this? 🙏
