### ISSUE TITLE
RN GoogleSignin native module is not correctly linked. Please read the readme, setup and troubleshooting instructions carefully or try manual linking.

### ISSUE THREAD

**Issue by tranvuluan** [callstack/repack#404]
Miniapp I use firebase and use @react-native-google-signin/google-signin for google signin. When run standalone mini app work well. But when I include to Shell app. I have occur RN GoogleSignin native module is not correctly linked. Please read the readme, setup and troubleshooting instructions carefully or try manual linking.

![image](https://github.com/callstack/repack/assets/63645119/77ceeb2b-ac96-47a8-9720-f29c631b4477)

My webpack.config.mjs in Mini App:
import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';
import * as Repack from '@callstack/repack';

const STANDALONE = Boolean(process.env.STANDALONE);

/**
 * More documentation, installation, usage, motivation and differences with Metro is available at:
 * https://github.com/callstack/repack/blob/main/README.md
 *
 * The API documentation for the functions and plugins used in this file is available at:
 * https://re-pack.netlify.app/
 */

/**
 * Webpack configuration.
 * You can also export a static object or a function returning a Promise.
 *
 * @param env Environment options passed from either Webpack CLI or React Native CLI
 *            when running with `react-native start/bundle`.
 */
export default env => {
  const {
    mode = 'development',
    context = Repack.getDirname(import.meta.url),
    entry = './index.js',
    platform = process.env.PLATFORM,
    minimize = mode === 'production',
    devServer = undefined,
    bundleFilename = undefined,
    sourceMapFilename = undefined,
    assetsPath = undefined,
    reactNativePath = new URL('./node_modules/react-native', import.meta.url)
      .pathname,
  } = env;
  const dirname = Repack.getDirname(import.meta.url);

  if (!platform) {
    throw new Error('Missing platform');
  }

  /**
   * Using Module Federation might require disabling hmr.
   * Uncomment below to set `devServer.hmr` to `false`.
   *
   * Keep in mind that `devServer` object is not available
   * when running `webpack-bundle` command. Be sure
   * to check its value to avoid accessing undefined value,
   * otherwise an error might occur.
   */
  // if (devServer) {
  //   devServer.hmr = false;
  // }

  /**
   * Depending on your Babel configuration you might want to keep it.
   * If you don't use `env` in your Babel config, you can remove it.
   *
   * Keep in mind that if you remove it you should set `BABEL_ENV` or `NODE_ENV`
   * to `development` or `production`. Otherwise your production code might be compiled with
   * in development mode by Babel.
   */
  process.env.BABEL_ENV = mode;

  return {
    mode,
    /**
     * This should be always `false`, since the Source Map configuration is done
     * by `SourceMapDevToolPlugin`.
     */
    devtool: false,
    context,
    /**
     * `getInitializationEntries` will return necessary entries with setup and initialization code.
     * If you don't want to use Hot Module Replacement, set `hmr` option to `false`. By default,
     * HMR will be enabled in development mode.
     */
    entry: [
      ...Repack.getInitializationEntries(reactNativePath, {
        hmr: devServer && devServer.hmr,
      }),
      entry,
    ],
    resolve: {
      /**
       * `getResolveOptions` returns additional resolution configuration for React Native.
       * If it's removed, you won't be able to use `<file>.<platform>.<ext>` (eg: `file.ios.js`)
       * convention and some 3rd-party libraries that specify `react-native` field
       * in their `package.json` might not work correctly.
       */
      ...Repack.getResolveOptions(platform),

      /**
       * Uncomment this to ensure all `react-native*` imports will resolve to the same React Native
       * dependency. You might need it when using workspaces/monorepos or unconventional project
       * structure. For simple/typical project you won't need it.
       */
      // alias: {
      //   'react-native': reactNativePath,
      // },
    },
    /**
     * Configures output.
     * It's recommended to leave it as it is unless you know what you're doing.
     * By default Webpack will emit files into the directory specified under `path`. In order for the
     * React Native app use them when bundling the `.ipa`/`.apk`, they need to be copied over with
     * `Repack.OutputPlugin`, which is configured by default inside `Repack.RepackPlugin`.
     */
    output: {
      clean: true,
      path: path.join(dirname, 'build/generated', platform),
      filename: 'index.bundle',
      chunkFilename: '[name].chunk.bundle',
      publicPath: Repack.getPublicPath({platform, devServer}),
    },
    /**
     * Configures optimization of the built bundle.
     */
    optimization: {
      /** Enables minification based on values passed from React Native CLI or from fallback. */
      minimize,
      /** Configure minimizer to process the bundle. */
      minimizer: [
        new TerserPlugin({
          test: /\.(js)?bundle(\?.*)?$/i,
          /**
           * Prevents emitting text file with comments, licenses etc.
           * If you want to gather in-file licenses, feel free to remove this line or configure it
           * differently.
           */
          extractComments: false,
          terserOptions: {
            format: {
              comments: false,
            },
          },
        }),
      ],
      chunkIds: 'named',
    },
    module: {
      /**
       * This rule will process all React Native related dependencies with Babel.
       * If you have a 3rd-party dependency that you need to transpile, you can add it to the
       * `include` list.
       *
       * You can also enable persistent caching with `cacheDirectory` - please refer to:
       * https://github.com/babel/babel-loader#options
       */
      rules: [
        {
          test: /\.[jt]sx?$/,
          include: [
            /node_modules(.*[/\\])+react/,
            /node_modules(.*[/\\])+@react-native/,
            /node_modules(.*[/\\])+@react-navigation/,
            /node_modules(.*[/\\])+@react-native-community/,
            /node_modules(.*[/\\])+react-freeze/, // <---- this line here
            /node_modules(.*[/\\])+@expo/,
            /node_modules(.*[/\\])+pretty-format/,
            /node_modules(.*[/\\])+metro/,
            /node_modules(.*[/\\])+abort-controller/,
            /node_modules(.*[/\\])+@callstack\/repack/,
            /node_modules(.*[/\\])+@callstack\/repack/,
            /node_modules(.*[/\\])+@react-native-firebase\/auth/,
            /node_modules(.*[/\\])+@react-native-firebase\/app/,
            /node_modules(.*[/\\])+@react-native-google-signin\/google-signin/,
            /node_modules(.*[/\\])+@callstack\/repack/,
          ],
          use: 'babel-loader',
        },
        /**
         * Here you can adjust loader that will process your files.
         *
         * You can also enable persistent caching with `cacheDirectory` - please refer to:
         * https://github.com/babel/babel-loader#options
         */
        {
          test: /\.[jt]sx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              /** Add React Refresh transform only when HMR is enabled. */
              plugins:
                devServer && devServer.hmr
                  ? ['module:react-refresh/babel']
                  : undefined,
            },
          },
        },
        /**
         * This loader handles all static assets (images, video, audio and others), so that you can
         * use (reference) them inside your application.
         *
         * If you wan to handle specific asset type manually, filter out the extension
         * from `ASSET_EXTENSIONS`, for example:
         * ```
         * Repack.ASSET_EXTENSIONS.filter((ext) => ext !== 'svg')
         * ```
         */
        {
          test: Repack.getAssetExtensionsRegExp(Repack.ASSET_EXTENSIONS),
          use: {
            loader: '@callstack/repack/assets-loader',
            options: {
              platform,
              devServerEnabled: Boolean(devServer),
              /**
               * Defines which assets are scalable - which assets can have
               * scale suffixes: `@1x`, `@2x` and so on.
               * By default all images are scalable.
               */
              scalableAssetExtensions: Repack.SCALABLE_ASSETS,
            },
          },
        },
      ],
    },
    plugins: [
      /**
       * Configure other required and additional plugins to make the bundle
       * work in React Native and provide good development experience with
       * sensible defaults.
       *
       * `Repack.RepackPlugin` provides some degree of customization, but if you
       * need more control, you can replace `Repack.RepackPlugin` with plugins
       * from `Repack.plugins`.
       */
      new Repack.RepackPlugin({
        context,
        mode,
        platform,
        devServer,
        output: {
          bundleFilename,
          sourceMapFilename,
          assetsPath,
        },
      }),
      new Repack.plugins.ModuleFederationPlugin({
        name: 'ocr',
        exposes: {
          './App': './SignInScreen.tsx',
        },
        shared: {
          react: {
            ...Repack.Federated.SHARED_REACT,
            requiredVersion: '18.2.0',
            eager: STANDALONE,
          },
          'react-native': {
            ...Repack.Federated.SHARED_REACT_NATIVE,
            requiredVersion: '0.71.8',
            eager: STANDALONE,
          },
          '@react-navigation/native': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.0.13',
          },
          '@react-navigation/native-stack': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.9.1',
          },
          '@react-navigation/material-bottom-tabs': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.2.4',
          },
          'react-native-image-picker': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '5.6.0',
          },
          'react-native-image-crop-picker': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '0.40.0',
          },
          '@react-native-firebase/auth': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '18.3.0',
          },
          '@react-native-firebase/app': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '18.3.0',
          },
          '@react-native-google-signin/google-signin': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '10.0.1',
          },
        },
      }),
      
    ],
  };
};

**Comment by jbroma** [comment]
Hi @tranvuluan,

Did you add the `@react-native-google-signin/google-signin` to your Host app as well? If it links properly in the MiniApp then it should link properly in the Host app as well. 

If your problem persists, please create a reproduction repository with your setup so we can help you diagnose this issue better.

**Comment by tranvuluan** [comment]
@jbroma thanks for response, I created 2 repository shell app and miniapp remote.
Shell app: https://github.com/tranvuluan/supper-app-demo.git
Miniapp: https://github.com/tranvuluan/AwesomeProject.git

Shell app: I cloned from supper-app-show-case and I include my miniapp 'ocr' key name
Miniapp: I'm expose signing screen

**Comment by jbroma** [comment]
Hi @tranvuluan,

I see you've added `firebase` & `google-signin` to the babel transpiled libraries in the `webpack.config` of the `shell` app but forgot to add them as explicit dependencies to the `shell app`. The error (RN GoogleSignin native module is not correctly linked) occurs because there is no native code available for that library in the `shell` app.

As both of those libraries have native code in them you will need to add them as dependencies to the `shell` app to make it work.

You also have to add them to `shared` dependencies in your `ModuleFederation` setup in `webpack.config` - in this case, you need to add them to the list inside of `shared/dependencies.mjs`.

Let me know whether you were able to resolve your issue.

**Comment by tranvuluan** [comment]
@jbroma thanks you, It worked

**Comment by Luca-Tamburo** [comment]
I have the same error after running npx expo start --web. How can I solve it?

This is my metro.config.js
```js
const {getDefaultConfig} = require("metro-config");

module.exports = (async () => {
    const {
        resolver: {sourceExts, assetExts},
    } = await getDefaultConfig();
    return {
        transformer: {
            babelTransformerPath: require.resolve("react-native-svg-transformer"),
        },
        resolver: {
            assetExts: assetExts.filter((ext) => ext !== "svg"),
            sourceExts: [...sourceExts, "svg", "mjs", "cjs"],
        },
    };
})();
```

**Comment by Hiba-Bazerbashi** [comment]
I've similar issue  with Expo sdk 50   . I'm using react-native-firebase along with

**error** on web 

>  Uncaught Error: RN GoogleSignin native module is not correctly linked. Please read the readme, setup and troubleshooting instructions carefully.
>  If you are using Expo, make sure you are using Custom dev client, not Expo go

**app.json:**
`....
"ios": {
      "config": {
        "usesNonExemptEncryption": false
      },
      "supportsTablet": true,
      "bundleIdentifier": "bundleIdentifier",
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "googleServicesFile": "./google-services.json",
      "package": "my package"
    },
    "web": {
      "bundler": "metro",
      "favicon": "./src/assets/favicon.png"
    },
    "experiments": {
      "tsconfigPaths": true
    },
    "extra": {
      "eas": {
        "projectId": "projectId"
      }
    },
    "plugins": [
      "@react-native-firebase/app",
      "expo-font",
      **"@react-native-google-signin/google-signin"**
    ],
    "owner": "owner"`

**package.json :**
`dependencies:{
"@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/auth": "^17.4.2",
    "@react-native-google-signin/google-signin": "^11.0.0",
    "@reduxjs/toolkit": "^1.9.7",
    "expo": "^50.0.0-preview.10",
    "expo-auth-session": "~5.4.0",
    "expo-crypto": "~12.8.0",
    "expo-dev-client": "~3.3.5",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.1",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.49.2",
    "react-native": "^0.73.2",}`
 */

steps to achieve it 
1_ Expo manged workflow 
2_ development build   eas build --profile development --platform android 
3_ npx expo install @react-native-google-signin/google-signin
4_ expo doctor Didn't find any issues with the project
5_ npx expo prebuild --clean  

on android emulator stuck in splash screen with no issues 'Android Bundling complete'
on web give the error above 

RN google sign docs in you have to be sponsor to get it work on web 
but github docs says if you're not sponsor follow readme instructions   but nothing differ form the docs 
is being sponsor required ??? or what the solution

**Comment by RafikiTiki** [comment]
@Luca-Tamburo @Hiba-Bazerbashi are you using repack to build your apps?

**Comment by Hiba-Bazerbashi** [comment]
@Luca-Tamburo . I'm not really , but I'll be so delighted if you could help me  to get this issue sorted ,thanks in advance

**Comment by Hiba-Bazerbashi** [comment]
@Luca-Tamburo  did you figure it out ,I've similar issue ??

**Comment by tranvuluan** [comment]
> @Luca-Tamburo did you figure it out ,I've similar issue ??

hi @Hiba-Bazerbashi , sorry for lately, did you resolve it? 
I don't remember how to fix it because I just investigated supper, it seems like I installed @react-native-google-signin/google-signin for both the host app and the micro app. I don't know why I need to install the  @react-native-google-signin/google-signin package in host app because my goal for this architecture is only to install package in micro app and don't install any package that isn't used by host app

**Comment by Hiba-Bazerbashi** [comment]
@tranvuluan yes ,i did it was just related to firebase setup for web platform 
`import {Platform} from 'react-native';
import { initializeApp, } from "firebase/app";

import { getStorage } from 'firebase/storage';
import Constants from "expo-constants";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { getFirestore, enableIndexedDbPersistence } from "firebase/firestore";

// @ts-ignore 
import{initializeAuth, GoogleAuthProvider , inMemoryPersistence,
  getReactNativePersistence,setPersistence,}from 'firebase/auth';

import firebase from "firebase/compat/app"
import 'firebase/compat/auth';
import 'firebase/compat/firestore';
import 'firebase/compat/functions';



let app: firebase.app.App;

 firebase.apps.length === 0 ?
 app = firebase.initializeApp(firebaseConfig)
:  app = firebase.app();
//export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
const persistence = 
Platform.OS === 'web'                                                        //this line
            ?inMemoryPersistence as any                                 //this line
            :getReactNativePersistence(AsyncStorage);            //this line
export const auth = initializeAuth(app, { persistence });
//export const auth = getAuth();
export const provider = new GoogleAuthProvider();
export const database = getFirestore();
const storage = getStorage(app);
export {app}`

**Comment by jbroma** [comment]
> > @Luca-Tamburo did you figure it out ,I've similar issue ??
> 
> hi @Hiba-Bazerbashi , sorry for lately, did you resolve it? I don't remember how to fix it because I just investigated supper, it seems like I installed @react-native-google-signin/google-signin for both the host app and the micro app. I don't know why I need to install the @react-native-google-signin/google-signin package in host app because my goal for this architecture is only to install package in micro app and don't install any package that isn't used by host app

You need to add it to the host app because `@react-native-google-signin/google-signin` contains native parts, and every piece of native code needs to come from the host app. Do avoid conflicts further down the line, make sure to declare `@react-native-google-signin/google-signin` as a shared dependency in Module Federation configuration in both host and mini-apps - mark them as `singleton` and make it `eager: true` in host app and `eager: false` in mini-app for the super app setup.

**Comment by tranvuluan** [comment]
@jbroma , thanks for your response, I usually work on the backend, and I only research the callstack, this is the interesting architecture, your example repo is actually good (super-app-showcase) but mostly it refers to UI components , I hope your team can create more example repos that have lot interacts packages between host app and mini-app.
