### ISSUE TITLE
Using webpack-bundle to report an error

### ISSUE THREAD

**Issue by Liuminke1996** [callstack/repack#407]
## When I use webpack-bundle, it prompts an error, the error is as follows
<img width="1253" alt="image" src="https://github.com/callstack/repack/assets/19630237/36a57d7f-8653-4cab-8d53-bcdbbd97e7ea">

## But try to start react-native to run
<img width="1245" alt="image" src="https://github.com/callstack/repack/assets/19630237/72edca2f-3709-40e9-b1cc-7e0948f4ba67">
I need help, I don't know how to configure webpack to build successfully

**Comment by jbroma** [comment]
Hi @Liuminke1996,

the description you've provided is not enough for me to diagnose this issue, could you please create a reproduction repository where this error happens? Thanks!
