### ISSUE TITLE
How and where to find example of repack config for webpack.SourceMapDevToolPlugin

### ISSUE THREAD

**Issue by slav-getov** [callstack/repack#410]
Hello,
I am trying to use web pack's SourceMapDevToolPlugin and noticed this reply. Where can I find examples and what exactly is meant by 'only provides config for ...'? Thank you for any advice.

              > I don't really understand the subtleties between the way repack rebuilds bundles for HMR and just normal bundle rebuilds when you make changes and reload.

 Re.Pack doesn't really do anything regarding the source map creation. Re.Pack only provides config for these 2 plugins `webpack.SourceMapDevToolPlugin` and that's it.

The errors you're getting in the console makes me think that the source maps might be broken on incomplete.

I have couple of question:
1. Do you have this issue with HMR enabled or disabled?
2. _load times_ mean the time to build source maps or the time to symbolicate the stack trace from error? I'm not sure which _load_ you're referring to.
3. Do you think you could create some repro project for it? 

_Originally posted by @zamotany in https://github.com/callstack/repack/issues/64#issuecomment-895854317_

**Comment by jbroma** [comment]
Hi @slav-getov,

I'm afraid we don't have any examples with custom `SourceMapDevToolPlugin `. Could you explain in more detail what you are trying to achieve? 

Regarding your question: `RepackPlugin` by default uses `SourceMapDevToolPlugin` to enable source maps in the project. The plugin is preconfigured inside of `RepackPlugin`. You can always explode the `RepackPlugin` into individual components by checking it's implementation inside `packages/repack/src/webpack/plugins/RepackPlugin.ts` and importing these plugins manually in your project.

**Comment by slav-getov** [comment]
Hello and thank you very much for the speedy reply!

I am trying to generate and then read source maps of errors(if that makes sense?). I saw that if there is a symbolicated error, using source maps we can get to the root issue and not read these obtuse errors. 

![Screenshot 2023-07-31 at 14 16 13](https://github.com/callstack/repack/assets/124028924/da92f79d-56fe-4dc9-98fe-cdd326907bce)


I also read this part of the webpack.config.js and this is why I asked the question above. 
![Screenshot 2023-08-03 at 9 12 59](https://github.com/callstack/repack/assets/124028924/baa3d884-f329-4b5c-b93f-f1e4230327cb)
