### ISSUE TITLE
How to handle typescript when using remotes ?

### ISSUE THREAD

**Issue by antoniovuono** [callstack/repack#411]
Hey guys, 

I created a component in my core repository and I want to export it to another isolated repository with remotes.

When I import, it works normally. But I can't access the types
![Captura de Tela 2023-08-03 às 10 03 09](https://github.com/callstack/repack/assets/7297243/dd19de28-7de0-4d4d-8042-f8ee6923bd3d)

How it is recommended to work with typescript with re.pack ?

**Comment by RafikiTiki** [comment]
This is unfortunately expected – TypeScript type definitions have to be known at the compile time, whereas Federated Modules are, in their nature, runtime dependencies. This is not Repack-related – the same set of problems exists in every Module Federation application, regardless of the environment/platform.

There are, however, a few ways to tackle this issue. If you want to learn more, here are some links:
- a webpack plugin enabling Typescript Types support for Module Federated Components: https://github.com/module-federation/universe/tree/main/packages/typescript
- a very nice write-up  on all possible solutions with their pros and cons: https://spin.atomicobject.com/2022/07/19/typescript-federated-modules/
