### ISSUE TITLE
[State Management] How can i integrate Redux with Module Federation? 

### ISSUE THREAD

**Issue by huytd2510** [callstack/repack#412]
I am trying to create a store in the "StateManager" module. And I want to share an instance of a provider for other modules in MyApp. How can I do it? I have researched, but I still need to figure out how to resolve it. (If anyone has an example, please share it with me. I'm so grateful for that) Many thanks.

**Comment by leonardoballand** [comment]
did you see [https://github.com/callstack/super-app-showcase/blob/main/packages/auth](https://github.com/callstack/super-app-showcase/blob/main/packages/auth example)?

**Comment by huytd2510** [comment]
@leonardoballand yep. But I need to use redux. I have an idea, and it works. 
1. Create custom provider -> expose 
2. Using code-splitting of redux https://redux.js.org/usage/code-splitting. To add new reducers in other modules
So, in other modules, it can be used.
