### ISSUE TITLE
URL not working in `npx @callstack/repack-init`

### ISSUE THREAD

**Issue by kunalphaltankar** [callstack/repack#413]
## Description

I saw the URL in manual setup is different than the URL in auto setup by npx @callstack/repack-init

**Comment by kunalphaltankar** [comment]
I saw the URL in manual setup is different than the URL in auto setup by `npx @callstack/repack-init`

**Comment by jbroma** [comment]
Hi @kunalphaltankar,

I believe you meant the URL's for `webpack.config` templates, I've just checked and they seem to be working correctly for me, could you provide me with more details for this issue? Thanks!

If `repack-init` is not working you, try forcing it to use the latest possible version like this:
```sh
npx @callstack/repack-init@latest
```
