### ISSUE TITLE
Is "realm" usable with Repack

### ISSUE THREAD

**Issue by decisionnguyen** [callstack/repack#416]
## Ask your Question
Hi everyone,

I have problem when using realm package 
It's work well when "react-native start" and got error when run "react-native webpack-start"

<img width="529" alt="image" src="https://github.com/callstack/repack/assets/22584353/6ccc6117-8d5c-472b-a7ab-f5bee4c012a6">
<img width="1221" alt="image" src="https://github.com/callstack/repack/assets/22584353/49a5a6eb-713f-49b9-80f7-ca0f818100d4">

After I added this is config, it's got new error
![image](https://github.com/callstack/repack/assets/22584353/bc56f257-6410-497c-bd76-593a2d0e1c3b)

<img width="1180" alt="image" src="https://github.com/callstack/repack/assets/22584353/bd008307-1c77-4fed-af49-5e63274faa3c">

<img width="508" alt="image" src="https://github.com/callstack/repack/assets/22584353/3480204b-47ae-467f-9058-8b9cdfec89a2">

Anyone can help me? Please

**Comment by decisionnguyen** [comment]
Thank @jbroma so much.
I tried but got an error, project is very simple
Please help me on this demo project: https://github.com/decisionnguyen/demo


![Screenshot 2023-09-05 at 08 34 35](https://github.com/callstack/repack/assets/22584353/fb6c110e-00b9-4b82-bfef-8f666f8a25ef)
![Simulator Screenshot - iPhone 14 - 2023-09-05 at 08 34 38](https://github.com/callstack/repack/assets/22584353/bd06029e-19fb-4c12-bd21-ce4085a1286e)
![Screenshot 2023-09-05 at 08 40 29](https://github.com/callstack/repack/assets/22584353/8254cae0-0f59-492e-a983-4f70a73dd1f4)

**Comment by dagouzhi** [comment]
@decisionnguyen 
`realm$: new URL('./node_modules/realm/index.react-native.js', import.meta.url)
          .pathname,`

**Comment by decisionnguyen** [comment]
You are super hero <3 <3 <3 @dagouzhi
