### ISSUE TITLE
refeching chunk after invalidating cache

### ISSUE THREAD

**Issue by jerrynim-zigbang** [callstack/repack#418]
Hi
I'm trying to clear the cache and refetch a chunk. I expect that after calling [Script.shared.invalidateScript
](https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#invalidatescripts), the chunk will be downloaded again. However, after calling invalidateScript, the cache is cleared, and cacheInitialized is set to true, but refetching has not occurred. How can I clear the storage or download the chunk again with the same URL? Here is my code.

```

const resolveURL = Federated.createURLResolver({
	containers: {
		app1: __DEV__
			? "http://localhost:9001/[name][ext]"
			: `https:/{MY_CLOUDFRONT_URL}/app1/${Platform.OS}/[name][ext]`,
		app2: __DEV__
			? "http://localhost:9002/[name][ext]"
			: `https://{MY_CLOUDFRONT_URL}/app2/${Platform.OS}/[name][ext]`,
	},
})

ScriptManager.shared.addResolver(async (scriptId, caller) => {
	const url = resolveURL(scriptId, caller)

	return {
		url,
		cache: false,
		query: {
			platform: Platform.OS,
		},
	}
})


          const App1 = React.lazy(() => Federated.importModule("app1", "./App"))
          const App2 = React.lazy(() => Federated.importModule("app2", "./App"))

			<Button
				title={"clear app1 cache"}
				onPress={() => {
					ScriptManager.shared.invalidateScripts(Object.keys(ScriptManager.shared.cache))
				}}
			/>
```

**Comment by JoonDong2** [comment]
ScriptManager.shared.invalidateScripts must contain the script IDs, not the cache key.
