### ISSUE TITLE
 ERROR  ReferenceError: Property '__webpack_require__' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by gandhamsaicharan** [callstack/repack#424]
After following all the steps in the following link "https://www.callstack.com/blog/step-by-step-guide-to-super-app-development"
im getting this error __webpack_require__ doesnt exist.
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 14 50 01](https://github.com/callstack/repack/assets/145093513/edf96d75-b2dd-417c-b3e2-556fb98ae66e)
how to resolve this

**Comment by jbroma** [comment]
Hi @gandhamsaicharan,

Errors like this indicate that there is something wrong with your setup, can you share a reproduction repository so we can investigate this? Thanks!

**Comment by gandhamsaicharan** [comment]
hi im using the superApp-example given by call stack "https://github.com/callstack/super-app-example"

**Comment by jbroma** [comment]
what steps did you follow and how far how you gotten with the article? afaik `main` and `finished` branches are working properly atm.

**Comment by gandhamsaicharan** [comment]
I have cloned  the sample repo and checkout to finished branch, did yarn install and then yarn android in host-app. build is successful but while loading the app getting this error.
![Simulator Screenshot - iPhone 14 Pro - 2023-09-20 at 14 50 01](https://github.com/callstack/repack/assets/145093513/441f13e4-cfb3-47b4-b557-4959131c149f)

**Comment by gandhamsaicharan** [comment]
this worked for android but first we have to generate index.android.bundle, other wise it is giving metro error

![Screenshot_1695657304](https://github.com/callstack/repack/assets/145093513/769c3afd-77f3-4194-87fb-9912d7a290c5)
