### ISSUE TITLE
ScriptManager failed to load

### ISSUE THREAD

**Issue by gandhamsaicharan** [callstack/repack#429]
After resolving __webpack_require__ issue i was able to run the app but when i click on Navigate to MiniApp button on home screen getting error  ScriptManager failed to load 
![Screenshot_1695707603](https://github.com/callstack/repack/assets/145093513/82f32041-58b8-43fc-9f67-4235b93c33a7)

**Comment by jbroma** [comment]
Please make sure the dev-server for the mini-app is running and then run `adb reverse tcp:9000 tcp:9000`

**Comment by gandhamsaicharan** [comment]
I have started the server using yarn start in root folder, then started mini-app using yarn android and then used "adb reverse tcp:9000 tcp:9000" . Then i tried building host app using yarn android in host-app folder. still getting error related to webpack require
![Screenshot_1695721601](https://github.com/callstack/repack/assets/145093513/6489449c-24c6-45ed-b9a1-86ff76ee2f1d)

**Comment by jbroma** [comment]
I'm not able to reproduce that error, it looks to me like a networking issues. Just to clear it all up please do the following again:

```sh
yarn start
yarn run:host-app:android

# before navigating to the mini-app screen
adb reverse tcp:9000 tcp:9000
# adb reverse should return with 9000 printed to the stdout
```

Please make sure that you can visit access the dev-server by opening Chrome **on the emulator** and going to both of these addresses and veryfing that you get `React Native packager is running` page there
- localhost:8081
- localhost:9000

**Comment by gandhamsaicharan** [comment]
After running "yarn run:host-app:android" im getting 
![Screenshot_1695721567](https://github.com/callstack/repack/assets/145093513/01d3a41b-b083-4b48-b3b9-19878aa92337)


if click on reload in emulator it is giving 

![Screenshot_1695727963](https://github.com/callstack/repack/assets/145093513/89216513-54bb-4bc0-aceb-1bf3a7d67dc1)

also i have checked both servers 8081 and 9000 by opening chrome on the emulator
8081: react-native packager is running
9000: this site cant be reached

**Comment by jbroma** [comment]
make sure there is nothing else running on your PC on port 9000. If you can't access the dev server through chrome there is no way the emulator will access it from within the app. Are you on Windows or Mac?

**Comment by gandhamsaicharan** [comment]
mac

**Comment by jbroma** [comment]
This looks like a networking issue and I'm not able to reproduce this issue in my environment, therefore I'm not able to assist you with this any further. Let me know if you manage to get past it and what helped to resolve this issue.
