### ISSUE TITLE
Property '__webpack_require__' doesn't exist.

### ISSUE THREAD

**Issue by vandnaPatidar** [callstack/repack#432]
There is an issue with miniApp , coz when we are trying to open miniApp inside the hostApp then it's showing  an error of Property '__webpack_require__' doesn't exist, in case of expo .Here is the video of entire execution https://drive.google.com/file/d/1VRspRpykV74nuH8myjc-0R7Is4OetMjN/view?usp=drivesdk

And when we run the hostApp on android emulator  the it's showing an error ""HostApp" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes"

**Comment by jbroma** [comment]
Hi @vandnaPatidar,

Expo uses metro underneath, and atm there is no way to switch to Re.Pack. If you wish to use Re.Pack you will have to resort to classic `react-native-cli` way of using `react-native`.

**Comment by jbroma** [comment]
you need to run `react-native webpack-start` instead of `react-native start` in order to run Re.Pack/webpack

**Comment by vandnaPatidar** [comment]
@jbroma 
I'm doing the following steps for running my project
step1:- Inside \super-app-example i'm running "yarn start" Then it's starting my both app's server on post
[mini-app] i [09:23:57.922Z][DevServer] Server listening at http://127.0.0.1:9000
[host-app] i [09:23:57.975Z][DevServer] Server listening at http://127.0.0.1:8081

Step2:- inside \hostApp i'm running "yarn run:host-app:android" Then i'm getting this error

![MicrosoftTeams-image (3)](https://github.com/callstack/repack/assets/145319757/c68bfdc6-262e-430d-8b9b-9d7c3e7448c9)

**Comment by jbroma** [comment]
try running `adb reverse tcp:8081 tcp:8081`

**Comment by vandnaPatidar** [comment]
in my cmd i'm getting this after running hostapp
![image](https://github.com/callstack/repack/assets/145319757/a669fe07-0201-4735-970b-41043d372b3d)

**Comment by vandnaPatidar** [comment]
> try running `adb reverse tcp:8081 tcp:8081`

can you please let me know , exactly where i need to run this command , in super-app-example or in hostapp?
because in both the case i'm getting error of "adb.exe: error: no devices/emulators found" 
![Uploading image.png…]()

**Comment by vandnaPatidar** [comment]
when i'm starting the server for hostapp then it's starting on  http://127.0.0.1:8081
and after that when i was starting the hostapp then it's starting on http://10.0.2.2:8081 

![image](https://github.com/callstack/repack/assets/145319757/b535614e-3fc4-4908-937e-f5431f420783)

**Comment by RafikiTiki** [comment]
Looks like you're using Windows as the OS. I recently got my hands on a Windows machine so I should soon be able to investigate a few issues that Repack is affected by on Windows machines.

I'll let you know once I make any progress.

**Comment by vandnaPatidar** [comment]
@RafikiTiki Thanks for your response!

**Comment by jbroma** [comment]
Hey @vandnaPatidar,

we've recently released [Re.Pack 3.5.0](https://github.com/callstack/repack/releases/tag/%40callstack%2Frepack%403.5.0) which address a major issue for users on Windows. Try updating `@callstack/repack` to the newest version and see whether your issue is still relevant, thanks!

**Comment by puneetsharma1991** [comment]
@jbroma any update on this issue. I am also facing the same issue. 
Can't find variable: __webpack_require__ when I load the app.
I have update the repack version to 3.5.0 but still facing same issue. I am using windows.


Please guide me.


Thanks
Puneet

**Comment by jbroma** [comment]
hey @puneetsharma1991,

are you sure you are running `react-native webpack-start` instead of `react-native start`? That usually solves this kind of issue :)

**Comment by jbroma** [comment]
I'm not sure what `react-native-webpack` is, but it seems like an old package, unrelated to `Re.Pack` and might be messing with your setup. Did you create your apps via `@callstack/repack-init` ? Are you on Windows? 

If you want to get this issue solved quickly, please create a reproduction repository, thanks!

**Comment by puneetsharma1991** [comment]
https://github.com/puneetsharma1991/SuperAppMiniAppDemo

this is my project and try to resolve my issue. 


Thanks in advance

**Comment by puneetsharma1991** [comment]
@jbroma any update on this?

**Comment by heradonbenin** [comment]
hello.. having the same issue , but in other case. for host deployment , we would like to know the way to change the url localhost:8081 with the remote url...  or if they have any other way to do it... in our understanding we should deploy all the mini-app and the host app, then build the ios package/android apk for store.  during the development , when we lunch emulator, the host url is called first, and a lazy load of mini app occur according to the setting up in Stack.Navigator.

<img width="688" alt="image" src="https://github.com/callstack/repack/assets/12575935/55d3d85c-d795-4b2e-b9e8-8596e94ba34c">
