### ISSUE TITLE
Error in "undefined": Module not found: Error: Can't resolve 'react-native-svg' in

### ISSUE THREAD

**Issue by vlack-coder** [callstack/repack#434]
## Ask your Question
Good day, So I'm new to webpack and repack... I have been able to run the examples in the repo but I am trying to convert my current app  to use webpack and benefit from the power of module federation but most of the packages that I installed in the project are not getting resolved and I have to test my app using just local and remote chunk before implementing module federation.

In the examples in the repo, I added other packages, reanimated worked unlike in my main project, react-native-gesture-handler, react-native-svg, etc. did not work .... Please can you assist me on this. Thank you

<img width="824" alt="image" src="https://github.com/callstack/repack/assets/56041655/c38d56f8-4d3f-4833-96a5-bd3bdafac3ad">
<img width="824" alt="image" src="https://github.com/callstack/repack/assets/56041655/07ced103-67c1-4f9a-acf6-7509c7405b95">
<img width="835" alt="image" src="https://github.com/callstack/repack/assets/56041655/14d5c576-b47a-45d6-b54b-7d2d3b213aa5">

**Comment by vlack-coder** [comment]
@jbroma please your thought on this.
Thank you

**Comment by jbroma** [comment]
Hi @vlack-coder,

please share your `webpack.config` and also describe your setup in more detail so I can help you, thanks!

**Comment by vlack-coder** [comment]
@jbroma  thanks for your response. My webpack config is the same as the one in the docs asides that I tried to add this to the config hoping the packages would get resolved
`    /node_modules(.*[/\\])+react-native-fast-image/,
            /node_modules(.*[/\\])+react-native-gesture-handler/,
            /node_modules(.*[/\\])+react-native-crypto/,
            /node_modules(.*[/\\])+react-native-reanimated/,
            /node_modules(.*[/\\])+react-native-safe-area-context/,
            /node_modules(.*[/\\])+react-native-svg/,`

This is the link to the repo - https://github.com/vlack-coder/repacktest

I only added you to this repo cuz the repo is quite confidential. Thanks again

**Comment by vlack-coder** [comment]
@jbroma  Please can you check this public repo - https://github.com/vlack-coder/repack_test

It's a fresh react-native installation with added dependencies and a little configuration. 
After following the getting started section on the docs, I got this error message when I ran react-native webpack-start 
<img width="710" alt="image" src="https://github.com/callstack/repack/assets/56041655/5f3ca85d-8482-4bfd-9bed-1411232ff610">

Please can I know where the error is coming from, I can fix from my end... Thanks

**Comment by vlack-coder** [comment]
I have gotten it to work alas.... I add to install the libraries in a fresh react native project one after the other and resolve the error accordingly. I resolved it from checking other issues and answers in the repo.
The only library I couldn't get to resolve is the Zod library but it's all fine. Thank you
