### ISSUE TITLE
Got a component with the name "" for screen "" warning when load MiniApp from CDN server

### ISSUE THREAD

**Issue by Ibnunds** [callstack/repack#436]
## Ask your Question

I got this error when loading MiniApp from CDN server, its because the react-native-paper

![simulator_screenshot_5F8495D3-F9A0-4CD8-9FE5-76E8F904E1C5](https://github.com/callstack/repack/assets/146713357/5dddf419-dcb1-429f-bdbe-c29178f0be4e)

I used react-native-paper for Host and MiniApp using version 4.x.x

<img width="381" alt="Jepretan Layar 2023-10-03 pukul 16 51 36" src="https://github.com/callstack/repack/assets/146713357/fb0148e5-5241-4462-b181-d9ffb16196ef">

This is my shared dependencies ( same for host app and mini app )

<img width="569" alt="Jepretan Layar 2023-10-03 pukul 16 52 20" src="https://github.com/callstack/repack/assets/146713357/2582c912-b14a-4239-8ac5-95b34cf0a2bf">

this is my rules

<img width="491" alt="Jepretan Layar 2023-10-03 pukul 16 52 53" src="https://github.com/callstack/repack/assets/146713357/84122322-f09c-46da-85af-0576ea07ffda">

this is my babel.config.js

warning is only shown up on bundled MiniApp, its normal when running using npm start locally

**Comment by jbroma** [comment]
Hey @Ibnunds,

This warning popups up when you try to use a bundle that has been minified, therefore the names were replaced with shorter ones.

You can hide this type of warning if it bothers you:

```
import { LogBox } from 'react-native';

LogBox.ignoreLogs(['Warning: Got a component with the name']);
```

**Comment by Ibnunds** [comment]
> Hey @Ibnunds,
> 
> This warning popups up when you try to use a bundle that has been minified, therefore the names were replaced with shorter ones.
> 
> You can hide this type of warning if it bothers you:
> 
> ```
> import { LogBox } from 'react-native';
> 
> LogBox.ignoreLogs(['Warning: Got a component with the name']);
> ```

oh noted, but actually i used react native typescript for the MiniApp is it causing the warning?

**Comment by jbroma** [comment]
It doesn't matter whether typescript was used or not, it's all transpiled to plain JS anyways :) 

You can also disable minifaction of the mini-app bundle and this error will go away since names will be preserved.
Please note that if you used webpack-bundle it uses production mode therefore minifaction was enabled.

**Comment by Ibnunds** [comment]
> It doesn't matter whether typescript was used or not, it's all transpiled to plain JS anyways :)
> 
> You can also disable minifaction of the mini-app bundle and this error will go away since names will be preserved. Please note that if you used webpack-bundle it uses production mode therefore minifaction was enabled.

i tried to change the miniapp base to javascript and the warning is gone, but when using the typescript with the same base the warning will shown up

**Comment by Ibnunds** [comment]
solved by using javascript project rather than typescript on mini app
