### ISSUE TITLE
does callstack repack help us skip google and appstore full app review process for updates once the app is released

### ISSUE THREAD

**Issue by gandhamsaicharan** [callstack/repack#437]
Suppose I'm making a change in mini app. do host app needs to go through full app review?. or similar to react-native code push we can avoid full app review once app is released

**Comment by huytd2510** [comment]
I have tried it in my prj, and you can release the app without a review from Apple/google. But only JS code changes. You can host modules in CDN or somewhere. App host can fetch and can use the latest version.

**Comment by jbroma** [comment]
Hey @gandhamsaicharan,

what @huytd2510 says is indeed correct, if you have any native changes (like new version of `react-native` or new dependency with a native module) you will have to go through the app review process again. 

Please mind that AppStore/PlayStore don't look too favourably upon updates like this. Officially, we recommended to use this OTA functionality to only fix existing bugs, in compliance with both store's rulebook

**Comment by RafikiTiki** [comment]
Besides the native platform's technical limitations (no possibility to update the native code on the fly), you should be good if you don't drastically change the app functionality. As @jbroma mentioned, quickly applying bug fixes without waiting for app store approval is an excellent appliance for Repack-enabled applications and significantly tightens the feedback loop between you, the app creator, and the app's user base.

Please remember that any time you're introducing a significant new feature into the app, even though it is possible to do that with over-the-air updates, circumventing app store review – we recommend **not doing that**. Following the usual release process helps avoid surprises in these cases.
