### ISSUE TITLE
Host bundle remotely on a CDN

### ISSUE THREAD

**Issue by vlack-coder** [callstack/repack#438]
Hi so I bundled the miniapp and hosted the bundle on a cdn - "https://cdn.jsdelivr.net/gh/vlack-coder/repacbundle@main/assets/index.android.bundle"

then I added the cdn link to the container  -
    rnminiappone:
      'https://cdn.jsdelivr.net/gh/vlack-coder/repacbundle@main/assets/index.android.bundle',
      
 I got this error
<img width="388" alt="image" src="https://github.com/callstack/repack/assets/56041655/ab73f5b2-b43e-44d1-a300-dd0dd4f6be8b">

I used github release - "https://github.com/vlack-coder/repacbundle/releases/download/repack-android/rnminiappone.container.bundle" to host the bundle but I got the same thing too. 

Meanwhile it worked well when the miniapp ran locally on my system... Where am I getting it wrong... Thanks

github repo to test it out - https://github.com/vlack-coder/rn_super_app

This video below is from the main project I am working on and it worked well when I ran the miniapp locally

https://github.com/callstack/repack/assets/56041655/32128704-944f-4416-8177-de176ac27736

**Comment by huytd2510** [comment]
You should upload all files in the remote folder. Include chunk.bundle, ....

**Comment by vlack-coder** [comment]
Thanks @huytd2510  for the heads up... I thought it was the bundle from -`react-native webpack-bundle` I created in the asset file.
So I've uploaded all the files - https://github.com/vlack-coder/repacbundle/releases/tag/repack-android and I made reference to only the app1.container.bundle file -

```javascript
const resolveURL = Federated.createURLResolver({
    containers: {
           app1: 'https://github.com/vlack-coder/repacbundle/releases/download/repack-android/app1.container.bundle',
    },
  });
```
But I am stuck on the fallback loading screen in my suspense. I feel like I am missing something... Thank you

**Comment by huytd2510** [comment]
You should change
app1: 'https://github.com/vlack-coder/repacbundle/releases/download/repack-android/app1.container.bundle', -> app1: 'https://github.com/vlack-coder/repacbundle/releases/download/repack-android/[name][ext]',

**Comment by vlack-coder** [comment]
@huytd2510  Thanks so much, works like magic....
