### ISSUE TITLE
Can i build app host with local container?

### ISSUE THREAD

**Issue by huytd2510** [callstack/repack#439]
## Release with the local modules 
Hi. I have a question. I have an app Host and 5 modules. But I just want remote 4 modules. With the remaining module, I want to build it inside the apk/ipa. Is it possible?

For example
App Host
Module| Remote      | Local | 
--- | --- | ---|
A|  -  | X |  
B|   X   |  -  |
C| X   |   -  |
D| X   |   -  |
E| X   |   -  |

**Comment by jbroma** [comment]
Hey @huytd2510,

composition like this is possible, it requires a little bit of configuration but is doable and works, have a look at our TesterApp package, here in the Re.Pack repository, where we have both local and remote chunks at the same time.

**Comment by RafikiTiki** [comment]
Hey @huytd2510 

It requires appropriately configuring `RepackPlugin` in the webpack config. Let's use the `TesterApp` from Repack repo as an example: https://github.com/callstack/repack/blob/719c2ef3e1af0c82de8042de2c5c21ab88a287ea/packages/TesterApp/webpack.config.mjs#L290-L300

1. This particular configuration will make every file with `local` in the name an async chunk (which will still be embedded into the app bundle but, using lazy loading, will only be evaluated when it's needed – effectively making it _local_)
2. For all other files that are lazily imported but don't have the `.local` part in the filename – they will be treated as remote chunks.

I highly recommend going through the whole `Code Splitting` section in the docs, they are very helpful in understanding these concepts: https://re-pack.netlify.app/docs/code-splitting/concept

**Comment by huytd2510** [comment]
@RafikiTiki @jbroma, thank you so much. I will give feedback soon.

**Comment by huytd2510** [comment]
Hi @RafikiTiki, @jbroma Sorry about the late reply. I have read code splitting. But I have one more question
With the upon example. 
Suppose all modules have other repo and diffidence locations in my devices. How can the app host link the local chunk/container?

Let me explain in more detail. 

Module| Remote      | Local |  Location repo module
--- | --- | ---| ---|
A|  -  | X |  /download/A
B|   X   |  -  | /workspace/B
C| X   |   -  | workspace/C
D| X   |   -  | /desktop/D
E| X   |   -  | /destop/E

Location of app host: /workspace/host. 

Note: Modules A, B, C, D, and E => can run alone without a host.

Another example is the app https://github.com/callstack/super-app-showcase/tree/55d722262f200562410cff2acbff33b8d48f8eed

I want to auth modules to be included inside the apk/IPA. Do you know how I can do this? Is it possible?

Thanks guys.
