### ISSUE TITLE
can not use repack for windows

### ISSUE THREAD

**Issue by thuno** [callstack/repack#440]
i was used windows 10 and react-native-cli as the instructions, my was crashed by  **webpack_require** does not exist

**Comment by jbroma** [comment]
Hey @thuno,

we are trying to resolve issue with Windows, however your error points to another problem - did you use `react-native webpack-start` to start the development server?

**Comment by jbroma** [comment]
also, try changing your `webpack.config` from `.mjs` to `.cjs` (copy it from the the root of repo here), this should make the Re.Pack work for Windows for now

**Comment by jbroma** [comment]
Hey @thuno,

we've recently released [Re.Pack 3.5.0](https://github.com/callstack/repack/releases/tag/%40callstack%2Frepack%403.5.0) which address a major issue for users on Windows. Try updating `@callstack/repack` to the newest version and see whether your issue is still relevant, thanks!
