### ISSUE TITLE
Cannot find module 'path' 'assert' and 'fs' from @babel

### ISSUE THREAD

**Issue by Ibnunds** [callstack/repack#447]
## Ask your Question

<img width="1104" alt="Jepretan Layar 2023-10-17 pukul 15 24 46" src="https://github.com/callstack/repack/assets/146713357/1fee852c-8f61-4ecf-b861-eeaee3464208">

this error shown after installing jest and react native testing library

below is my webpack.config.js
<img width="764" alt="Jepretan Layar 2023-10-17 pukul 15 27 53" src="https://github.com/callstack/repack/assets/146713357/4e5d7add-ea52-4d90-a2c1-9440cab5a841">

![Screenshot_1697531331](https://github.com/callstack/repack/assets/146713357/4f357bf3-8b50-4521-a84d-025430e316cf)
error on emulator

is there any missing configuration on my webpack.config.js ?

**Comment by jbroma** [comment]
Hi @Ibnunds,

could you please create a reproduction repository with the problem you're having? The information you've provided is not enough to diagnose the issue.

**Comment by Ibnunds** [comment]
<img width="766" alt="Jepretan Layar 2023-10-18 pukul 10 40 11" src="https://github.com/callstack/repack/assets/146713357/03a27e3d-4bed-4fd0-89f2-dc7a4fa8b8d7">
Solved by adding configuration as above in webpack.config.js

**Comment by jbroma** [comment]
While I'm glad you've managed to resolve your issue, i'm curious about one thing - are this runtime errors or Were these errors happening when running tests?

**Comment by Ibnunds** [comment]
> While I'm glad you've managed to resolve your issue, i'm curious about one thing - are this runtime errors or Were these errors happening when running tests?

Its error on runtime, I also don't know why suddenly such an error like that appears after doing jest setup. And i need to npm install path-browserify and assert then added the fallback to webpack.config.js
