### ISSUE TITLE
How to remove  / delete mini app when downloaded from Federated.importModule

### ISSUE THREAD

**Issue by saravanan6137** [callstack/repack#449]
## Ask your Question
Hi
1. How do I remove the downloaded mini app like this.
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  const containersURL = getContainersURL({
    hostname: process.env.SAS_CATALOG_SERVER_URL,
    version: appVersion,
    platform: Platform.OS,
    appName,
  });

  const containersResponse = await fetch(containersURL);

  const containers = await containersResponse.json();

  const resolveURL = Federated.createURLResolver({
    containers,
  });

  let url;
  if (__DEV__ && caller === 'main') {
    console.log('came 1:', containers)
    url = Script.getDevServerURL(scriptId);
  } else {
    console.log('came 2:', containers)
    url = resolveURL(scriptId, caller);
  }
  console.log('scriptid:', scriptId)
  console.log('url:', url)

  if (!url) {
    return undefined;
  }

  return {
    url,
    cache: !__DEV__,
    query: {
      platform: Platform.OS, // only needed in development
    },
    verifyScriptSignature: __DEV__ ? 'off' : 'strict',
  };
});
Lets say I have a logic that some mini app is inactive I need to delete that mini app which is downloaded by the user once. So how do I remove that mini app.

2. Downloading the mini app bundles from external based on url and if I increase the version of the url and next time when it checks old url vs new url and if there is mismatch then will it automatically download the latest? (Following the same steps to download mini app as above)

**Comment by RafikiTiki** [comment]
1. To remove the mini-app script/scripts downloaded, you'll need to keep track of the scriptIds yourself and then use `ScriptManager.invalidateScripts` method ([see docs](https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#invalidatescripts)). A demo implementation can be found in the TesterApp:
https://github.com/callstack/repack/blob/b68b6142af7c88d309dd6593efc165c42344dc4c/packages/TesterApp/src/remoteChunks/RemoteContainer.tsx#L37-L47

2. Yes, Repack will use the url as one of the params checked during cache verification. For a given script/chunk if the url has changed – it will get refetched and if that's successful – replaced. For more context please check out the following code:
https://github.com/callstack/repack/blob/b68b6142af7c88d309dd6593efc165c42344dc4c/packages/repack/src/modules/ScriptManager/Script.ts#L186-L201

**Comment by saravanan6137** [comment]
<img width="910" alt="Screenshot 2023-10-24 at 2 46 49 PM" src="https://github.com/callstack/repack/assets/68968235/fd24be5a-dca1-4681-bfdc-fcc6062fe5f8">
Tried removing the news app from super-app-showcase, but still when I open the news mini app second time it loads directly not downloading again since I have invalidated that script.

**Comment by saravanan6137** [comment]
<img width="882" alt="Screenshot 2023-10-24 at 5 05 42 PM" src="https://github.com/callstack/repack/assets/68968235/7834f525-8307-4a9d-b0e3-005ca1e05b91">
Here I see that for the second import it wont load the sam container twice, but what if I want to remove that container on button click and when user visits the same screen second time (second time) I want the container to be fetched and evaluated again like the first time.

**Comment by thymikee** [comment]
@saravanan6137 does this happen in release mode as well, or only in development? When in dev, by default chunk's cache is invalidated

**Comment by saravanan6137** [comment]
<img width="844" alt="Screenshot 2023-10-28 at 12 43 40 AM"
<img width="855" alt="Screenshot 2023-10-28 at 12 45 42 AM" src="https://github.com/callstack/repack/assets/68968235/a280ecd3-dbd4-45c2-aa80-3ea34b49310f">
 src="https://github.com/callstack/repack/assets/68968235/24352b51-4343-40dd-838c-883f4e29d5e0">
 
I am running in dev mode but I found this, when I run first time it downloads and second time it directly loads. Then I added a button to invalidate the respective script. After invalidating ScriptManager.shared.on('invalidated') triggers. Then when I close the app and lunch again and when I go to the invalidated mini app it crashes. (Actual behaviour is to redownload the script and load the app right). I attached the screenshots of how I am loading the script with event (.on event) also and how I am invalidating the script. Please advice.

**Comment by saravanan6137** [comment]
<img width="673" alt="Screenshot 2023-10-28 at 12 49 42 AM" src="https://github.com/callstack/repack/assets/68968235/467f8bdb-8ebe-44ae-9611-0f6caef307e3">

Invalidation method screenshot

**Comment by saravanan6137** [comment]
<img width="629" alt="Screenshot 2023-10-28 at 1 16 15 AM" src="https://github.com/callstack/repack/assets/68968235/0676986d-06ab-4e72-96f5-9e5a2822b1bb">
Also I set cache to be true.

**Comment by saravanan6137** [comment]
Hi, can please give the example of how to remove the cached news mini app which is loaded externally (external github)

**Comment by saravanan6137** [comment]
<img width="890" alt="Screenshot 2023-11-01 at 1 31 38 AM" src="https://github.com/callstack/repack/assets/68968235/f741678d-b073-4325-959a-2bde3be7e6b6">
I changed the repack code like this and it works, can you please check on this and in any latest version we have any fix like this?

**Comment by huytd2510** [comment]
Hi, @saravanan6137 . I have a question. After I have called invalidateScripts scripts. Then, I tried to go to this module. The second time, it doesn't load from the remote. Do you have any suggestions?

**Comment by saravanan6137** [comment]
<img width="653" alt="Screenshot 2023-11-06 at 11 41 06 AM" src="https://github.com/callstack/repack/assets/68968235/33c0be92-5a48-4721-aff4-5bbc7b168d77">
after calling the invalidate scripts, it will come here, do any customisations here. Here only I also changed to remove the cache

**Comment by saravanan6137** [comment]
File name - scriptManager.js

**Comment by sriharshaarangi** [comment]
I was also facing issue with `invalidateScripts` method. The file is getting deleted, but the entry in sqlite db is not getting cleared. On debugging it, it looks like there is a [bug in `invalidateScripts` method](https://github.com/callstack/repack/blob/main/packages/repack/src/modules/ScriptManager/ScriptManager.ts#L414 ). `resolveScripts` method appends caller to the `scriptId` to get the cacheKey (```const cacheKey = `${scriptId}_${caller ?? 'unknown'}`;```), while `invalidateScripts` directly uses `scriptId` as the cacheKey.

**Comment by jbroma** [comment]
@sriharshaarangi that's a great find, are you willing to open a PR with fix for this?

**Comment by sriharshaarangi** [comment]
@jbroma I am having few queries before getting into the fix:

1. [Documentation says](https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#resolvescript) `Name of the calling script - it can be for example: name of the bundle, chunk or container.` However, that appears inaccurate. `main` appears to be the default caller. Actual value `main` does not come into either of those categories.
2. Should default caller value be made `main` instead of `unknown`?
3. I am unable to grasp what value the caller is adding for cacheKey in the first place. Can you please help elaborate, or point me to any other documentation?

**Comment by sriharshaarangi** [comment]
@jbroma I am having few queries before getting into the fix:

1. [Documentation says](https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#resolvescript) `Name of the calling script - it can be for example: name of the bundle, chunk or container.` However, the default value is `main` which is not the default bundle/chunk/container name.
2. Should default caller value be made `main` instead of `unknown`?
3. I am unable to grasp what value the caller is adding for cacheKey in the first place, if the underlying downloaded file  is the same irrespective of the caller value (I am assuming so as per the downloaded chunk file name). Can you please help elaborate, or point me to any other documentation behind the design decision?

**Comment by jbroma** [comment]
@sriharshaarangi Let's move this to a separate issue and discuss it there please 🙏

**Comment by sriharshaarangi** [comment]
Created - https://github.com/callstack/repack/issues/553
