### ISSUE TITLE
React Native and HMR client disconnected immediately after connection

### ISSUE THREAD

**Issue by krzysztofzaluski** [callstack/repack#450]
Hi, I'm trying to migrate existing project to use Re.Pack and I'm facing with an error in servers logs after I try to run android with command:
`react-native run-android --no-packager`

Logs:

> ⇢ [11:40:08.258Z][LoggerPlugin] Compiling android: 100%  
> ℹ [11:40:12.225Z][DevServer] React Native client connected { clientId: 'client#0' } 
> ℹ [11:40:12.238Z][DevServer] HMR client connected { clientId: 'client#0', platform: 'android' } 
> ℹ [11:40:13.950Z][DevServer] HMR client disconnected { clientId: 'client#0', platform: 'android' } 
> ℹ [11:40:13.951Z][DevServer] React Native client disconnected { clientId: 'client#0' } 

and app freezes like just before the splashscreen.

When I kill the app and try to launch it again it's immediately closed with Application Not Responding and "App keeps stopping" alert with one line of log:

> ℹ [11:46:33.571Z][DevServer] Hermes device connected { deviceId: 2 } 

Any ideas how to resolve that or track what's the cause of that problem?
Thanks

**Comment by jbroma** [comment]
Hi @krzysztofzaluski,

The information you've provided is not enough for me to diagnose this issue, could you please create a reproduction repository so we can get to the bottom of this?

**Comment by krzysztofzaluski** [comment]
hey @jbroma 
sorry but the project is very big and complex and I can't share the code but fortunately I've resolved that issue
I looked in the native android logs in Logcat and I was able to track down the problem
I had two errors, the first was a Theme error in AndroidManifest:

> You need to use a Theme.AppCompat theme (or descendant) with this activity

and it turned out to be a problem with the "react-native-bootsplash" library, the solution was to bump the version to 4.7.5

the second problem was the error:

> Uncaught ReferenceError: regeneratorRuntime is not defined

and it was caused by the Reactotron configuration, which I have temporarily disabled and now I'm trying to reconfigure it again

**Comment by RafikiTiki** [comment]
I'm glad that you were able to resolve the issues. Closing this for now, if you'll have any further problems please try to create small reproduction repo in which we can debug the issues, thanks!
