### ISSUE TITLE
Set AsyncStorage cause crash

### ISSUE THREAD

**Issue by rainjiang** [callstack/repack#456]
## Environment

"@react-native-async-storage/async-storage": "^1.19.3",
"react-native": "0.72.3",
"@callstack/repack": "^3.5.1",
"webpack": "^5.89.0"

platform: iOS

## Description

When i  call 
```ScriptManager.shared.setStorage(AsyncStorage);```
it will crash when load async chunks
![Screenshot 2023-10-27 at 17 44 58](https://github.com/callstack/repack/assets/144203565/74f59cb5-9159-47e5-81de-e37e1c65a645)
![Screenshot 2023-10-27 at 17 48 39](https://github.com/callstack/repack/assets/144203565/4d055a30-0de7-4a0d-ae6b-eb0e5f3204fd)

there are not much human readable info

**Comment by jbroma** [comment]
Hey @rainjiang, 

since the error is native, it might indicate the issue with native module of either `Re.Pack` or `AsyncStorage`

does the AsyncStorage work in your project when you call it directly? For example:

```js
import AsyncStorage from '@react-native-async-storage/async-storage';

const storeData = async (value) => {
  try {
    const jsonValue = JSON.stringify(value);
    await AsyncStorage.setItem('my-key', jsonValue);
  } catch (e) {
    // saving error
  }
};

storeData('test');
```
