### ISSUE TITLE
Can't find variable: __wepack_require__ in ScriptManager.js

### ISSUE THREAD

**Issue by datdt-026** [callstack/repack#482]
**Environment**
React Native: 0.72.4
Repack: 3.7.0
Webpack: 5.89.0
OS: MacOS 13.5.2 - Chip M1 

**Description**
I'm using callstack/repack to build super app, it works well on Android but running on iOS, i'm facing that error
With the same project, i ran on MacOS 14.1.1 with Intel Chip well but on M1 chip it's not.
Is there any solution for this? 
Thank you.

Here is my  **index.js**

```
import React from "react";
import { AppRegistry, Platform } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import { ScriptManager, Script, Federated } from '@callstack/repack/client';
import appApi from './src/api/appApi';
import Slider from '@react-native-community/slider';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import messaging from '@react-native-firebase/messaging';

// Handle background messages using setBackgroundMessageHandler
messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', remoteMessage);
});

ScriptManager.shared.addResolver(async (scriptId, caller) => {

    const containers = {}
    containers['01014799689484027398304'] = 'http://10.0.2.2:6998/[name][ext]';
    // containers['90349279303689920881142'] = 'http://10.0.2.2:6998/[name][ext]';
    // containers['92113831404793824233142'] = 'http://10.0.2.2:6997/[name][ext]';
    // containers['9184570116497492142'] = 'http://10.0.2.2:6998/[name][ext]';
    //   containers['29503170284484683670146'] = 'http://10.15.144.116:6996/[name][ext]';
    // containers['90349279303689920881142'] = 'http://10.15.144.116:6997/[name][ext]';
    // containers['57609231104055066915142'] = 'http://10.0.2.2:6998/[name][ext]';

    const rs = await appApi.getAllApp();
    if (rs.code == 200) {
        var miniApps = rs.data;
        for (let i = 0; i < miniApps.length; i++) {
            containers[miniApps[i].id] = miniApps[i].url;
        }
    }

    console.log(5555555, containers)

    const resolveURL = Federated.createURLResolver({
        containers,
    });

    let url;
    let token;
    if (__DEV__ && caller === 'main' && false) {
        url = Script.getDevServerURL(scriptId);
    } else {
        url = resolveURL(scriptId, caller);
    }
    console.log('00000000', url)
    if (!url) {
        return undefined;
    }
    console.log('123123123', url)
    return {
        url,
        cache: false,
        headers: { dfe: '123' },
        query: {
            platform: Platform.OS, // only needed in development
        },
        verifyScriptSignature: 'off'

    };
});


/**
 * We can also add a listener to the ScriptManager to get notified about the loading process. This is useful for debugging.
 *
 * This is optional and can be removed.
 */
ScriptManager.shared.on('resolving', (...args) => {
    console.log('DEBUG/resolving', ...args);
});

ScriptManager.shared.on('resolved', (...args) => {
    console.log('DEBUG/resolved', ...args);
});

ScriptManager.shared.on('prefetching', (...args) => {
    console.log('DEBUG/prefetching', ...args);
});

ScriptManager.shared.on('loading', (...args) => {
    console.log('DEBUG/loading', ...args);
});

ScriptManager.shared.on('loaded', (...args) => {
    console.log('DEBUG/loaded', ...args);
});

ScriptManager.shared.on('error', (...args) => {
    console.log('DEBUG/error', '111111111111');
    console.log('DEBUG/error', ...args);
});

export function Root() {
    return <App />;
}

AppRegistry.registerComponent(appName, () => Root);


// import { AppRegistry } from 'react-native';
// import App from './App';
// import { name as appName } from './app.json';

// AppRegistry.registerComponent(appName, () => App);

```

My **Podfile**

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '12.4'
prepare_react_native_project!

pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => static
  $RNFirebaseAsStaticFramework = true
end

target 'meid_app' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  target 'meid_appTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('callstack-repack')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```
![IMG_7888](https://github.com/callstack/repack/assets/71490730/1d0dc1d7-4055-412c-8dfd-0aa72454d5d4)

**Comment by jbroma** [comment]
Hi @datdt-026,

are you sure you've used `webpack-start` command everytime? This kind of error usually happens when you bundle with `metro` instead of `webpack` by mistake. If this is not the case, please provide a reproduction repository so I can help see what's wrong with your setup, thanks!

**Comment by datdt-026** [comment]
yes i've change the script start with `webpack-start --host --port`, i run on xcode and it auto show up the `metro` instead of `webpack`, i stop the `metro`, start with `webpack` and it show another error with `yarn` like this.
![IMG_7891](https://github.com/callstack/repack/assets/71490730/d25419f4-b762-4060-a211-50c9661cf670)

**Comment by jbroma** [comment]
You can remove the build phase witch starts the metro server in development in XCode to get rid of this. However, since you also start Re.Pack you should be just fine with clicking on `Reload JS` on the simulator.

Another thing that comes to my mind is that if you don't use the default port of `8081`, and you want to run the app through XCode it might require changing in some place. I'm not sure where to change it in XCode (i'll get back to you on that), but when running iOS through CLI, you should also pass `--port`, and that should match the port used with `webpack-start`.

**Comment by jbroma** [comment]
perhaps @szymonrybczak can help with that?

**Comment by datdt-026** [comment]
I'm using the default port `8081`. When i stop `metro`, start `webpack`, it show the error with the images above.
I reloadJS on my device and it show that.
Here is my repo: https://github.com/datdo26/meid_app
Thank you for seeing what's wrong in my setup.

**Comment by jbroma** [comment]
Hey @datdt-026,

I can launch the app normally both through CLI & XCode without any issues.

One thing I needed to fix was to add `react-freeze` to transformed `node_modules` in `webpack.config`. Also the app was missing some modules which you removed, so after adding the rule and commenting out the missing modules in source code I was able to get everything running smoothly.

I've also noticed that your start command does not pass `port` argument properly:
```
"start": "react-native webpack-start --host 127.0.0.1 -- port 8081"
```
as there is a unnecessary space between `--` and `port`. But it still defaults to port 8081 so it doesn't matter in this case.

**Comment by datdt-026** [comment]
Sorry for replying late. 
I added `react-freeze` like you said. The host-app ran, i connected to the dev server. 
But when i chose mini-app, it showed the loading indicator like i coded before but the mini-app did not run. It showed the error with call stack like this.
Really hope for your reply. Thank you so much.
<img width="604" alt="image" src="https://github.com/callstack/repack/assets/71490730/fec14730-41e4-4389-b233-9b0e4ab5b5a1">
<img width="780" alt="image" src="https://github.com/callstack/repack/assets/71490730/e02a5912-d7fd-45f4-b0b6-17be20586492">

**Comment by datdt-026** [comment]
> Hey @datdt-026,
> 
> I can launch the app normally both through CLI & XCode without any issues.
> 
> One thing I needed to fix was to add `react-freeze` to transformed `node_modules` in `webpack.config`. Also the app was missing some modules which you removed, so after adding the rule and commenting out the missing modules in source code I was able to get everything running smoothly.
> 
> I've also noticed that your start command does not pass `port` argument properly:
> 
> ```
> "start": "react-native webpack-start --host 127.0.0.1 -- port 8081"
> ```
> 
> as there is a unnecessary space between `--` and `port`. But it still defaults to port 8081 so it doesn't matter in this case.

OMG, i run it successfully.
I upgrade the `callstack/repack` to `3.6.0` and run with --host with wifi IP.
Thank you so much, Merry Xmas and Happy New Year! <3

**Comment by datdt-026** [comment]
@jbroma, Is there any way for the debbuger, I always using react-native-debbuger to debug the project and see the network activity.
