### ISSUE TITLE
Error in bundling micro apps with react-native-svg packages

### ISSUE THREAD

**Issue by elizabethinFy** [callstack/repack#486]
Error while creating bundle files for micro apps with svg dependency using bundle command (pnpm bundle:ios && pnpm bundle:android) 

ERROR in resolving fallback for shared module react-native-svg
Module not found: Error: Can't resolve 'react-native-svg' in ' host-mobile-app/packages/auth/src/screens/authModule/authView'
resolve 'react-native-svg' in ' host-mobile-app/packages/auth/src/screens/authModule/authView'
  Parsed request is a module
  using description file:  host-mobile-app/packages/auth/package.json (relative path: ./src/screens/authModule/authView)
    Field 'react-native' doesn't contain a valid alias configuration
    Field 'browser' doesn't contain a valid alias configuration
    Field 'main' doesn't contain a valid alias configuration
    resolve as module
       host-mobile-app/packages/auth/src/screens/authModule/authView/node_modules doesn't exist or is not a directory
       host-mobile-app/packages/auth/src/screens/authModule/node_modules doesn't exist or is not a directory
       host-mobile-app/packages/auth/src/screens/node_modules doesn't exist or is not a directory
       host-mobile-app/packages/auth/src/node_modules doesn't exist or is not a directory
      looking for modules in  host-mobile-app/packages/auth/node_modules
        single file module
          using description file:  host-mobile-app/packages/auth/package.json (relative path: ./node_modules/react-native-svg)
            no extension
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg doesn't exist
            .ios.ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.ios.ts doesn't exist
            .ios.js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.ios.js doesn't exist
            .ios.tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.ios.tsx doesn't exist
            .ios.jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.ios.jsx doesn't exist
            .native.ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.native.ts doesn't exist
            .native.js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.native.js doesn't exist
            .native.tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.native.tsx doesn't exist
            .native.jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.native.jsx doesn't exist
            .ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.ts doesn't exist
            .js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.js doesn't exist
            .tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.tsx doesn't exist
            .jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.jsx doesn't exist
            .json
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/packages/auth/node_modules/react-native-svg.json doesn't exist
         host-mobile-app/packages/auth/node_modules/react-native-svg doesn't exist
       host-mobile-app/packages/node_modules doesn't exist or is not a directory
      looking for modules in  host-mobile-app/node_modules
        single file module
          using description file:  host-mobile-app/package.json (relative path: ./node_modules/react-native-svg)
            no extension
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg doesn't exist
            .ios.ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.ios.ts doesn't exist
            .ios.js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.ios.js doesn't exist
            .ios.tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.ios.tsx doesn't exist
            .ios.jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.ios.jsx doesn't exist
            .native.ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.native.ts doesn't exist
            .native.js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.native.js doesn't exist
            .native.tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.native.tsx doesn't exist
            .native.jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.native.jsx doesn't exist
            .ts
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.ts doesn't exist
            .js
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.js doesn't exist
            .tsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.tsx doesn't exist
            .jsx
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.jsx doesn't exist
            .json
              Field 'react-native' doesn't contain a valid alias configuration
              Field 'browser' doesn't contain a valid alias configuration
              Field 'main' doesn't contain a valid alias configuration
               host-mobile-app/node_modules/react-native-svg.json doesn't exist
         host-mobile-app/node_modules/react-native-svg doesn't exist
       node_modules doesn't exist or is not a directory
      /Users/elizabeth.pradeep/Desktop/node_modules doesn't exist or is not a directory
      /Users/elizabeth.pradeep/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.88.2 compiled with 1 error and 1 warning in 45986 ms

P.S: Bundles were created for other micro apps without svg dependency

Package version :  "react-native-svg": "12.1.1"

**Comment by jbroma** [comment]
hi @elizabethinFy 

Judging by the error, you're probably trying to share module (`react-native-svg`) without using it anywhere in the host of that dependency. If that's the case you should add `require.include('react-native-svg')` inside of index.js inside your host app. Let me know if that helped
