### ISSUE TITLE
[RFC] sync API

### ISSUE THREAD

**Issue by troZee** [callstack/repack#493]
The TM provides the ability to provide a synchronous function call via JSI. Do we need these synchronous methods in the Re.Pack? 

Here you can find an example API:
```
    loadScript(scriptId: string, config: Object): Promise<Object>;
    loadScriptSync(scriptId: string, config: Object): Object
```

Hence, the dev could use the sync or async method if needed. 

_Originally posted by @troZee in https://github.com/callstack/repack/pull/344#discussion_r1173638141_

**Comment by jbroma** [comment]
@troZee please update the description 🙏 thanks!

**Comment by troZee** [comment]
@jbroma done

**Comment by jbroma** [comment]
Personally, I'm not sure whether sync API is useful as `loadScript` is called only for the async chunks right now. 

The only thing that comes to mind where this would be helpful is that we could split the the main chunk into smaller chunks and allow them to be OTA updated. As all chunks would be required at startup, the sync API could prove useful there.

**Comment by RafikiTiki** [comment]
Typically a user should see a loading screen/indicator when a script is being fetched and evaluated. Having sync API for loading a script would only make sense for [local async chunks](https://re-pack.netlify.app/docs/code-splitting/local-vs-remote-chunks/#local-chunks) but then it would be a little quirky to decide whether to use sync or async method 🤔

**Comment by jbroma** [comment]
I agree with @RafikiTiki, we would need to integrate it in a way that would allow for such optimisation in this rare case and keep async `loadScript` as default.

**Comment by troZee** [comment]
Thank you for your input. I am closing it since it does not make any sense in our case.

**Comment by RafikiTiki** [comment]
Yeah, keeping the async as the default sounds good! And since we have a technological possibility to implement a sync method let's do that – maybe someone will benefit from it in a way that's not obvious to us now.

**Comment by jbroma** [comment]
@thymikee WDYT

**Comment by thymikee** [comment]
Agree on keeping the default. How big of a maintenance investment would it be to implement, test and document the `loadScriptSync` method? Frankly I would wait for the opportunity to solve the real problem to arise before publishing the API and hoping for adoption

**Comment by DivyatejaChe** [comment]
> Typically a user should see a loading screen/indicator when a script is being fetched and evaluated. Having sync API for loading a script would only make sense for [local chunks](https://re-pack.netlify.app/docs/code-splitting/local-vs-remote-chunks/#local-chunks) but then it would be a little quirky to decide whether to use sync or async method 🤔
> 
> Edit: on top of that, in the linked docs we discourage users from using local chunks if they are using Hermes because it might result in degraded performance.

hey @RafikiTiki , do you have any results/ performance benchmarks that support this statement? For any super-app development, are there any guidelines around when/ how to choose certain parts of your app as Remote vs Local Chunks?
