### ISSUE TITLE
callstack_repack-Swift.h file not found

### ISSUE THREAD

**Issue by jefmoraes** [callstack/repack#498]
I'm having a failure when executing the application build in Xcode 15, I installed the pods correctly but I don't know why this happens, I have another project and everything happened correctly there

<img width="273" alt="Captura de Tela 2024-02-08 às 16 38 31" src="https://github.com/callstack/repack/assets/82906124/ce34029c-1a5e-46a4-aba6-1dc7724a8bd5">
<img width="733" alt="Captura de Tela 2024-02-08 às 16 38 52" src="https://github.com/callstack/repack/assets/82906124/6d8a3d64-27bd-4937-9ce2-4bf860b6b508">

I discovered that the file that should be generated is not being generated by Xcode in DerivedSources the generated file is **callstack_repack _vers.c** when it should be **callstack_repack-Swift.h**
<img width="312" alt="Captura de Tela 2024-02-22 às 11 49 33" src="https://github.com/callstack/repack/assets/82906124/f6d7eb19-84ee-48d4-8ae4-1612cf0d8b5b">

**Comment by jbroma** [comment]
@jefmoraes @sternlucas can you provide me with your cocoapods version being used in the projects?

**Comment by jbroma** [comment]
@jefmoraes @sternlucas I'm not able to reproduce this issue on a fresh `react-native` project created using CLI, can you provide even more details about your environment? Here is what i tried it on:

1. System: Sonoma 14.1
2. Xcode: 15.2
3. Ruby: 2.7.6
4. Cocoapods: 14.3
5. Node: 20.11.1

**Comment by mlakmal** [comment]
@jbroma seeing same issue when i tried to integrate re.pack to existing application

Sonomae 14.3.1
XCode 15.2
Ruby 2.7.6
cocoapods 1.11.2
node 16.14.2

react-native 0.68.6
@callstack/repack ^3.7.0

i tried setting up superapp example and it worked fine with above core deps

**Comment by jbroma** [comment]
@mlakmal did you run pod install after adding repack?

**Comment by mlakmal** [comment]
> @mlakmal did you run pod install after adding repack?

yes i did. it installed the Pods. below is the screenshot in xcode with pod files.
![Uploading Screenshot 2024-03-01 at 2.10.50 PM.png…]()

**Comment by jbroma** [comment]
looks related to #370

**Comment by jbroma** [comment]
Looks like it's related to #390, do you have `use_franeworks!` in your Podfile too?

**Comment by mlakmal** [comment]
i do see use_frameworks! in our podfile
let me give it a shot at above fix and let yall know...

**Comment by mlakmal** [comment]
that workaround did not resolve the issue for me.

fyi: point to note is that i had to manually link the callstack-repack in Podfile. wonder if thats causing the issue...

**Comment by lakmal-gentem** [comment]
Yes I am not sure what combination actually worked. I did all below and it's solved now. Tnx

- Add callstack as static in profile
- Add manual link in profile for callstack. Yarn didn't auto link...
- Re-setup ruby env

**Comment by jbroma** [comment]
@mlakmal @jefmoraes Potential fix for this issue has been merged, it will be included in `4.0.0-rc.2` which should be available today 🎉

If there is an option for you to test whether this fixes the problem without adjusting Podfile in your projects, please do and let me know if that helped 🙏

**Comment by mlakmal** [comment]
> @mlakmal @jefmoraes Potential fix for this issue has been merged, it will be included in `4.0.0-rc.2` which should be available today 🎉
> 
> If there is an option for you to test whether this fixes the problem without adjusting Podfile in your projects, please do and let me know if that helped 🙏

thanks for the fix. will try it later next week and get back to you!

**Comment by HebertGB** [comment]
> @mlakmal @jefmoraes Potential fix for this issue has been merged, it will be included in `4.0.0-rc.2` which should be available today 🎉
> 
> If there is an option for you to test whether this fixes the problem without adjusting Podfile in your projects, please do and let me know if that helped 🙏

I confirm that the repack upgrade from 3.7.0 to 4.0.0-rc-2 resolved this issue without need to add "pre_install ..." to Podfile.

**Comment by ichina** [comment]
> @mlakmal @jefmoraes Potential fix for this issue has been merged, it will be included in `4.0.0-rc.2` which should be available today 🎉
> 
> If there is an option for you to test whether this fixes the problem without adjusting Podfile in your projects, please do and let me know if that helped 🙏

i confirm that the issue is fixed in 4.0.0-rc-2

**Comment by mlakmal** [comment]
> > @mlakmal @jefmoraes Potential fix for this issue has been merged, it will be included in `4.0.0-rc.2` which should be available today 🎉
> > If there is an option for you to test whether this fixes the problem without adjusting Podfile in your projects, please do and let me know if that helped 🙏
> 
> thanks for the fix. will try it later next week and get back to you!

yes this is working on ours as well!
