### ISSUE TITLE
 Repack Navigation From Mini App To Main APP

### ISSUE THREAD

**Issue by Nazehs** [callstack/repack#514]
## Ask your Question

I am wondering how navigation works in repack. I am certain the back button navigation takes me back to the previous route on the stack but i am wondering how i can take a user from the mini page for example to the main page directly without using the back button.
In my use case, i want to go back to the main app because the navigations of the main app are not in the mini app when the mini app launches and i want them to be able to move back to the main app because of how my app is designed

**Comment by jbroma** [comment]
Hi @Nazehs,

if your `NavigationContainer` is in the host app and the mini-app is rendered within the component tree, then you could just do `navigation.navigate()` to any screen in the app that you want. Not much changes in that respect when using MF.
