### ISSUE TITLE
how to handle unavailability of modules in the host application

### ISSUE THREAD

**Issue by jefmoraes** [callstack/repack#526]
I have a question related to the **error handling process when consuming modules.** I have an app that is consuming a module from **my CDN**. When the **CDN is not available** I want to show something on the screen as an unavailable function, I didn't find anything about handling this type of thing with repack. When trying to consume the module in this situation my app crashes and I don't know how to deal with it, could you help me by giving me an example?

When trying to access the module my application gets stuck in the application index, so I want to know how to deal with this and show the user a message on the screen for example and make the app continue working without closing.

``` jsx
/**
 * @format
 */

import {AppRegistry, Platform} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import {Federated, ScriptManager} from '@callstack/repack/client';

ScriptManager.shared.addResolver(async (scriptId, caller) => {
  const resolveURL = Federated.createURLResolver({
    containers: {
      RepackModule: `http://myCDN.com/[name][ext]`,
    },
  });

  const url = resolveURL(scriptId, caller);
  if (url) {
    return {
      url,
      query: {
        platform: Platform.OS,
      },
    };
  }
});
AppRegistry.registerComponent(appName, () => App);
```

``` jsx
import React from 'react';
import {Federated} from '@callstack/repack/client';
import {ActivityIndicator, StyleSheet, View} from 'react-native';

const MiniApp = React.lazy(() =>
  Federated.importModule('RepackModule', './MiniApp'),
);

const FallbackComponent = () => (
  <View style={styles.container}>
    <ActivityIndicator color="rgba(56, 30, 114, 1)" size="large" />
  </View>
);

const MiniAppScreen = () => {
  return (
    <React.Suspense fallback={<FallbackComponent />}>
      <MiniApp />
    </React.Suspense>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default MiniAppScreen;
```

**Comment by jbroma** [comment]
@jefmoraes sorry for the late reply, I think what you're looking for are error boundaries. If the CDN fails then you could catch that with an error boundary and display a fallback component to handle this kind of situation gracefully.

Some resources:
1. Take a look at the [PR](https://github.com/callstack/super-app-showcase/pull/30) in the `super-app-showcase`
2. You could also use a package like this: [`react-native-error-boundary`](https://www.npmjs.com/package/react-native-error-boundary)

**Comment by vlack-coder** [comment]
Is it possible to reload mini app from error boundary @jbroma

**Comment by mlakmal** [comment]
you can also include local bundle with the host app and load that bundle when remote bundle fails...

**Comment by vlak-koder** [comment]
Hi @jbroma , navigating back and forth so that the component gets unmounted doesn't work... It only invalidates the cache when app relaunches

**Comment by vlak-koder** [comment]
@jbroma  also when asyncstorage is used to cache the miniapp, can we target the storage key and delete that cache manually instead of changing the url

**Comment by vlack-coder** [comment]
Hi @jbroma how do we invalidate the script to reload the app incase the app bundle download fails due to bad network... The only way to go about this for now is to reopen the app bwhich is not a good user experience. Thank you

**Comment by vlak-koder** [comment]
Hi @jbroma I would check if calling invalidateScript method will work in the ErrorBoundary. For now it doesn't work by unmounting the page
