### ISSUE TITLE
Adjust the description of `start` and `bundle` commands

### ISSUE THREAD

**Issue by jbroma** [callstack/repack#538]
## Describe the feature

Adjust the description of commands so that they don't include unsupported flags

## Motivation

Currently, we copy the the command descriptions from CLI commands and add our own flags. We should also adjust the copied descriptions, so that the `--help` output is up to date.

## Related Issues

proposed by @szymonrybczak  in #537

**Comment by szymonrybczak** [comment]
Is this issue still valid? What option do we miss inside Re.Pack CLI commands? 🤔

**Comment by jbroma** [comment]
It's still valid, hard to tell what's missing, haven't looked at that yet - we simply need to go through every flag and check if it makes sense in Re.Pack and/or add missing ones (specific to Re.Pack)

**Comment by barttom** [comment]
@jbroma @szymonrybczak 
Hey guys!
I've checked all options in the start command and a few in the bundle command. Looks like every option works fine so I;m confused, about how I can investigate that

**Comment by barttom** [comment]
@jbroma @szymonrybczak  when You have a moment :) 
https://github.com/callstack/repack/pull/656
