### ISSUE TITLE
Release App Crashing on Codepush update Install

### ISSUE THREAD

**Issue by vlack-coder** [callstack/repack#547]
## Environment

react : 18.2.0
react-native : 0.72.5
repack : 3.7.0
webpack : 5.90.0

## Description

My app is crashing in release mode with codepush... and it gives the same error as though we are running a repack project with metro in development mode... Checking the phone logs, I get this error
<img width="831" alt="image" src="https://github.com/callstack/repack/assets/56041655/22fbd667-17c4-4a79-8075-77efd31efc2d">

## Reproducible Demo

1. Create a new react native project
2. add repack with the CLI
3. Add appcenter's codepush
4. configure codepush in the project
5. Create a release APK/IPA 
6. make changes to your code then push new update OTA
7. When Release APK installs new Update it crashes

**Comment by vlack-coder** [comment]
I'm providing a repo with:

- Fresh React Native installation (0.72.5)
- I installed codepush and React native progress (to show the progress of the OTA downloaded)

Repo - https://github.com/vlack-coder/repack_codepush

**Comment by jbroma** [comment]
Hey @vlack-coder

As stated in the docs:  `Officially, CodePush is only supported if you're not using Code Splitting.`. 

We have a guide on how to get it to work here: `https://re-pack.netlify.app/docs/code-splitting/code-push` but I'm not sure how up to date that info is. Give it a try if you haven't already.

Summoning @RafikiTiki as I believe he did some experiments with `CodePush` not that long ago

**Comment by vlack-coder** [comment]
Hi @jbroma , I'm aware of the guide of using CodePush with Code Splitting but  I don't understand step 5 to 7 of the guide
<img width="550" alt="image" src="https://github.com/callstack/repack/assets/56041655/5337924c-e641-4867-995b-7b1f375072e8">

**Comment by vlack-coder** [comment]
@jbroma I'm aware of cache invalidation  but in my case, I'm not trying to invalidate the mini app cache. 
I'm trying to update the host app bundle with what comes from codepush.

And I think the problem is the command that appcenter uses to create a bundle to push to appcenter... 
So it creates this bundle with metro instead of webpack... Because the error I'm getting is of this nature -
`ReferenceError: Property '__webpack_require__' doesn't exist, js engine: hermes, stack:`

**Comment by jbroma** [comment]
@vlack-coder I'm not familiar with CodePush setup tbh, what command are you using?
