### ISSUE TITLE
ChunkLoadError on Android

### ISSUE THREAD

**Issue by gedeagas** [callstack/repack#55]
## Environment
Android 10. 
React Natvie 64.2

## Description

So my build is finished successfully, the main bundle is generated but somehow the chunk is not getting copied to the APK resulting in ChunkLoadError. 

<img width="329" alt="Screen Shot 2021-07-15 at 8 07 25 PM" src="https://user-images.githubusercontent.com/8868908/125793231-2532e096-f6cc-4d60-a128-703433c3b75f.png">

When I run manually with this command, the chuck is in the correct assets folder. 
```npx react-native webpack-bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle```

<img width="1273" alt="Screen Shot 2021-07-15 at 7 54 03 PM" src="https://user-images.githubusercontent.com/8868908/125792580-f680301e-14fb-40f3-8053-9a7a131077fc.png">

So I suppose the problem is that the bundle is not getting copied by react-native Gradle because the APK doesn't have any of the chunks that they are supposed to have.

<img width="567" alt="Screen Shot 2021-07-15 at 8 05 28 PM" src="https://user-images.githubusercontent.com/8868908/125793002-f8814d22-8c56-4a9c-a765-2a3bb9355317.png">

**Comment by zamotany** [comment]
Can you prepare a repro project? Something is wrong with the way your project is being built, because it should never load chunk with such URI - `noop://`.

**Comment by zamotany** [comment]
Also make sure you're building with `dev=false` from Gradle. `npx react-native webpack-bundle ...` works because you're passing `--dev false` manually, but it looks like the build from Gradle is passing `dev` as `true`.

**Comment by gedeagas** [comment]
> 
> 
> Also make sure you're building with `dev=false` from Gradle. `npx react-native webpack-bundle ...` works because you're passing `--dev false` manually, but it looks like the build from Gradle is passing `dev` as `true`.

let me double check again. And i will try to create a repro project. 

Thanks for the swift response @zamotany

**Comment by gedeagas** [comment]
@zamotany i can't make the repro yet but i just added a logger in the webpack config. 

The build from Gradle is indeed on production mode. 
<img width="595" alt="Screen Shot 2021-07-17 at 12 47 22 AM" src="https://user-images.githubusercontent.com/8868908/125988777-c0e5e515-aefb-4505-b7c1-2dbbf25330f4.png">

I even manually disabled the hmr.

```
entry: [
    ...ReactNative.getInitializationEntries(reactNativePath, {
      hmr: false,
    }),
    entry,
  ],
```
 
But somehow the index.bundle is still includes the hmr code.

**Comment by gedeagas** [comment]
@zamotany here is a barebone demo https://github.com/gedeagas/hmr-bug even when i build the bundle from this repo i can see the `noop:///` code with a reference of hmr in there. Is that the expected behaviour?

**Comment by DanijelBojcic** [comment]
I'm getting the same error in release builds. ( both android and iOS )

### Description
It seems like the local chunks are not included in the apk. 
When I inspect the iOS `.app` file there is only a `main.jsbundle`.

I have checked the `dev` variable in the config and its `false`.

### Crashlytics stack trace: 
```
Fatal Exception: com.facebook.react.common.c: ChunkLoadError: Loading chunk 9557 failed.
(resolution: 9557)
```

### Versions:
```
repack: 2.5.1,
react-native: 0.65.1,
webpack: 5.65.0,
```

**Comment by zamotany** [comment]
> It seems like the local chunks are not included in the apk.

Have you specified `localChunk` property in `OutputPlugin` in your Webpack config?

**Comment by DanijelBojcic** [comment]
I think so...

```
  new ReactNative.OutputPlugin({
      platform,
      devServerEnabled: devServer.enabled,
      remoteChunksOutput: path.join(__dirname, "build", platform, "remote"),
      localChunks: /\.chunk\.(js)?bundle$/,
    }),
```

**Comment by DanijelBojcic** [comment]
Maybe I should have mentioned that we use monorepo and we have multiple targets/flavors.

**Comment by zamotany** [comment]
@DanijelBojcic `localChunks` matches only chunk `name` (or `id` if can cannot be obtained), so `/\.chunk\.(js)?bundle$/` won't match anything. If you want to match everything you should provide `/.*/` instead. If you want only specific chunks I suggest to:
1. Use `/* webpackChunkName: "myChunk" */`
2. Set `localChunks: ['myChunk']` or `localChunks: [/myChunk/]`

**Comment by andreszuluaga-wolox** [comment]
@zamotany  how to generate the apk and the ipa to include the local chunks

**Comment by zamotany** [comment]
Local chunks should be included in the apk/ipa by default. Are you getting any errors?

**Comment by jd1378** [comment]
I have the same problem
after setting `localChunks` to `[/.*/]` it seems the chunks make their way into the apk, but it seems to me that despite using `webpackChunkName` in `import()`, and using `chunkFilename: '[name].chunk.bundle',` in webpack config, chunks still get named randomly (like `462.chunk.bundle`)
So it fails
