### ISSUE TITLE
Brotli decompression

### ISSUE THREAD

**Issue by sstatsuya** [callstack/repack#590]
## Ask your Question

Can someone assist me with decompressing a module on both Android and iOS when I'm using the Brotli algorithm for compression? 
Here is the preferred compression method: https://webpack.js.org/plugins/compression-webpack-plugin/#using-brotli

**Comment by jbroma** [comment]
hi @sstatsuya 

we currently don't support decompressing downloaded scripts like that, this is something that would need to be added to the native module of Re.Pack since fetching of the scripts happens on the native layer. PRs welcome 🙏
