### ISSUE TITLE
Apk not launching

### ISSUE THREAD

**Issue by omotayoR1** [callstack/repack#593]
![WhatsApp Image 2024-04-30 at 15 55 35_3ba35583](https://github.com/callstack/repack/assets/97170749/a730348e-ecff-41bc-ad28-41942dc93a56)
![errorimage1](https://github.com/callstack/repack/assets/97170749/53c30a55-a61d-4a23-8aa0-8b548f8bdc93)
Attached to this is the error i am encountering. The apk builds successfully but does not compile successfully. It stops at 99.7% as shown in the second image. As result of this, the apk doesnt launch successfully, can you please help fix this. I use windows. Thanks

**Comment by jbroma** [comment]
Hi @omotayoR1,

I've managed to track down the root cause of this issue - this is related to using Node 21 (or 22) same as #595 which was fixed today, and the fix will be available later this week. Thanks for providing the screenshot that includes the node version, that helped a lot!

**Comment by omotayoR1** [comment]
> Hi @omotayoR1,
> 
> I've managed to track down the root cause of this issue - this is related to using Node 21 (or 22) same as [this one](https://github.com/callstack/repack/issues/595) which was fixed today, and the fix will be available later this week. Thanks for providing the screenshot that includes the node version, that helped a lot!
> 
> Closing this issue as it's the same as #595

Hello thanks for the response. Please is the new update available now

**Comment by jbroma** [comment]
@omotayoR1 yes, the fix is already released inside of Re.Pack `4.0.0`

**Comment by omotayoR1** [comment]
> @omotayoR1 yes, the fix is already released inside of Re.Pack `4.0.0`

Hello, I have installed the latest version and it bundled correctly, can i use this in an existing project?

Thanks

**Comment by omotayoR1** [comment]
> @omotayoR1 yes, the fix is already released inside of Re.Pack `4.0.0`

Hello, please can you provide an example of how to use it like this example https://github.com/paaber/superapp-repack-reprod... i have tried upgrading the re-pack version in that reprod repo to 4.0.0 but i keep getting build error
