### ISSUE TITLE
ERROR while setting up code signing

### ISSUE THREAD

**Issue by pttchsswk** [callstack/repack#594]
## Ask your Question

I am trying to include code signing in my Re.Pack project using these two as references - https://github.com/callstack/repack/pull/348 & https://github.com/callstack/super-app-showcase/pull/43/
 
I am getting the following errors - please help fix this

![Screenshot 2567-05-02 at 14 32 47](https://github.com/callstack/repack/assets/158119549/0e5ce57d-b877-44c9-9c83-d6dac11a318f)

**Comment by jbroma** [comment]
Hi @pttchsswk,

Please provide a reproduction repository with your setup, I'm not able to do so with just the screenshot you've provided.

Btw, docs for `CodeSigningPlugin` should be available later this week (for the v4 version), perhaps you will be able to solve it yourself with them.

**Comment by jbroma** [comment]
@pttchsswk I've closed this issue since we've added docs for code-signing available here:

https://re-pack.dev/4.x/docs/plugins/code-signing

If you still can't get it to work please open a new issue with a reproduction repository included so we can dig deeper into the problem you are/were having
