### ISSUE TITLE
Error: repack react native module was not found. Did you forget to update native dependencies?

### ISSUE THREAD

**Issue by DivyatejaChe** [callstack/repack#598]
## Ask your Question

<img width="252" height="500" alt="Screenshot 2024-05-07 at 04 46 16" src="https://github.com/callstack/repack/assets/54347537/57ba1ed3-aca0-4896-a95d-701a89c4bfa7">

- Error observed when setting up Re.Pack in an existing monorepo created using YARN workspaces
- Reproducible repo: `repack` branch in [this repo](https://github.com/DivyatejaChe/dfCore/tree/repack)
- Issue reproducible on both Android and iOS
- Performed `pod install` too
- Please note that I have hoisted all the dependencies at the root level of the monorepo only
- Path for Bundle React Native code and images set as follows
```
set -e

WITH_ENVIRONMENT="../../../node_modules/react-native/scripts/xcode/with-environment.sh"
export BUNDLE_COMMAND=webpack-bundle
REACT_NATIVE_XCODE="../../../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

**Comment by DivyatejaChe** [comment]
hello @jbroma , can you help take a look into this, please?

**Comment by jbroma** [comment]
@DivyatejaChe

The reproduction repository you've provided is not public, therefore I won't be able to assist you directly. You can contact jakub.stadniczuk@callstack.com if you want us to take a closer look at that.

Have you tried using the latest RC release `4.0.0-rc.2`? Perhaps the issue will resolve itself when you use it, we fixed a ton of things since `3.7.0`.

**Comment by DivyatejaChe** [comment]
hey @jbroma , I just made the repo public. Can you please take a look?

**Comment by DivyatejaChe** [comment]
As for the latest RC release, is there any breaking changes from 3.x.x? @jbroma

**Comment by jbroma** [comment]
@DivyatejaChe thanks, I'll take a look tomorrow. As for the migration process, it should be relatively smooth, you can check [last few release notes](https://github.com/callstack/repack/releases), should be all listed there. Migration guide is in the works.

**Comment by jbroma** [comment]
@DivyatejaChe after taking a quick look - please don't add `@callstack/repack` in the root of your repo, instead add it as a `devDependency` of each app where you use it. That's probably why autolinking was failing and your module was not found. Please see if that helps.

**Comment by DivyatejaChe** [comment]
> @DivyatejaChe after taking a quick look - please don't add `@callstack/repack` in the root of your repo, instead add it as a `devDependency` of each app where you use it. That's probably why autolinking was failing and your module was not found. Please see if that helps.

hey @jbroma, thanks for the help! I upgraded to 4.0.0 and was able to run. Congrats on the new release!
