### ISSUE TITLE
How to config webpack to reuse existing dependencies from the main bundle

### ISSUE THREAD

**Issue by trinhhcse** [callstack/repack#620]
## Ask your Question
Hi team,
I try to using repack v4 with Module Federation plugin in sub app  but after run webpack bundle size. The output bundle still content shared dependencies (react, react-native). 
I research from document
`Beware, with dynamic scripts there's no dependency sharing by default. If you want your scripts to reuse existing dependencies from the main bundle, it's up to you to figure out how to do it. A good starting point would be:
https://webpack.js.org/configuration/externals/
https://webpack.js.org/plugins/dll-plugin/`

How to config webpack dll plugin in host app and miniapp to reuse existing dependencies from the host app bundle (react, react-native)
Thanks team.

**Comment by jbroma** [comment]
@trinhhcse 

Correct me If I'm wrong, but I'm guessing you are talking about the shared dependencies still being present in the output directory of the mini-app despite being declared shared right?

**Comment by trinhhcse** [comment]
@jbroma Yes, that’s right.

**Comment by jbroma** [comment]
You can add `import: false` to shared dependency config to prevent that (next to `singleton` and `eager`, for each dep)

**Comment by trinhhcse** [comment]
I tried it. It works like a charm. Thanks you.
