### ISSUE TITLE
build bundle mini app

### ISSUE THREAD

**Issue by HongQuang231** [callstack/repack#655]
## Ask your Question

when i update repack version to v4, I cannot use command
react-native webpack-bundle --platform ios --entry-file index.js --dev false

and it throw error 

RangeError: Maximum call stack size exceeded
    at /Users/hongquang/Documents/fis/super-app-project/erequestApp/node_modules/@callstack/repack/dist/webpack/plugins/OutputPlugin.js:101:36
    at Array.flatMap (<anonymous>)
    at getAllInitialChunks (/Users/hongquang/Documents/fis/super-app-project/erequestApp/node_modules/@callstack/repack/dist/webpack/plugins/OutputPlugin.js:101:28)
    at /Users/hongquang/Documents/fis/super-app-project/erequestApp/node_modules/@callstack/repack/dist/webpack/plugins/OutputPlugin.js:102:16
    at Array.flatMap (<anonymous>)
   

can you help me build bundle mini app like repack v3 @jbroma , thanks

**Comment by jbroma** [comment]
Hi @HongQuang231,

we have a pending fix for that in #646

**Comment by hosseinmd** [comment]
I have a module federation app. I tested your fix PR, but it's not worked. Same Error happened.
