### ISSUE TITLE
Error: Can't resolve 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance

### ISSUE THREAD

**Issue by aw-capgemini** [callstack/repack#657]
## Environment
- **Repack Version**: v4
- **React Native Version**: 0.72.0
- **Node Version**: 19
- **Operating System**: macOS
- **Platform**: Android

## Description
Error after upgrading from repack v3 to v4 when bundling for production
I encountered an error while running the pnpm bundle:android command. 

## Error Message

            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.android.jsx doesn't exist
          .native.jsx
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.native.jsx doesn't exist
          .jsx
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.jsx doesn't exist
          .android.ts
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.android.ts doesn't exist
          .native.ts
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.native.ts doesn't exist
          .ts
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.ts doesn't exist
          .android.tsx
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.android.tsx doesn't exist
          .native.tsx
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.native.tsx doesn't exist
          .tsx
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.tsx doesn't exist
          .android.json
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.android.json doesn't exist
          .native.json
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.native.json doesn't exist
          .json
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.json doesn't exist
          as directory
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance doesn't exist

webpack 5.92.1 compiled with 1 error and 2 warnings in 13029 ms 
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance' in '/Users/cgemployee/Projects/rahul/Digico/node_modules/.pnpm/react-native-gesture-handler@2.17.1_react-native@0.72.0_react@18.2.0/node_modules/react-native-gesture-handler/src'
    at /Users/cgemployee/Projects/rahul/Digico/node_modules/.pnpm/webpack@5.92.1/node_modules/webpack/lib/sharing/ConsumeSharedPlugin.js:187:12
    at finishWithoutResolve (/Users/cgemployee/Projects/rahul/Digico/node_modules/.pnpm/enhanced-resolve@5.17.0/node_modules/enhanced-resolve/lib/Resolver.js:567:11)
    at /Users/cgemployee/Projects/rahul/Digico/node_modules/.pnpm/enhanced-resolve@5.17.0/node_modules/enhanced-resolve/lib/Resolver.js:656:15
            Field 'react-native' doesn't contain a valid alias configuration
            Field 'browser' doesn't contain a valid alias configuration
            Field 'main' doesn't contain a valid alias configuration
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance.json doesn't exist
          as directory
            /Users/cgemployee/Projects/rahul/Digico/packages/host/node_modules/react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance doesn't exist
 ELIFECYCLE  Command failed with exit code 2.
cgemployee@Arjays-MacBook-Pro host % 

### Steps to Reproduce
1. Run the command `pnpm bundle:android`
2. Observe the error message

### Expected Behavior
The bundling process should complete successfully.

**Comment by jbroma** [comment]
@aw-capgemini can you show your resolution config (`config.resolve`)? The defaults from V4 should easily resolve RN in this case. Perhaps this is a matter of hoisting dependencies in your config?

**Comment by jbroma** [comment]
Closing since the issue has been stale for a long time and not enough has been provided to investigate this.

**Comment by VadzimAlkhimionak** [comment]
I had the same error. @jbroma @aw-capgemini did you know how to fix it?

**Comment by jbroma** [comment]
solution to this issue: https://github.com/callstack/repack/issues/761#issuecomment-2585919493
