### ISSUE TITLE
i try to add react-native-reanimated-carousel lib to project

### ISSUE THREAD

**Issue by HongQuang231** [callstack/repack#659]
## Ask your Question

i try to add react-native-reanimated-carousel lib to mini project but it not working, can you help me? @jbroma 
and it has error 
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __loaded__ listeners added. Use emitter.setMaxListeners() to increase limit]

**Comment by har2008preet** [comment]
use `ScriptManager.shared.setMaxListeners(number)`
