### ISSUE TITLE
Stuck while loading bundles on second app launch with cache flag enabled

### ISSUE THREAD

**Issue by hafiz-azman-cd** [callstack/repack#660]
## Environment

Localhost dev

## Description

Hello I've tried to enable caching in my project following the [caching and versioning](https://re-pack.dev/docs/code-splitting/caching-versioning) guide. The app runs with all the remotes loaded and working the first time I launch it. However, if I close the app and launch it again, it gets stuck at the launch screen.

I initially thought it was an issue with the project code, but the same problem occurs when I try it with the sample project [super-app-showcase](https://github.com/callstack/super-app-showcase).

<img width="1135" alt="image" src="https://github.com/callstack/repack/assets/141902138/a7ca866e-8218-4eaf-a734-f970c986d122">

I've tried to debug and it seems like it stuck at `Federated.importModule()`.

I didn't get this issue if I set the cache flag to false, but then the app downloads the remote bundles every time I need to access them, which is not optimal.

## Reproducible Demo

1. Clone and setup [super-app-showcase](https://github.com/callstack/super-app-showcase)
2. In
	`packages/booking/index.js`
	`packages/dashboard/index.js`
	`packages/host/index.js`
	`packages/shell/index.js`
	`packages/shopping/index.js`

	Add
	```
	import AsyncStorage from '@react-native-async-storage/async-storage';

	...

	ScriptManager.shared.setStorage(AsyncStorage);

	...
	```
	and set `cache: true`

**Comment by jbroma** [comment]
Hi @hafiz-azman-cd, please check the [related PR](https://github.com/callstack/repack/pull/680#issuecomment-2266841405) and try the canary version and see if fixes your issue, thanks!

**Comment by hafiz-azman-cd** [comment]
Hello @jbroma I was testing the canary lib with [super-app-showcase](https://github.com/callstack/super-app-showcase). I manage to get it running and enabled the caching based on [here](https://re-pack.dev/docs/code-splitting/caching-versioning). I wasn't sure what to expect with the cache enabled. I still see the app requesting the bundle files from the dev server instead of loading from AsyncStorage when the app is killed and relaunched. I debugged the AsyncStorage and confirmed that the bundle files are present in their key-value pairs when the cache is enabled.

What I did in super-app-showcase:

1. `pnpm remove -r @callstack/repack --save-dev`
2. Update `devDependencies.json` > @callstack/repack > version change to `@callstack/repack@4.2.0-canary-20240803153933`
3. `pnpm add -r @callstack/repack@4.2.0-canary-20240803153933 -D`
4. `pnpm pods`
5. Update booking, dashboard, shell and shopping `index.js` to enable cache as in [here](https://re-pack.dev/docs/code-splitting/caching-versioning)
6. `pnpm start + pnpm run:host:ios`

**Comment by vlack-coder** [comment]
Hi @hafiz-azman-cd  do we really need step 5, If we're testing just the host.
Also, switching to the new version did not fix the Caching issue

**Comment by vlack-coder** [comment]
Hi @jbroma , So I switched to the canary version but I still have caching issue.

I enabled cache in the host, create a release build

### Bug Description and Reproduction
- Open the app for the first time
- Open Booking, wait for it to load completely
- Do the same for Shopping, News and Dashboard Min Apps
- Close the App and reopen
- Open Booking, Booking gets stuck at loading screen
- Same thing happens in Shopping and News
- But Dashboard which is the last Mini App I opened when I opened the app for the first time opens correctly and gets cached

index.js of Host 
```js 
/**
 * @format
 */

import { Federated, Script, ScriptManager } from '@callstack/repack/client';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { AppRegistry, Platform } from 'react-native';
import { name as appName } from './app.json';
import App from './src/App';

!__DEV__ && ScriptManager.shared.setStorage(AsyncStorage);

ScriptManager.shared.addResolver(async (scriptId, caller) => {
  const RealContainers = {
    auth: 'https://github.com/vlack-coder/repacbundle/releases/download/repack/[name][ext]',
    booking:
      'https://github.com/vlack-coder/repacbundle/releases/download/booking/[name][ext]',
    dashboard:
      'https://github.com/vlack-coder/repacbundle/releases/download/dashboard/[name][ext]',
    news: 'https://github.com/vlack-coder/repacbundle/releases/download/news/[name][ext]',
    shopping:
      'https://github.com/vlack-coder/repacbundle/releases/download/shopping/[name][ext]',
  };
  const resolveURL = Federated.createURLResolver({
    containers: RealContainers,
    // containers,
  });

  let url;
  if (false) {
    // if (__DEV__ && caller === 'main') {
    url = Script.getDevServerURL(scriptId);
  } else {
    url = resolveURL(scriptId, caller);
  }
  console.log('repackurl', url);

  if (!url) {
    return undefined;
  }

  return {
    url,
    cache: !__DEV__,
    query: {
      platform: Platform.OS, // only needed in development
    },
    // verifyScriptSignature: __DEV__ ? 'off' : 'strict',
  };
});

AppRegistry.registerComponent(appName, () => App);

```

[Link to Repo](https://github.com/vlack-coder/superapp_clone/tree/repackCache) - https://github.com/vlack-coder/superapp_clone/tree/repackCache

**Comment by jbroma** [comment]
Hi @vlack-coder, 

I managed to narrow down the issue to files being overridden on the native side, (on the device storage).

Here is the example of what's happening:

1. Request `auth` mini-app:
    - Download and cache `auth.container.bundle`
    - Download and cache `vendor-1.chunk.bundle`
    - _**Download and cache `vendor-2.chunk.bundle`**_
    - Auth fully loaded

2. Request `booking` mini-app
    - Download and cache `auth.container.bundle`
    - _**Download and cache `vendor-2.chunk.bundle`**_
    - Download and cache `vendor-3.chunk.bundle`
    - Booking fully loaded

Downloading `booking` will override `vendor-2.chunk.bundle` on the filesystem, which originally comes from `auth` so on the next startup, when loading auth, wrong content will be loaded and our app ends up in an rather undefined state 😅 

Working on a fix!

**Comment by vlak-koder** [comment]
@jbroma , I thought as much, The last opened minapp overrides the previously opened miniapp. Thank you.

**Comment by jbroma** [comment]
@vlak-koder please check this canary release: https://www.npmjs.com/package/@callstack/repack/v/4.2.0-canary-20240808200412

**Comment by jbroma** [comment]
@vlak-koder @hafiz-azman-cd  please check this canary release: https://www.npmjs.com/package/@callstack/repack/v/4.2.0-canary-20240808200412

Please remember to:
- install the canary release
- iOS: reinstall pods and rebuild the app 
- Android: rebuild the app

The cache in the super app showcase should work correctly with this change.

**Comment by hafiz-azman-cd** [comment]
@jbroma I'm happy to report that it works now in the super-app-showcase!

I loaded the booking feature for the first time, then killed the app. After relaunching and clicking on booking again, it no longer requests the bundle file from the dev server. Great work and thanks!

I have the super-app-showcase with the cache enabled pushed [here](https://github.com/hafiz-azman-cd/super-app-showcase-cache-enabled) if anyone wants to check it out.

**Comment by vlak-koder** [comment]
Hi @jbroma , thank you, it's no longer stuck on the loading screen for this new update 

Just an observation, when I was testing from my end and i opened the micro app, it looked as though there was a bundle download as my internet speed meter spiked up. 
Also, can we use this canary release in our current project

**Comment by jbroma** [comment]
@vlak-koder please double check, ideally check with some network monitoring tool to verify this - nothing like this should be happening unless you set `shouldUpdateScript` to invalidate the cache.

I will release 4.2.0 today, no need to use the canary version

**Comment by vlak-koder** [comment]
@jbroma  noted, it might be the pictures in the micro app.
1 more thing, please I also have 2 issues I raised
- reloading micro apps - https://github.com/callstack/repack/issues/526#issuecomment-2276145383
- memory issues - https://github.com/callstack/repack/issues/675#issuecomment-2276132546

Any idea about them, thanks
