### ISSUE TITLE
Property '__webpack_share_scopes__' doesn't exist

### ISSUE THREAD

**Issue by chimcuccu258** [callstack/repack#667]
![IMG_0542](https://github.com/callstack/repack/assets/26501360/f89d69e3-9cbf-4450-9886-db5abdf44b82)
Can somebody please show me how to fix this issue? I can not open miniapp in hostapp.

**Comment by jbroma** [comment]
Hi @chimcuccu258, do you have `ModuleFederation` plugin in your host app? Seems like MF runtime module is not injected into the bundle.

**Comment by chimcuccu258** [comment]
![Screenshot 2024-07-11 at 08 41 53](https://github.com/callstack/repack/assets/26501360/570789cd-3222-4cfa-88ad-741fa81a8624)
I guess that I already have config for this

**Comment by jbroma** [comment]
@chimcuccu258, have you tried setting a name to a non-empty string?

**Comment by jbroma** [comment]
@chimcuccu258 please provide a reproduction repository if you think the problem lies with library and not just configuration

**Comment by jbroma** [comment]
Closing since the issue has been stale for a long time and no reproducer was provided. If you are still facing the issue please provide a minimal reproduction repository and I will reopen this issue.
