### ISSUE TITLE
PROBLEMS WITH NAVIGATION IN MICROFRONT FEDERATION

### ISSUE THREAD

**Issue by sergiohortua** [callstack/repack#682]
## Ask your Question

**Context:** In a directory I have two directories, "host" and "app1", in "app1" I have a 2-screen navigation and I expose that file in webpack.
In the "host" I import the microfront as follows: `const App1 = React.lazy(() => Federated.importModule('app1', './RoutesApp1'));`
When I launch the application I get the following error: _Invariant violation: I tried to register two views with the same name RNCSafeAreaProvider._
I already share the most relevant files. It already changes versions in the react-navigation dependencies but it continues to throw that error. This only happens to me with navigation. If I have a microfront without navigation there is no problem.

![image](https://github.com/user-attachments/assets/f0260265-ab21-43c7-b0e9-a5f738a4a6a3)

- How could I solve this issue

**FILES APP1:**
index-navigation
![image](https://github.com/user-attachments/assets/28c2efeb-5b42-41f6-9bd4-fad163784175)

app1.tsx
![image](https://github.com/user-attachments/assets/f905dde0-a68b-4534-8252-c897342a3286)

index.js
![image](https://github.com/user-attachments/assets/1b8878e6-a9d0-43a3-ba22-4988768984dd)

package.json
![image](https://github.com/user-attachments/assets/35d6d403-c71b-402a-bd24-d484c0184c7b)

plugin of webpack
![image](https://github.com/user-attachments/assets/bd7e72eb-575d-45c5-a72c-8a3db2c36a57)

**FILES HOST:**
index-navigation
![image](https://github.com/user-attachments/assets/2095af35-44fb-45f8-b3dd-447b98aadc2c)

app.tsx - host
![image](https://github.com/user-attachments/assets/0af5fcca-c416-414a-9e6a-6f42a2d6a400)

index.js -host
![image](https://github.com/user-attachments/assets/283d512e-ce83-48d8-ae46-19d3dcdcc139)

package.json
![image](https://github.com/user-attachments/assets/ad7356f2-97d4-400d-9d34-df50daac56a5)

plugin of webpack
![image](https://github.com/user-attachments/assets/9f726199-c061-4f10-9ca7-fa5ddd8614eb)

**Comment by jbroma** [comment]
hi @sergiohortua, 

you need to add every dependency with native module as shared to the `ModuleFederationPlugin` configuration in all of your webpack.configs.

**Comment by jbroma** [comment]
your host needs to provide all dependencies that have native modules - for JS-only dependencies there is no need for that.

Example:
Host has 4 dependencies, all declared as shared
App1 has 5 dependencies, 4 same as host + `react-native-reanimated` (as an example)

In this example you would need to add `react-native-reanimated` to the host app, even though host app doesn't use it. You also need to import it in the `index.js` of host so it doesn't get stripped way like this:

```ts
import 'react-native-reanimated';
```

If you don't do this, your app will crash since the native module is not present in the host app.

**Comment by sergiohortua** [comment]
@jbroma 
thank you my app funtionality perfect
