### ISSUE TITLE
handle a module's redux state from another module

### ISSUE THREAD

**Issue by sergiohortua** [callstack/repack#688]
## Ask your Question

 hi!.
I have the following file structure for a project:
![image](https://github.com/user-attachments/assets/b5aa5b25-3664-4069-bd8f-ed8487c381a4)

In the reduxProvider folder I created a redux to handle it from other modules. Leave the following webpack configuration to share the provider, store and slice. - "It's a redux of a counter that adds, subtracts and resets." -
![image](https://github.com/user-attachments/assets/28646165-a35c-4923-a499-b938ea275e72)
In the host module I already imported it and I can use the provider from the reduxProvider module.
![image](https://github.com/user-attachments/assets/e02a3074-0b2b-4c57-a68d-85dd0d28a35e)

**How can I use the reducer dispatch for increment, decrement and reset of the reduxProvider module from the host or any other module?**
![image](https://github.com/user-attachments/assets/0bdbcd12-3338-4e61-916e-1bc9de4d7248)

**Comment by sergiohortua** [comment]
please help!!

**Comment by sergiohortua** [comment]
@jbroma ???????

**Comment by rasheedk** [comment]
I used redux micro front end library to dispatch actions . You need to register actions , so that u can use anywhere in app.

**Comment by vlack-coder** [comment]
Hi @sergiohortua , what I did on my end was that I put the miniApp reducer in the host app and I shared the folder
```javascript
  shared: {
          './src/features/reduxSlice': {
            singleton: true,
            eager: true,
            requiredVersion: '1',
          },
	}
```
Don't put it under exposes, put it under the shared.
You can also pass state as props
```javascript
const MiniAPP = ({ route }: any) => {
  return (
    <ErrorBoundary name="Mini App">
      <React.Suspense fallback={<FallbackComponent />}>
        <MiniAPPNavigator params={route?.params} />
      </React.Suspense>
    </ErrorBoundary>
  );
};
```
