### ISSUE TITLE
Error when running from an NPM script

### ISSUE THREAD

**Issue by meienberger** [callstack/repack#71]
## Environment

MacOS 11.4
Node 16.6.1
@callstack/repack: 2.0.0-beta.7
concurrently: 6.2.1

## Description

When running the start command `npx react-native webpack-start` from an npm script with concurrently in my package.json I'm getting the following error :

```
TypeError: process.stdin.setRawMode is not a function
[1]     at Object.start [as func] (/Users/.../@callstack/repack/dist/commands/start.js:75:19)
```

My package.json start script :
`"dev:ios": "concurrently \"yarn ios\" \"npx react-native webpack-start\""`

## Reproducible Demo

Setup a basic project following the docs and use my script

**Comment by zamotany** [comment]
Can you try adding `--no-interactive` to `npx react-native webpack-start`?

**Comment by meienberger** [comment]
Thank you @zamotany this solved my issue. For reference on why this was an issue : https://nodejs.org/api/tty.html
