### ISSUE TITLE
Tried to register two views with the same name RCTText 

### ISSUE THREAD

**Issue by ra1nj** [callstack/repack#717]
### Describe the bug

I initialized 2 brand new react-native project, and setup with repack module federation,  i started the host app on iOS simulator, trying to load app1, but once the app1 build completed , it throw a error like this "Tried to register two views with the same name RCTText "
![Simulator Screenshot - iPhone 15 Plus - 2024-08-27 at 16 10 36](https://github.com/user-attachments/assets/623ca3dc-7215-4be3-8d2b-c818de204f4e)

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M3
  Memory: 263.16 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: ~/.nvm/versions/node/v20.5.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.5.1/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v20.5.1/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.2.0
    path: /Users/vn564c0/.rvm/rubies/ruby-3.2.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Re.Pack Version

4.3.1

### Reproduction

https://github.com/ra1nj/RepackHost , https://github.com/ra1nj/RepackApp1

### Steps to reproduce

1. install node dependencies for host and app1
2. pod install for host
3. run host on a iOS simulator

**Comment by jbroma** [comment]
you're running into a rare edge case - using `react-native` deep import - in this case `react-native/Libraries/NewAppScreen` which is causing this. 

At this moment I'm not sure how to solve this - I can only suggest not using deep imports from `react-native`

**Comment by hramadhaan** [comment]
same issue, any update ?

**Comment by jbroma** [comment]
if this is with the deep imports from react native then there is still no solution to that - otherwise it's down to configuring shared dependencies in the MF plugin i.e. a dependency should be in shared config but its not there so you get the runtime error like this
