### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]

### ISSUE THREAD

**Issue by michaeltugby0** [callstack/repack#721]
### Describe the bug

I just updated to the latest Repack and am unable to get a build going:
```Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'```
 I believe it's windows only. All I did was follow the Getting Started instructions and I was able to reproduce it.
Think the regression happened in 4.3.0, 4.2.0 builds fine.

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
  Memory: 10.01 GB / 31.85 GB
Binaries:
  Node:
    version: 20.12.2
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.5.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 33.0.1
      - 34.0.0
      - 35.0.0
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.18034.62.2411.12071903
  Visual Studio: Not Found
Languages:
  Java:
    version: 17.0.10
    path: /c/Program Files/Common Files/Oracle/Java/javapath/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Re.Pack Version

4.3.1

### Reproduction

https://github.com/michaeltugby0/repack-windows-bug

### Steps to reproduce

Run `yarn start` in one windows terminal, `yarn android` in another. Once it's built, the error gets thrown when bundling begins.

**Comment by jbroma** [comment]
@michaeltugby0 fix available in `4.3.2`
