### ISSUE TITLE
How to access host app's variable/functions within a miniapp ? 

### ISSUE THREAD

**Issue by ra1nj** [callstack/repack#722]
### Describe the bug

It's seems like if i shared through Host's ModuleFederationPlugin.exposes , it's actually a individual script context , the value i assigned in host becomes null in miniApp.
For example : i keep the NavigationContainer's ref in a variable called navigationRef, the value is assigned until NavigationContainer is rendered, so if shared through ModuleFederationPlugin.exposes, the navigationRef is just a null , because the imported module host from miniApp is a individual context(container).

So what's the right way to do this ? through global variable ?

### System Info

```shell
none
```

### Re.Pack Version

4.3.1

### Reproduction

none

### Steps to reproduce

none

**Comment by ra1nj** [comment]
https://github.com/callstack/repack/discussions/719

**Comment by jbroma** [comment]
> #719

Closing since this is not a bug but a question, and it's already posted in discussions.
