### ISSUE TITLE
Catalogue server being called repeatedly for each micro app- in  remote bundled builds. 

### ISSUE THREAD

**Issue by rasheedk** [callstack/repack#726]
### Describe the bug

If I am having 10 micro apps I am seeing that when ever I load the application ( remote build) , the catalogue server is being invoked 10 times to get version info of the bundles . As per n/w traces , all request and response are same. 

### System Info

```shell
repack 3.7 , rn 0.72.0
```

### Re.Pack Version

3.7

### Reproduction

na

### Steps to reproduce

If I am having 10 micro apps I am seeing that when ever I load the application ( remote build) , the catalogue server is being invoked 10 times to get version info of the bundles . As per n/w traces , all request and response are same.

**Comment by rasheedk** [comment]
Problem is there for both android & iOS remote bundled builds. If my micro apps are loaded from remote bundle server. This happens when ever I launch the app.

**Comment by vlack-coder** [comment]
@rasheedk , is it the Super App example that you experienced this issue in?
Can you also upgrade to the latest version to confirm if this issue still persists?
Lastly, Can you provide a sample repo let me try if I can recreate on my end?

**Comment by rasheedk** [comment]
https://github.com/callstack/super-app-showcase 
This example also works like that .

**Comment by vlack-coder** [comment]
> callstack/super-app-showcase

@rasheedk , check out this repo that was cloned from the superapp example - https://github.com/vlack-coder/superapp_clone/blob/cachefix?rgh-link-date=2024-08-20T11%3A10%3A35Z 

But it doesn't work that way... The catalogue server is called only when you the app is ran as a standalone where it's called in the index.js.  For instance, lets run the host app
 Follow this script 
- adbreverse
- start
- run:host:android
Then test for the min apps
