### ISSUE TITLE
The query inside ScriptLocator has been encoded twice

### ISSUE THREAD

**Issue by ra1nj** [callstack/repack#731]
### Describe the bug

I put my bundle on the azure storage, to request this bundle i need to put some token stuff inside the query,  then i found out that the query object is actually will be encoded twice, 
the first time is in js code
<img width="881" alt="Screenshot 2024-09-04 at 13 48 24" src="https://github.com/user-attachments/assets/179ec9be-6e63-46c6-ae0d-17aa1aa2e01d">
the second time is in native code
![Screenshot 2024-09-04 at 13 51 26](https://github.com/user-attachments/assets/c63a58a2-78d9-45fc-b70c-00c13395f97e)

this will cause some error when fetching the bundle, i assume this is a bug ?

### System Info

```shell
none
```

### Re.Pack Version

4.3.1

### Reproduction

none

### Steps to reproduce

put a property like this: t: '2024-09-04T04:56:27Z' inside query obj

**Comment by jbroma** [comment]
Hi @ra1nj,

this looks very valid, since you found the places in the code, can you make a PR with a fix for that? Currently I have no capacity to handle this.

**Comment by ra1nj** [comment]
OK, i will try to fix this,  also i will verify whether is this happening on android.

**Comment by ra1nj** [comment]
I have checked and it will not be encoded again on the android side.
https://github.com/callstack/repack/pull/739

**Comment by jbroma** [comment]
Fixed by #739
