### ISSUE TITLE
Tried to register two views with same name DebuggingOverlay

### ISSUE THREAD

**Issue by sumeet45** [callstack/repack#769]
### Describe the bug

Hi, 
I'm trying to create MFE application for mobile and web as well. While creating facing following issue. Anybody face this kind of issue earlier.

![shared image](https://github.com/user-attachments/assets/d681895c-1a4c-46fe-9d83-d7745c511b65)

Thanks in advance.

### System Info

```shell
React-Native 0.74.4
```

### Re.Pack Version

4.1.1

### Reproduction

-

### Steps to reproduce

-

**Comment by sumeet45** [comment]
I able to resolve this issue, by just updating react-native version. In package.json, earlier we have React-native version "0.74.4". so we change it to "0.74.0".

**Comment by jbroma** [comment]
> I able to resolve this issue, by just updating react-native version. As per error, there's package which is trying different version in app. so I thought, to update react-native version. In package.json, earlier we have React-native version "0.74.4". so we change it to "0.74.0".

Sounds very plausible - when doing MFE with RN we have to align react & react-native version perfectly in order to reuse it correctly. Glad you figured that out!

Closing since the issue was resolved

**Comment by hungdev** [comment]
for someone to come later:
In my case: I didnt put a stack navgiation in Stack.Screen. For example
```
expose moduleA = 
    <Stack.Navigator initialRouteName="Me">
        <Stack.Screen name="Me" component={MeScreen} />
    </Stack.Navigator>
```

Host App:
```
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
        <moduleA /> // This causes an error
      </Stack.Navigator>
    </NavigationContainer>
```
