### ISSUE TITLE
Cache value is not valid when script is failed

### ISSUE THREAD

**Issue by hosseinmd** [callstack/repack#770]
### Describe the bug

In some situation, for example network failed when loading a script, The failed script is cached.

### System Info

```shell
repack 4.3.3
react-native 75.4
```

### Re.Pack Version

4.3.3

### Reproduction

https://github.com/callstack/repack

### Steps to reproduce

Make your app fail to load remote script, then restart the app. Here the failed script doesn't download again, and it is trying to execute from cache, but there is no cache file.

**Comment by jbroma** [comment]
@hosseinmd, I'm finishing the work on MF2 and should release V5 RC very soon 🙏 
I would put this issue on hold until we can verify that it's also happening on V5

**Comment by hosseinmd** [comment]
Please review this https://github.com/callstack/repack/pull/771
I made a good test scenario which can show you the problem

**Comment by jbroma** [comment]
Thank you for handling this @hosseinmd!

Closing since this was fixed by #771. 

Fix available in `5.0.0-rc.0` version of Re.Pack.
