### ISSUE TITLE
index.js not running when using ModuleFederationPluginV2

### ISSUE THREAD

**Issue by ra1nj** [callstack/repack#794]
### Describe the bug

I am trying out the Repack5.0 with the ModuleFederationPluginV2, after i started the dev server,  the build was fine, no errors output, but the app is stuck on the splashscreen, index.js was not running at all. 
Any clues about that?

### System Info

```shell
none
```

### Re.Pack Version

5.0.0-rc.1

### Reproduction

none

### Steps to reproduce

none

**Comment by jbroma** [comment]
is this on iOS? if its iOS its probably because somehow on bridgeless the errors are not being displayed at startup and we're aware of that.

**Comment by ra1nj** [comment]
> is this on iOS? if its iOS its probably because somehow on bridgeless the errors are not being displayed at startup and we're aware of that.

Yes it is, I am using iOS,  I will try with android then 🤔

**Comment by ra1nj** [comment]
> is this on iOS? if its iOS its probably because somehow on bridgeless the errors are not being displayed at startup and we're aware of that.

Yes it is, I am using iOS,  I will try with android then 🤔

**Comment by jbroma** [comment]
can you try RN 0.76.2? There were some fixes to show EarlyJS errors there that [might help with this](https://github.com/facebook/react-native/commit/dac6d508afd0f919943d8053330d6314201319c3)

**Comment by ra1nj** [comment]
> can you try RN 0.76.2? There were some fixes to show EarlyJS errors there that [might help with this](https://github.com/facebook/react-native/commit/dac6d508afd0f919943d8053330d6314201319c3)

I managed to use android to running the project and i can see the errors , after i fixed those errors, the iOS is good now, i will try to upgrade the RN to 0.76.2 and revert my fix to see if it can output errors on iOS 🧐.

**Comment by ra1nj** [comment]
I upgraded the RN version to 0.76.2 but sadly it's the same with 0.76.1, nothing displayed on iOS, but it shows EarlyJsError on android.

![Image](https://github.com/user-attachments/assets/9614742a-8d68-4e7a-a668-7d18a3f71994)

**Comment by jbroma** [comment]
If the RN version didn't fix it then its def something in Re.Pack
