### ISSUE TITLE
[HMRClient] Cannot find update - full reload needed

### ISSUE THREAD

**Issue by ra1nj** [callstack/repack#795]
### Describe the bug

I am trying out the Repack5.0 with the ModuleFederationPluginV2, i followed the super-app-showcase repo to configure my project. 
But i encountered a bug:
once my mini-app loaded , the devServer of the mini-app says:
**[DevServer] File mini-app.233bb634f7c7647b.hot-update.json for android not found in compilation assets (no compilation in progress)** 
...
the devServer of the host app says:
 **[HMRClient] Cannot find update - full reload needed** 

Then the host app will do a fully reload, i never got the chance to render the mini-app.

### System Info

```shell
None
```

### Re.Pack Version

5.0.0-rc.1

### Reproduction

None

### Steps to reproduce

i'm not sure if the bug is caused by that i added babel-loader in the mini-app's rspack.config.mjs ,my mini-app relied on some babel plugin so configured the rule like following:
```
                 {
                    test: /\.[jt]sx?$/,
                    exclude: [/node_modules/],
                    type: 'javascript/auto',
                    use: [
                        {
                            loader: 'builtin:swc-loader',
                            /** @type {import('@rspack/core').SwcLoaderOptions} */
                            options: {
                                parseMap: true,
                                env: {
                                    targets: {
                                        'react-native': '0.74',
                                    },
                                },
                                jsc: {
                                    externalHelpers: true,
                                    transform: {
                                        react: {
                                            runtime: 'automatic',
                                            development: mode === 'development',
                                            refresh: mode === 'development' && Boolean(devServer),
                                        },
                                    },
                                },
                            },
                        },
                        {
                            loader: 'babel-loader',
                            // options: {
                            //     /** Add React Refresh transform only when HMR is enabled. */
                            //     plugins:
                            //         devServer && devServer.hmr
                            //             ? ['module:react-refresh/babel']
                            //             : undefined,
                            // },
                        },
                    ],
                },
```

**Comment by ra1nj** [comment]
Find a error before reloading:
✖ [01:38:34.549Z][Console] Warning: ReferenceError: Property 'exports' doesn't exist

**Comment by jbroma** [comment]
Hey, can you provide some details on what changes you've introduced to the config? Thanks!

**Comment by ra1nj** [comment]
I will try to make a reproduction repo

**Comment by jbroma** [comment]
Any luck?

**Comment by ra1nj** [comment]
Sorry for the late response, i haven't got the time to make a reproduction,  closing the issue for now , i will reopen it once i made a reproduction repo.

**Comment by jbroma** [comment]
> Sorry for the late response, i haven't got the time to make a reproduction, closing the issue for now , i will reopen it once i made a reproduction repo.

no worries - please try to always add a repro in the future, it's very time consuming to work on such issues with little information 👍
