### ISSUE TITLE
Repack v5 mdule federation (cannot read property 'shared' of undefined)

### ISSUE THREAD

**Issue by hosseinmd** [callstack/repack#805]
### Describe the bug

![Image](https://github.com/user-attachments/assets/4ef72909-fbdf-4893-b269-6679472ea8b4)

### System Info

```shell
react-native 75.4
```

### Re.Pack Version

5.0.0-rc.2

### Reproduction

.

### Steps to reproduce

yarn react-native webpack-start

**Comment by thymikee** [comment]
@hosseinmd please send some reproduction steps. In this form it's not actionable from our part to do anything with your issue. You can check our example apps or https://github.com/callstack/super-app-showcase/

**Comment by hosseinmd** [comment]
i found this issue,that was about config. but i have a lot of issues yet, i will came back if i can't fix them.
