### ISSUE TITLE
Error resolving only a subset of scales

### ISSUE THREAD

**Issue by nhnam** [callstack/repack#97]
## Ask your Question

In my project I load image like this
`
<Image
      style={styles.emptyIcon}
      source={require('../../../../images/inbox_nomessage.png')}
/>
`

But actually in my project i only have inbox_nomessage@3x.png
This is just to reduce the assets's size.
This approach works with react-native bundle, but I got error with react-native webpack-bundle because @1x and @2x ones are missing

**Comment by joe06102** [comment]
I think it would better to just remove the @3x suffix if you got only image.
